runner1:
  load: 1
  input_policy: short
runner2:
  load: 1
  input_policy: long
runner3:
  load: 1
  input_policy: mixed
runner4:
  load: 20
  input_policy: short
runner5:
  load: 20
  input_policy: long
runner6:
  load: 20
  input_policy: mixed
