"""Canvas token registration and resolution endpoints.

A canvas lives in Unify contexts under ``Canvas/*``: the authored source, the
compiled bundle, the resolved bindings and the declared actions are all rows
there. What is relational is only what console needs before it can read any of
that — which context, whose identity, and whether this canvas may be served at
all.

Two roles, deliberately split:

* **Unify** (``API_KEY_AUTH``) registers a token when it publishes a canvas,
  moves it between draft, published and quarantined, and revokes it on delete.
* **Console** (``ADMIN_AUTH``) resolves a token to the owner's identity so it can
  read the canvas row as that owner, and gets ``visibility`` and ``status`` back
  on the same call because it has to check both before using the admin key. It
  also executes a canvas's declared bindings on the viewer's behalf.

The read plane accepts an **alias and nothing else**. The dashboard tile bridge it
replaces takes ``context`` and ``filter`` from the client, which lets any token
holder query anything in the creator's project; here the server loads the canvas
record and runs the binding that was validated and dry-run at author time. A
compromised or prompt-injected canvas therefore cannot widen its own reach.

There is no bundle endpoint. The compiled module is stored on the canvas row
itself with its sha256, so console reads it through the ordinary logs API as the
owner and verifies the hash before handing the bytes to the frame. An endpoint
serving bundle bytes would be a second, weaker path to the same data.
"""

import hashlib
import json
import logging
import re
from datetime import datetime, timedelta, timezone
from types import SimpleNamespace
from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException, Path, Request, status
from sqlalchemy.orm import Session

from orchestra.db.dao.canvas_token_dao import CanvasTokenDAO
from orchestra.db.dependencies import get_db_session
from orchestra.web.api.canvas.schema import (
    CanvasActionDescriptor,
    CanvasActionsResponse,
    CanvasInvocationResponse,
    CanvasQueryRequest,
    CanvasQueryResponse,
    CanvasTokenResolutionResponse,
    CanvasTokenResponse,
    InvokeCanvasActionRequest,
    RegisterCanvasTokenRequest,
    UpdateCanvasTokenRequest,
)

# Tokens are generated by `secrets.token_urlsafe`, so this is the full alphabet
# they can contain. Validated as a path pattern because the token is interpolated
# into a filter expression when the canvas record is read.
TOKEN_PATTERN = r"^[A-Za-z0-9_-]{1,12}$"

# How the log query joins a list of field names. See `_fields`.
FIELD_SEPARATOR = "&"

logger = logging.getLogger(__name__)

router = APIRouter()
admin_router = APIRouter()


def _resolve_project_id(
    session: Session,
    *,
    user_id: str,
    organization_id,
    project_name: str,
) -> int:
    """Resolve a project the caller can actually reach.

    Going through ``filter_by_user_access`` rather than a name lookup is what
    stops a caller registering a token that points at somebody else's project.
    """
    from orchestra.db.dao.context_dao import ContextDAO
    from orchestra.db.dao.organization_member_dao import OrganizationMemberDAO
    from orchestra.db.dao.project_dao import ProjectDAO

    org_member_dao = OrganizationMemberDAO(session)
    context_dao = ContextDAO(session)
    project_dao = ProjectDAO(session, org_member_dao, context_dao)

    rows = project_dao.filter_by_user_access(
        user_id=user_id,
        organization_id=organization_id,
        name=project_name,
    )
    if not rows:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Project '{project_name}' not found or not accessible",
        )
    return rows[0][0].id


def _owned_entry(session: Session, token: str, user_id: str):
    """Fetch a token the caller owns, or raise.

    404 for missing and 403 for someone else's, rather than 404 for both: the
    token is already known to whoever holds the URL, so collapsing the two hides
    nothing and makes a real permission problem look like a typo.
    """
    dao = CanvasTokenDAO(session)
    entry = dao.get_by_token(token)
    if not entry:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Token not found",
        )
    if entry.user_id != user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You can only modify your own canvases",
        )
    return dao, entry


@router.get(
    "/canvas/tokens/{token}",
    response_model=CanvasTokenResponse,
    responses={
        200: {"description": "Token read"},
        403: {"description": "Not the owner"},
        404: {"description": "Token not found"},
    },
)
def read_canvas_token(
    request_fastapi: Request,
    token: str,
    session: Session = Depends(get_db_session),
) -> CanvasTokenResponse:
    """Read back one of the caller's own token registrations.

    Exists so the writer can tell its own retry from a genuine token collision:
    registration answers 409 for both, and treating the second as success would
    leave a canvas URL resolving to somebody else's view. Owner-scoped rather than
    admin, because confirming your own registration needs no wider reach.
    """
    _, entry = _owned_entry(session, token, request_fastapi.state.user_id)

    return CanvasTokenResponse(
        token=entry.token,
        context_name=entry.context_name,
        visibility=entry.visibility,
        status=entry.status,
    )


@router.post(
    "/canvas/tokens",
    response_model=CanvasTokenResponse,
    status_code=status.HTTP_201_CREATED,
    responses={
        201: {"description": "Token registered successfully"},
        404: {"description": "Project not found or not accessible"},
        409: {"description": "Token already exists"},
    },
)
def register_canvas_token(
    request_fastapi: Request,
    body: RegisterCanvasTokenRequest,
    session: Session = Depends(get_db_session),
) -> CanvasTokenResponse:
    """Register a token-to-context mapping for a canvas.

    Called by Unify once the canvas row is written. The token is generated there,
    so a collision is a genuine conflict rather than something to retry silently.
    """
    user_id = request_fastapi.state.user_id
    organization_id = request_fastapi.state.organization_id

    dao = CanvasTokenDAO(session)
    if dao.get_by_token(body.token):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Token '{body.token}' already exists",
        )

    project_id = _resolve_project_id(
        session,
        user_id=user_id,
        organization_id=organization_id,
        project_name=body.project_name,
    )

    entry = dao.register(
        token=body.token,
        context_name=body.context_name,
        project_id=project_id,
        user_id=user_id,
        organization_id=organization_id,
        visibility=body.visibility,
        status=body.status,
    )
    session.commit()

    return CanvasTokenResponse(
        token=entry.token,
        context_name=entry.context_name,
        visibility=entry.visibility,
        status=entry.status,
    )


@router.patch(
    "/canvas/tokens/{token}",
    response_model=CanvasTokenResponse,
    responses={
        200: {"description": "Token updated"},
        403: {"description": "Not the owner"},
        404: {"description": "Token not found"},
    },
)
def update_canvas_token(
    request_fastapi: Request,
    token: str,
    body: UpdateCanvasTokenRequest,
    session: Session = Depends(get_db_session),
) -> CanvasTokenResponse:
    """Change a canvas's visibility or lifecycle status.

    Quarantining is the kill switch: it stops the bundle, the data reads and the
    actions in one place, which is why it is a status on the routing row rather
    than a flag each read path checks for itself.
    """
    dao, _ = _owned_entry(session, token, request_fastapi.state.user_id)

    entry = dao.set_state(token, visibility=body.visibility, status=body.status)
    session.commit()

    return CanvasTokenResponse(
        token=entry.token,
        context_name=entry.context_name,
        visibility=entry.visibility,
        status=entry.status,
    )


@router.delete(
    "/canvas/tokens/{token}",
    status_code=status.HTTP_200_OK,
    responses={
        200: {"description": "Token deleted"},
        403: {"description": "Not the owner"},
        404: {"description": "Token not found"},
    },
)
def delete_canvas_token(
    request_fastapi: Request,
    token: str,
    session: Session = Depends(get_db_session),
) -> dict:
    """Revoke a canvas token so its URL stops resolving."""
    dao, _ = _owned_entry(session, token, request_fastapi.state.user_id)
    dao.delete_by_token(token)
    session.commit()
    return {"deleted": True, "token": token}


@admin_router.get(
    "/canvas/tokens/{token}",
    response_model=CanvasTokenResolutionResponse,
    responses={
        200: {"description": "Token resolved"},
        404: {"description": "Token not found"},
    },
)
def admin_resolve_canvas_token(
    token: str,
    session: Session = Depends(get_db_session),
) -> CanvasTokenResolutionResponse:
    """Resolve a token to its context path, owner identity and access state.

    Used by console to read a canvas from Unify contexts with the owner's API
    key. Resolution deliberately succeeds for a quarantined or draft canvas and
    reports the status: the caller needs to tell "no such canvas" apart from
    "exists but is not servable", and only the caller knows whether it is serving
    a viewer or the owner's own editor.
    """
    entry = CanvasTokenDAO(session).get_by_token(token)
    if not entry:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Token not found",
        )

    return CanvasTokenResolutionResponse(
        context_name=entry.context_name,
        user_id=entry.user_id,
        organization_id=entry.organization_id,
        project_id=entry.project_id,
        project_name=entry.project.name,
        visibility=entry.visibility,
        status=entry.status,
    )


# ===========================================================================
# Read plane
# ===========================================================================


def _bridge_daos(session: Session):
    """The DAO set every query needs, imported lazily to keep import time down."""
    from orchestra.db.dao.context_dao import ContextDAO
    from orchestra.db.dao.field_type_dao import FieldTypeDAO
    from orchestra.db.dao.organization_member_dao import OrganizationMemberDAO
    from orchestra.db.dao.project_dao import ProjectDAO

    org_member_dao = OrganizationMemberDAO(session)
    context_dao = ContextDAO(session)
    project_dao = ProjectDAO(session, org_member_dao, context_dao)
    field_type_dao = FieldTypeDAO(session)
    return project_dao, field_type_dao, context_dao


def _as_owner(entry) -> SimpleNamespace:
    """A request-shaped stand-in carrying the canvas owner's identity.

    Every query below runs as the owner, never as the viewer. The viewer's own
    permission to see the canvas at all was decided upstream in console; here the
    only identity that makes sense is the one whose data the bindings resolved
    against at author time.
    """
    return SimpleNamespace(
        state=SimpleNamespace(
            user_id=entry.user_id,
            organization_id=entry.organization_id,
        ),
    )


def _servable(session: Session, token: str):
    """Resolve a token that is allowed to serve data.

    Quarantine has to stop reads, not just the bundle. A canvas pulled for
    leaking data would otherwise keep answering queries for anyone whose frame
    was already open.
    """
    entry = CanvasTokenDAO(session).get_by_token(token)
    if not entry:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Token not found",
        )
    if entry.status != "published":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Canvas is {entry.status} and cannot serve data",
        )
    return entry


def _flatten(logs: list) -> list:
    """Merge stored and derived entries into plain rows for JS consumption."""
    return [
        {**log.get("entries", {}), **log.get("derived_entries", {})} for log in logs
    ]


def _fields(names) -> Optional[str]:
    """Join field names the way the log query expects.

    The separator is ``&``, and getting it wrong fails silently in two different
    directions: a comma-joined ``from_fields`` matches no field and returns **zero
    rows**, while a comma-joined ``exclude_fields`` excludes **nothing**. Neither
    raises, so both look like working code — hence one helper rather than a
    ``join`` at each call site.
    """
    return FIELD_SEPARATOR.join(names) if names else None


def _rows_from(
    *,
    entry,
    context: str,
    filter_expr: Optional[str],
    from_fields: Optional[str] = None,
    exclude_fields: Optional[str] = None,
    sorting: Optional[str] = None,
    limit: int,
    offset: int,
    session: Session,
) -> tuple[list, int]:
    """Run one row query as the canvas owner, through the standard log path."""
    from orchestra.web.api.log.utils.logging_utils import _format_logs, _get_logs_query

    project_dao, field_type_dao, context_dao = _bridge_daos(session)
    project = entry.project

    rows, total = _get_logs_query(
        request_fastapi=_as_owner(entry),
        project_name=project.name,
        context=context,
        filter=filter_expr,
        sorting=sorting,
        from_ids=None,
        exclude_ids=None,
        from_fields=from_fields,
        exclude_fields=exclude_fields,
        limit=limit,
        offset=offset,
        project_dao=project_dao,
        field_type_dao=field_type_dao,
        context_dao=context_dao,
        session=session,
        randomize=False,
    )

    context_rows = context_dao.filter(name=context, project_id=project.id)
    context_id = context_rows[0][0].id if context_rows else None
    field_types = field_type_dao.get_field_types(
        project.id,
        context_id=context_id,
        return_mutable=True,
    )
    logs_out, _ = _format_logs(
        rows=rows,
        field_types=field_types,
        value_limit=1000,
        column_context=None,
        field_order_map=field_type_dao.get_ordered_field_names(
            project.id,
            context_id=context_id,
        ),
        from_fields=from_fields,
        exclude_fields=exclude_fields,
    )
    return _flatten(logs_out), total


def _canvas_bindings(entry, token: str, session: Session) -> dict:
    """Load the stored, author-time-validated bindings for one canvas.

    Reading them from the record rather than accepting them from the caller is
    the entire security property of this endpoint.
    """
    # Only the two fields this needs. The record also holds the authored source
    # and the compiled bundle, which together run to hundreds of kilobytes, and a
    # data query must not pay for the bundle on every view.
    rows, _ = _rows_from(
        entry=entry,
        context=entry.context_name,
        filter_expr=f"token == '{token}'",
        from_fields=_fields(("token", "bindings_json")),
        sorting=None,
        limit=1,
        offset=0,
        session=session,
    )
    if not rows:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Canvas record not found",
        )

    payload = rows[0].get("bindings_json")
    if not payload:
        return {}

    try:
        declared = json.loads(payload)
    except (TypeError, ValueError):
        logger.warning("Canvas %s has unreadable bindings_json", token)
        return {}

    return {binding["alias"]: binding for binding in declared if binding.get("alias")}


def _as_rows(result: Any) -> list:
    """Normalise a reduction into the row list the frame is handed.

    Mirrors the same normalisation applied to author-time dry-run samples in
    unify, so a preview and a live view give the canvas the same shape.
    """
    if result is None:
        return []
    if isinstance(result, list):
        return result
    if isinstance(result, dict):
        return [result]
    return [{"value": result}]


def _run_binding(binding: dict, entry, session: Session) -> tuple[list, bool]:
    """Execute one stored binding as the owner and return its rows."""
    args = binding.get("args") or {}
    operation = args.get("operation")
    context = binding.get("resolved_context") or binding.get("table") or ""

    if operation == "filter":
        limit = int(args.get("limit") or 100)
        columns = args.get("columns")
        exclude = args.get("exclude_columns")
        order_by = args.get("order_by")
        sorting = None
        if order_by:
            sorting = (
                f"{order_by} desc" if args.get("descending") else f"{order_by} asc"
            )

        rows, _ = _rows_from(
            entry=entry,
            context=context,
            filter_expr=args.get("filter"),
            from_fields=_fields(columns),
            exclude_fields=_fields(exclude),
            sorting=sorting,
            limit=limit,
            offset=int(args.get("offset") or 0),
            session=session,
        )
        # Reaching the cap is reported rather than hidden: a canvas presenting a
        # truncated set as complete is worse than one that says it is partial.
        return rows, len(rows) >= limit

    if operation == "reduce":
        from orchestra.web.api.log.utils.metric_utils import (
            _compute_metric_for_key_grouped,
            compute_metric_for_key,
        )

        project_dao, field_type_dao, context_dao = _bridge_daos(session)
        project = entry.project
        context_rows = context_dao.filter(name=context, project_id=project.id)
        context_id = context_rows[0][0].id if context_rows else None
        field_types = field_type_dao.get_field_types(project.id, context_id=context_id)

        columns = args.get("columns")
        keys = [columns] if isinstance(columns, str) else list(columns or [])
        single = isinstance(columns, str)
        group_by = args.get("group_by")

        results = {}
        for key in keys:
            if group_by:
                results[key] = _compute_metric_for_key_grouped(
                    key=key,
                    metric=args.get("metric"),
                    project_obj=project,
                    context_id=context_id,
                    field_types=field_types,
                    group_by=group_by,
                    key_filter=args.get("filter"),
                    key_from_ids=None,
                    key_exclude_ids=None,
                    session=session,
                )
            else:
                results[key] = compute_metric_for_key(
                    key=key,
                    metric=args.get("metric"),
                    project_obj=project,
                    context_id=context_id,
                    field_types=field_types,
                    key_filter=args.get("filter"),
                    key_from_ids=None,
                    key_exclude_ids=None,
                    session=session,
                )

        return _as_rows(results[keys[0]] if single and keys else results), False

    if operation in ("join", "join_reduce"):
        from orchestra.web.api.log.utils.logging_utils import _join_query_internal

        project_dao, field_type_dao, context_dao = _bridge_daos(session)
        project = entry.project
        tables = binding.get("resolved_tables") or args.get("tables") or []
        if len(tables) != 2:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="A join binding must name exactly two tables",
            )

        reducing = operation == "join_reduce"
        columns = args.get("columns")
        result = _join_query_internal(
            project_id=project.id,
            project_name=project.name,
            pair_of_args=[
                {"context": tables[0], "filter": args.get("left_where")},
                {"context": tables[1], "filter": args.get("right_where")},
            ],
            join_expr=args.get("join_expr"),
            mode=args.get("mode") or "inner",
            columns=args.get("select"),
            filter=args.get("result_where"),
            sorting=None,
            limit=int(args.get("result_limit") or 100),
            offset=int(args.get("result_offset") or 0),
            group_by=args.get("group_by") if reducing else None,
            metric=args.get("metric") if reducing else None,
            key=columns if reducing else None,
            request_fastapi=_as_owner(entry),
            project_dao=project_dao,
            field_type_dao=field_type_dao,
            context_dao=context_dao,
            session=session,
        )

        if reducing:
            return _as_rows(result.get("result")), False
        return result.get("logs", []), False

    raise HTTPException(
        status_code=status.HTTP_400_BAD_REQUEST,
        detail=f"Binding operation {operation!r} is not supported",
    )


@admin_router.post(
    "/canvas/{token}/query",
    response_model=CanvasQueryResponse,
    responses={
        200: {"description": "Rows for the requested alias"},
        400: {"description": "The stored binding cannot be executed"},
        403: {"description": "Canvas is not published"},
        404: {"description": "Token, canvas record or alias not found"},
    },
)
def admin_canvas_query(
    body: CanvasQueryRequest,
    token: str = Path(..., pattern=TOKEN_PATTERN),
    session: Session = Depends(get_db_session),
) -> CanvasQueryResponse:
    """Execute one of a canvas's own declared bindings.

    The client names an alias; the server loads the canvas record, finds the
    binding that was validated and dry-run at author time, and executes it as the
    owner. No context path, filter expression or row limit is accepted from the
    caller, which is the difference between this and the dashboard tile bridge it
    replaces.

    An unknown alias is a 404 rather than an empty result: silently returning no
    rows would leave a canvas rendering an empty state for a typo, which looks
    exactly like real data being absent.
    """
    entry = _servable(session, token)
    bindings = _canvas_bindings(entry, token, session)

    binding = bindings.get(body.alias)
    if binding is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Canvas declares no binding named '{body.alias}'",
        )

    try:
        rows, truncated = _run_binding(binding, entry, session)
    except HTTPException:
        raise
    except ValueError as error:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(error),
        )
    except Exception as error:
        logger.exception("Canvas query failed for token %s alias %s", token, body.alias)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error executing binding: {error}",
        )

    return CanvasQueryResponse(alias=body.alias, rows=rows, truncated=truncated)


# ===========================================================================
# Write plane
# ===========================================================================

# Canvas contexts live at `{user}/{assistant}/Canvas/*`, which is the only place
# the owning assistant is recorded for a canvas. Derived rather than accepted from
# the caller: the assistant that runs the work has to be the one the canvas
# actually belongs to.
_CANVAS_CONTEXT = re.compile(r"(?:^|/)(?P<assistant>[^/]+)/Canvas/[A-Za-z]+$")


def _assistant_id(entry) -> int:
    """The assistant that owns this canvas, from its context path."""
    match = _CANVAS_CONTEXT.search(entry.context_name or "")
    if not match:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"Canvas context {entry.context_name!r} does not name an assistant; "
                "cannot dispatch an action."
            ),
        )
    raw = match.group("assistant")
    if not raw.isdigit():
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Canvas context {entry.context_name!r} has a non-numeric assistant.",
        )
    return int(raw)


def _sibling_context(entry, table: str) -> str:
    """A sibling `Canvas/*` context of the one the token points at."""
    return re.sub(r"Canvas/[A-Za-z]+$", f"Canvas/{table}", entry.context_name)


def _action_row(entry, token: str, action_name: str, session: Session) -> dict:
    """Load one declared action from the canvas's own action rows.

    The dispatch target comes from here and nowhere else. An action the canvas
    never declared is a 404 rather than a silent no-op, so an author whose control
    and declaration disagree finds out.
    """
    rows, _ = _rows_from(
        entry=entry,
        context=_sibling_context(entry, "Actions"),
        filter_expr=f"canvas_token == '{token}' and action_name == '{action_name}'",
        limit=1,
        offset=0,
        session=session,
    )
    if not rows:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Canvas declares no action named '{action_name}'",
        )
    return rows[0]


def _validate_args(action: dict, args: dict) -> None:
    """Re-validate arguments against the schema stored at author time.

    This is the control. The frame validates too, but it is untrusted, so that
    copy is a usability feature and this one decides. Bounds were made mandatory
    when the action was declared precisely so they are enforceable here.
    """
    payload = action.get("input_schema_json")
    if not payload:
        # An action declared without a schema takes no arguments; accepting some
        # anyway would let a caller smuggle a payload past a validation step that
        # does not exist.
        if args:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="This action takes no arguments.",
            )
        return

    try:
        schema = json.loads(payload)
    except (TypeError, ValueError):
        logger.error(
            "Canvas action %s has unreadable input_schema_json",
            action.get("action_name"),
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="This action's input schema is unreadable.",
        )

    import jsonschema

    try:
        jsonschema.validate(instance=args, schema=schema)
    except jsonschema.ValidationError as error:
        # The message names the offending field and bound, which is what lets the
        # canvas tell the viewer what to fix rather than that something failed.
        path = ".".join(str(part) for part in error.absolute_path) or "arguments"
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"{path}: {error.message}",
        )
    except jsonschema.SchemaError as error:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"This action's input schema is invalid: {error.message}",
        )


# How long identical arguments are treated as one intent. Long enough to absorb a
# double-click, a retry after a dropped response and a reconnect; short enough that
# sending the same reminder again later is a new run rather than a silent no-op.
DEDUP_WINDOW_SECONDS = 300


def _derive_run_key(token: str, action_name: str, args: dict) -> str:
    """Idempotency key for one logical run.

    Hashes the canvas, the action, the arguments and a coarse time bucket. Without
    the bucket, identical arguments would collapse *forever* — "send that reminder
    again tomorrow" would return yesterday's run and send nothing, which is a worse
    failure than the occasional missed deduplication when two clicks straddle a
    bucket boundary.

    Console can send its own key to make a retry after a dropped response land on
    the same run even across a boundary.
    """
    canonical = json.dumps(args, sort_keys=True, separators=(",", ":"))
    bucket = int(datetime.now(timezone.utc).timestamp()) // DEDUP_WINDOW_SECONDS
    digest = hashlib.sha256(
        f"{token}|{action_name}|{canonical}|{bucket}".encode(),
    ).hexdigest()
    return digest[:32]


def _existing_invocation(
    entry,
    token: str,
    run_key: str,
    session: Session,
) -> Optional[dict]:
    """A run already recorded under this idempotency key, if any."""
    rows, _ = _rows_from(
        entry=entry,
        context=_sibling_context(entry, "Invocations"),
        filter_expr=f"canvas_token == '{token}' and run_key == '{run_key}'",
        limit=1,
        offset=0,
        session=session,
    )
    return rows[0] if rows else None


def _recent_invocation_count(
    entry,
    token: str,
    action_name: str,
    user_id: str,
    session: Session,
) -> int:
    """How many times this viewer has run this action in the last hour."""
    since = (datetime.now(timezone.utc) - timedelta(hours=1)).isoformat()
    rows, total = _rows_from(
        entry=entry,
        context=_sibling_context(entry, "Invocations"),
        filter_expr=(
            f"canvas_token == '{token}' and action_name == '{action_name}' "
            f"and requested_by_user_id == '{user_id}' and created_at > '{since}'"
        ),
        limit=1000,
        offset=0,
        session=session,
    )
    return max(total, len(rows))


def _insert_invocation(entry, values: dict, *, session: Session) -> dict:
    """Persist one invocation row and read it back.

    Read back rather than returned from the insert because ``invocation_id`` is
    auto-counted by the context, so the value the caller needs is assigned during
    the write. Reading it back also confirms the row landed, which matters here:
    everything downstream — dispatch, polling, the audit trail — keys off this row
    existing.
    """
    from orchestra.db.dao.log_event_dao import LogEventDAO
    from orchestra.web.api.log.schema import CreateLogConfig
    from orchestra.web.api.log.utils.logging_utils import create_logs_internal

    project_dao, field_type_dao, context_dao = _bridge_daos(session)
    context_name = _sibling_context(entry, "Invocations")

    context_rows = context_dao.filter(name=context_name, project_id=entry.project_id)
    if not context_rows:
        # Provisioned by the assistant runtime, never invented here: a context
        # created on this path would lack the auto-counting and uniqueness the
        # invocation model depends on.
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Context '{context_name}' does not exist; the canvas cannot record actions.",
        )

    create_logs_internal(
        request=CreateLogConfig(
            project_name=entry.project.name,
            context=context_name,
            entries=values,
        ),
        project_id=entry.project_id,
        context_id=context_rows[0][0].id,
        project_dao=project_dao,
        field_type_dao=field_type_dao,
        log_event_dao=LogEventDAO(session),
        context_dao=context_dao,
        context_obj=context_rows[0][0],
    )
    session.commit()

    rows, _ = _rows_from(
        entry=entry,
        context=context_name,
        filter_expr=f"run_key == '{values['run_key']}'",
        limit=1,
        offset=0,
        session=session,
    )
    if not rows:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="The invocation was written but could not be read back.",
        )

    written = rows[0]
    if written.get("invocation_id") is None:
        # The context exists but was not provisioned with an auto-counted
        # `invocation_id`, so nothing downstream could address this run. Saying so
        # beats a KeyError surfacing as an opaque 500.
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"Context '{context_name}' has no auto-counted invocation_id; "
                "the canvas cannot record actions."
            ),
        )
    return written


async def _wake_assistant(entry, invocation_id: int, action_name: str) -> None:
    """Hand the invocation to the assistant that owns the canvas.

    One event, not three dispatch lanes. Orchestra cannot run a stored function —
    functions live in unify — so splitting `function`, `task` and `assistant`
    dispatch here would put two of the three in the wrong process and duplicate
    machinery the assistant already has. The invocation row is the durable request;
    this only says one exists, carrying an id and nothing else.

    A dispatch failure is logged rather than raised. The row is already written, so
    the run is recoverable by retry or by a sweep; failing the request after
    persisting it would tell the viewer nothing happened when something did.
    """
    from orchestra.web.api.tasks.views import ADAPTERS_URL, ADMIN_KEY, get_async_client

    if not ADAPTERS_URL:
        logger.warning(
            "UNITY_ADAPTERS_URL not set; canvas invocation %s recorded but not dispatched",
            invocation_id,
        )
        return

    try:
        client = get_async_client()
        response = await client.post(
            f"{ADAPTERS_URL}/unity/system-event",
            headers={
                "Authorization": f"Bearer {ADMIN_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "assistant_id": _assistant_id(entry),
                "event_type": "canvas_invocation",
                "message": f"Canvas action '{action_name}' was triggered by a viewer.",
                "extra_event_fields": {
                    "type": "canvas_invocation",
                    "canvas_token": entry.token,
                    "invocation_id": invocation_id,
                    "action_name": action_name,
                },
            },
            timeout=30,
        )
        if response.status_code != 200:
            logger.error(
                "Canvas invocation dispatch failed: %s %s",
                response.status_code,
                response.text[:300],
            )
    except Exception:
        logger.exception("Canvas invocation %s could not be dispatched", invocation_id)


def _invocation_response(
    row: dict,
    *,
    deduplicated: bool = False,
) -> CanvasInvocationResponse:
    """Shape one stored invocation row for the caller."""
    result = None
    if row.get("result_json"):
        try:
            parsed = json.loads(row["result_json"])
            result = parsed if isinstance(parsed, dict) else {"value": parsed}
        except (TypeError, ValueError):
            result = None

    # Not `or 0`: auto-counted ids are 0-based, so a real first row and a missing
    # field would coerce to the same value. `_insert_invocation` refuses a context
    # without the field, so by here it is present.
    raw_id = row.get("invocation_id")
    return CanvasInvocationResponse(
        invocation_id=int(raw_id) if raw_id is not None else -1,
        action_name=str(row.get("action_name") or ""),
        status=str(row.get("status") or "pending"),
        result=result,
        error=row.get("error"),
        run_key=str(row.get("run_key") or ""),
        deduplicated=deduplicated,
    )


@admin_router.get(
    "/canvas/{token}/actions",
    response_model=CanvasActionsResponse,
    responses={
        200: {"description": "Declared actions"},
        403: {"description": "Canvas is not published"},
        404: {"description": "Token not found"},
    },
)
def admin_canvas_actions(
    token: str = Path(..., pattern=TOKEN_PATTERN),
    session: Session = Depends(get_db_session),
) -> CanvasActionsResponse:
    """List what a canvas may invoke, without saying what any of it runs.

    Console passes these to the frame so it can render controls. Targets are
    filtered out here rather than in console, so no caller of this endpoint can
    leak them by forgetting to.
    """
    entry = _servable(session, token)

    rows, _ = _rows_from(
        entry=entry,
        context=_sibling_context(entry, "Actions"),
        filter_expr=f"canvas_token == '{token}'",
        limit=100,
        offset=0,
        session=session,
    )

    actions = []
    for row in rows:
        schema = None
        if row.get("input_schema_json"):
            try:
                schema = json.loads(row["input_schema_json"])
            except (TypeError, ValueError):
                schema = None
        actions.append(
            CanvasActionDescriptor(
                name=str(row.get("action_name") or ""),
                label=str(row.get("label") or ""),
                icon=row.get("icon"),
                input_schema=schema,
                # A destructive action always confirms, whatever else was
                # declared: the copy is optional, the pause is not.
                requires_confirmation=bool(row.get("destructive"))
                or bool(row.get("confirm")),
                destructive=bool(row.get("destructive")),
            ),
        )

    return CanvasActionsResponse(actions=actions)


@admin_router.post(
    "/canvas/{token}/action",
    response_model=CanvasInvocationResponse,
    responses={
        200: {"description": "Invocation recorded (or matched an existing run)"},
        400: {"description": "Arguments failed validation"},
        403: {"description": "Canvas is not published"},
        404: {"description": "Token or action not found"},
        429: {"description": "Rate limit exceeded"},
    },
)
async def admin_canvas_action(
    body: InvokeCanvasActionRequest,
    token: str = Path(..., pattern=TOKEN_PATTERN),
    session: Session = Depends(get_db_session),
) -> CanvasInvocationResponse:
    """Record and dispatch one run of a canvas's declared action.

    The order is deliberate: resolve the action, validate the arguments, check the
    rate limit, deduplicate, **persist**, and only then dispatch. Persisting before
    dispatching is what makes the run recoverable — a dispatch that fails leaves a
    row to retry, whereas dispatching first can run work no one recorded.
    """
    entry = _servable(session, token)
    action = _action_row(entry, token, body.action_name, session)

    _validate_args(action, body.args)

    user_id = body.requested_by_user_id or entry.user_id
    limit = int(action.get("max_invocations_per_hour") or 20)
    if (
        _recent_invocation_count(entry, token, body.action_name, user_id, session)
        >= limit
    ):
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail=f"This action is limited to {limit} runs an hour.",
        )

    run_key = body.run_key or _derive_run_key(token, body.action_name, body.args)

    existing = _existing_invocation(entry, token, run_key, session)
    if existing:
        # A double-click, a retry after a dropped response, or a reconnect. All
        # three are the same intent, and the run that already exists is the answer.
        return _invocation_response(existing, deduplicated=True)

    now = datetime.now(timezone.utc).isoformat()
    inserted = _insert_invocation(
        entry,
        {
            "canvas_token": token,
            "action_name": body.action_name,
            "args_json": json.dumps(body.args, separators=(",", ":")),
            "status": "pending",
            "run_key": run_key,
            "requested_by_user_id": user_id,
            "created_at": now,
        },
        session=session,
    )

    await _wake_assistant(entry, inserted["invocation_id"], body.action_name)

    return _invocation_response(inserted)


@admin_router.get(
    "/canvas/{token}/invocations/{invocation_id}",
    response_model=CanvasInvocationResponse,
    responses={
        200: {"description": "Invocation state"},
        403: {"description": "Canvas is not published"},
        404: {"description": "Token or invocation not found"},
    },
)
def admin_canvas_invocation(
    invocation_id: int,
    token: str = Path(..., pattern=TOKEN_PATTERN),
    session: Session = Depends(get_db_session),
) -> CanvasInvocationResponse:
    """Read one invocation's current state.

    The polling fallback for when the event stream is unavailable. Scoped to the
    canvas in the path so an invocation id from one canvas cannot be read through
    another.
    """
    entry = _servable(session, token)

    rows, _ = _rows_from(
        entry=entry,
        context=_sibling_context(entry, "Invocations"),
        filter_expr=f"canvas_token == '{token}' and invocation_id == {invocation_id}",
        limit=1,
        offset=0,
        session=session,
    )
    if not rows:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Invocation not found",
        )

    return _invocation_response(rows[0])
