import time
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class ChatCompletionRequest(BaseModel):
    """
    Request model for chat completion based language model.

    Attributes:
        model (str): The model identifier.
        messages (List[Dict[str]]): List of messages for completion.
        temperature (float): The temperature parameter for generating completions.
        stream (bool): Whether to stream the response.
    """

    # This allows extra arguments through.
    model_config = ConfigDict(extra="allow")

    # unified arguments
    messages: List[Dict[str, Any]] = Field(
        description="A list of messages comprising the conversation so far.",
        json_schema_extra={
            "example": [
                {
                    "role": "user",
                    "content": "Tell me a joke",
                },
            ],
        },
    )
    model: str = Field(
        description="The endpoint to use, in the format "
        "`{model}@{provider}`, based on any of the supported "
        "endpoints as per the list returned by `/v0/endpoints`",
        json_schema_extra={"example": "gpt-4o-mini@openai"},
    )
    max_tokens: Optional[int] = Field(
        None,
        description="The maximum number of tokens that can be generated in the "
        "chat completion.\n\nThe total length of input tokens and generated tokens is "
        "limited by the model's context length.",
        json_schema_extra={"example": 1024},
    )
    stop: Optional[Union[str, List[str]]] = Field(
        None,
        description="Up to 4 sequences where the API will stop generating "
        "further tokens.",
        json_schema_extra={"example": ["The End.", " is the answer."]},
    )
    stream: bool = Field(
        False,
        description="If set, partial message deltas will be sent. Tokens will "
        "be sent as data-only server-sent events as they become available, with the "
        "stream terminated by a `data: [DONE]` message.",
        json_schema_extra={"example": False},
    )
    temperature: float = Field(
        1.0,
        description="What sampling temperature to use, between 0 and 2. Higher "
        "values like 0.8 will make the output more random, while lower values like 0.2 "
        "will make it more focused and deterministic.\n\nGenerally recommended to "
        "alter this or `top_p`, but not both.",
        json_schema_extra={"example": 0.9},
    )

    # partially unified arguments
    frequency_penalty: Optional[float] = Field(
        None,
        description="Number between -2.0 and 2.0. Positive values penalize new "
        "tokens based on their existing frequency in the text so far, decreasing the "
        "model's likelihood to repeat the same line verbatim.",
        json_schema_extra={"example": 1.5},
    )
    logit_bias: Optional[Dict[str, float]] = Field(
        None,
        description="Modify the likelihood of specified tokens appearing in the "
        "completion.\n\nAccepts a JSON object that maps tokens (specified by their "
        "token ID in the tokenizer) to an associated bias value from -100 to 100. "
        "Mathematically, the bias is added to the logits generated by the model prior "
        "to sampling. The exact effect will vary per model, but values between -1 and "
        "1 should decrease or increase likelihood of selection; values like -100 or "
        "100 should result in a ban or exclusive selection of the relevant token.",
        json_schema_extra={"example": {0: 10, 1: -75, 2: 90}},
    )
    logprobs: Optional[bool] = Field(
        None,
        description="Whether to return log probabilities of the output tokens or "
        "not. If true, returns the log probabilities of each output token returned in "
        "the `content` of `message`.",
        json_schema_extra={"example": False},
    )
    top_logprobs: Optional[int] = Field(
        None,
        description="An integer between 0 and 20 specifying the number of most "
        "likely tokens to return at each token position, each with an associated log "
        "probability. `logprobs` must be set to `true` if this parameter is used.",
        json_schema_extra={"example": 15},
    )
    n: Optional[int] = Field(
        None,
        description="How many chat completion choices to generate for each input "
        "message. Note that you will be charged based on the number of generated "
        "tokens across all of the choices. Keep `n` as `1` to minimize costs.",
        json_schema_extra={"example": 15},
    )
    presence_penalty: Optional[float] = Field(
        None,
        description="Number between -2.0 and 2.0. Positive values penalize new "
        "tokens based on whether they appear in the text so far, increasing the "
        "model's likelihood to talk about new topics.",
        json_schema_extra={"example": -1.1},
    )
    response_format: Optional[Dict[str, Any]] = Field(
        None,
        description="An object specifying the format that the model must output."
        '\n\nSetting to `{ "type": "json_schema", "json_schema": {...} }` enables '
        "Structured Outputs which ensures the model will match your supplied JSON "
        'schema.\n\nSetting to `{ "type": "json_object" }` enables JSON mode, which '
        "ensures the message the model generates is valid JSON.\n\n**Important:** when "
        "using JSON mode, you **must** also instruct the model to produce JSON "
        "yourself via a system or user message. Without this, the model may generate "
        "an unending stream of whitespace until the generation reaches the token "
        'limit, resulting in a long-running and seemingly "stuck" request. Also note '
        'that the message content may be partially cut off if `finish_reason="length"`'
        ", which indicates the generation exceeded `max_tokens` or the conversation "
        "exceeded the max context length.",
        json_schema_extra={"example": '{ "type": "json_mode"}'},
    )
    seed: Optional[int] = Field(
        None,
        description="If specified, the system will make a best effort to sample "
        "deterministically, such that repeated requests with the same `seed` and "
        "parameters should return the same result. Determinism is not guaranteed, and "
        "you should refer to the `system_fingerprint` response parameter to monitor "
        "changes in the backend.",
        json_schema_extra={"example": 11},
    )
    stream_options: Optional[Dict[str, bool]] = Field(
        None,
        description="Options for streaming response. Only set this when you set "
        "`stream: true`.",
        json_schema_extra={"example": {"include_usage", True}},
    )
    top_p: Optional[float] = Field(
        None,
        description="An alternative to sampling with temperature, called nucleus "
        "sampling, where the model considers the results of the tokens with top_p "
        "probability mass. So 0.1 means only the tokens comprising the top 10% "
        "probability mass are considered.\n\nGenerally recommended to alter this or "
        "`temperature` but not both.",
        json_schema_extra={"example": 0.5},
    )
    tools: Optional[List[Any]] = Field(
        None,
        description="A list of tools the model may call. Currently, only "
        "functions are supported as a tool. Use this to provide a list of functions "
        "the model may generate JSON inputs for. A max of 128 functions are supported.",
        json_schema_extra={"example": None},
    )
    tool_choice: Optional[Any] = Field(
        None,
        description="Controls which (if any) tool is called by the model. `none` "
        "means the model will not call any tool and instead generates a message."
        "`auto` means the model can pick between generating a message or calling one "
        "or more tools. `required` means the model must call one or more tools. "
        'Specifying a particular tool via `{"type": "function", "function": {"name": '
        '"my_function"}}` forces the model to call that tool.'
        "\n\n`none` is the default when no tools are present. `auto` is the default if "
        "tools are present.",
        json_schema_extra={
            "example": '{"type": "function", "function": {"name": "my_function"}}',
        },
    )
    parallel_tool_calls: bool = Field(
        True,
        description="Whether to enable parallel function calling during tool " "use.",
        json_schema_extra={"example": True},
    )
    user: Optional[str] = Field(
        None,
        description="A unique identifier representing your end-user.",
        json_schema_extra={"example": "some_user"},
    )

    # platform arguments
    signature: Optional[str] = Field(
        None,
        description="A string used to represent where the request came from, for "
        "examples, did it come via the Python package, the NodeJS package, the chat "
        "interface etc. This should *not* be set by the user.",
        json_schema_extra={"example": "python"},
    )
    use_custom_keys: Optional[bool] = Field(
        None,
        description="Whether or not to use custom API keys with the specified "
        "provider, meaning that you will be using your own account with that provider "
        "in the backend.",
        json_schema_extra={"example": True},
    )
    tags: Optional[List[str]] = Field(
        None,
        description="Comma-separated list of tags to associate with the corresponding prompt.",
        json_schema_extra={"example": True},
    )


class ChatCompletionResponse(BaseModel):
    """
    Response model for chat completion based language model.

    Attributes:
        model (str): The model identifier.
        created (int): Timestamp indicating when the response was created.
        id (str): Identifier for the completion response.
        object (str): The type of object, defaults to "chat.completion".
        usage (dict): Usage statistics or additional information.
        choices (List[Dict]): List of completion choices.
    """

    model: str
    created: Optional[int] = None
    id: Optional[str] = None
    object: str = "chat.completion"
    usage: Dict[str, Any]
    choices: List[Dict[str, Any]]

    def __init__(self, **data):
        super().__init__(**data)
        if self.created is None:
            self.created = int(time.time())
        if self.id is None:
            self.id = "msg-id"


class RouterScoresResponse(BaseModel):
    scores: Dict[str, float]


class QueryMetricsRequest(BaseModel):
    secondary_user_id: Optional[str] = ""
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    models: Optional[str] = None
    providers: Optional[str] = None
    interval: Optional[str] = 300
