"""Added units of measurement to the metric.

Revision ID: 3bde72676640
Revises: 0642c18bdb15
Create Date: 2023-12-22 12:42:24.827875

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3bde72676640"
down_revision = "0642c18bdb15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metric", sa.Column("units", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metric", "units")
    # ### end Alembic commands ###
