"""Created Orchestra Models.

Revision ID: 2badd346d324
Revises: 2b7380507a71
Create Date: 2023-12-13 14:11:45.695948

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2badd346d324"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "metric",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "modality",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "provider",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recharge_type",
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("type"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recharge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.TIMESTAMP(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type"],
            ["recharge_type.type"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("modality", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["modality"],
            ["modality.name"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "model",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column("input_args_format", sa.Text(), nullable=False),
        sa.Column("output_format", sa.Text(), nullable=False),
        sa.Column("custom_fields", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["license"],
            ["license.name"],
        ),
        sa.ForeignKeyConstraint(
            ["task"],
            ["task.name"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "endpoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datapoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("measured_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("metric_name", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_name"],
            ["metric.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "query",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("at", sa.TIMESTAMP(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "dummy_model",
        "name",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dummy_model",
        "name",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.drop_table("query")
    op.drop_table("datapoint")
    op.drop_table("endpoint")
    op.drop_table("model")
    op.drop_table("task")
    op.drop_table("recharge")
    op.drop_table("user")
    op.drop_table("recharge_type")
    op.drop_table("provider")
    op.drop_table("modality")
    op.drop_table("metric")
    op.drop_table("license")
    # ### end Alembic commands ###
