"""Created Updated Orchestra Models.

Revision ID: 0642c18bdb15
Revises: 819cbf6e030b
Create Date: 2023-12-20 15:21:01.909822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0642c18bdb15"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "metric",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "modality",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "provider",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recharge_type",
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("type"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("credits", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recharge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.TIMESTAMP(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type"],
            ["recharge_type.type"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("modality", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["modality"],
            ["modality.name"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mdl_code", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("uploaded_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column("input_args_format", sa.Text(), nullable=False),
        sa.Column("output_format", sa.Text(), nullable=False),
        sa.Column("custom_fields", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["license"],
            ["license.name"],
        ),
        sa.ForeignKeyConstraint(
            ["task"],
            ["task.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "endpoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mdl_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mdl_id"],
            ["model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datapoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("measured_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("metric_name", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_name"],
            ["metric.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "query",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("at", sa.TIMESTAMP(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query")
    op.drop_table("datapoint")
    op.drop_table("endpoint")
    op.drop_table("model")
    op.drop_table("task")
    op.drop_table("recharge")
    op.drop_table("users")
    op.drop_table("recharge_type")
    op.drop_table("provider")
    op.drop_table("modality")
    op.drop_table("metric")
    op.drop_table("license")
    # ### end Alembic commands ###
