"""add prompt variations table

Revision ID: df1c21169c93
Revises: 76e875ab31c4
Create Date: 2024-09-09 10:23:16.000090

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df1c21169c93"
down_revision = "76e875ab31c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_prompt_variation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datum_id", sa.Integer(), nullable=True),
        sa.Column("prompt_overrides", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stored_prompt_variation_datum_id"),
        "stored_prompt_variation",
        ["datum_id"],
        unique=False,
    )
    op.add_column(
        "evaluation",
        sa.Column("prompt_variation_id", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_evaluation_prompt_variation_id"),
        "evaluation",
        ["prompt_variation_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "evaluation",
        "stored_prompt_variation",
        ["prompt_variation_id"],
        ["id"],
    )
    op.add_column(
        "stored_prompt_response",
        sa.Column("prompt_variation_id", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_stored_prompt_response_prompt_variation_id"),
        "stored_prompt_response",
        ["prompt_variation_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "stored_prompt_response",
        "stored_prompt_variation",
        ["prompt_variation_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stored_prompt_response", type_="foreignkey")
    op.drop_index(
        op.f("ix_stored_prompt_response_prompt_variation_id"),
        table_name="stored_prompt_response",
    )
    op.drop_column("stored_prompt_response", "prompt_variation_id")
    op.drop_constraint(None, "evaluation", type_="foreignkey")
    op.drop_index(op.f("ix_evaluation_prompt_variation_id"), table_name="evaluation")
    op.drop_column("evaluation", "prompt_variation_id")
    op.drop_index(
        op.f("ix_stored_prompt_variation_datum_id"),
        table_name="stored_prompt_variation",
    )
    op.drop_table("stored_prompt_variation")
    # ### end Alembic commands ###
