"""Added status_code column

Revision ID: 193e0a1d573f
Revises: 0e9eef357b46
Create Date: 2024-09-25 14:05:20.992902

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "193e0a1d573f"
down_revision = "0e9eef357b46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query", sa.Column("status_code", sa.Integer(), nullable=True))
    status_code = sa.table("query", sa.column("status_code"))
    op.execute(
        status_code.update().values(
            status_code=200,
        ),
    )
    op.alter_column("query", "status_code", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query", "status_code")
    # ### end Alembic commands ###
