"""remove old columns from models and providers

Revision ID: 9fee25400687
Revises: e226d1c25675
Create Date: 2024-07-30 13:19:33.184013

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fee25400687"
down_revision = "e226d1c25675"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("model_license_fkey", "model", type_="foreignkey")
    op.drop_constraint("model_user_id_fkey", "model", type_="foreignkey")
    op.drop_column("model", "user_id")
    op.drop_column("model", "license")
    op.drop_column("model", "description")
    op.drop_column("model", "is_private")
    op.drop_column("model", "custom_fields")
    op.drop_column("model", "output_format")
    op.drop_column("model", "input_args_format")
    op.drop_column("provider", "description")
    op.drop_table("license")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("name", name="license_pkey"),
    )
    op.add_column(
        "provider",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "model",
        sa.Column(
            "input_args_format",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "model",
        sa.Column(
            "output_format",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "model",
        sa.Column("custom_fields", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "model",
        sa.Column(
            "is_private",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "model",
        sa.Column(
            "description",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "model",
        sa.Column("license", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "model",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key("model_user_id_fkey", "model", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        "model_license_fkey",
        "model",
        "license",
        ["license"],
        ["name"],
    )
    # ### end Alembic commands ###
