"""Renamed column in Evaluator to judge_prompt

Revision ID: f1131ce1eefb
Revises: 6deeccc0faa5
Create Date: 2024-09-18 12:37:44.034906

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1131ce1eefb"
down_revision = "6deeccc0faa5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluator", sa.Column("judge_prompt", sa.String(), nullable=False))
    op.drop_column("evaluator", "system_prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluator",
        sa.Column("system_prompt", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("evaluator", "judge_prompt")

    # ### end Alembic commands ###
