"""Add uniqueness of (user_id, dataset)

Revision ID: 704ebc5192eb
Revises: 7f6b200eca18
Create Date: 2024-09-04 15:44:02.697818

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "704ebc5192eb"
down_revision = "7f6b200eca18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_userid_name", "dataset", ["user_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("uq_userid_name", "dataset", type_="unique")
    # ### end Alembic commands ###
