"""Add active column to model.

Revision ID: b86a107c9058
Revises: 3bde72676640
Create Date: 2024-01-18 04:06:03.610756

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b86a107c9058"
down_revision = "3bde72676640"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model",
        sa.Column("active", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model", "active")
    # ### end Alembic commands ###
