"""add tags to query table

Revision ID: 433a0d1fdae5
Revises: 69fda243ec6f
Create Date: 2024-08-29 16:09:54.881357

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "433a0d1fdae5"
down_revision = "69fda243ec6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "query_tag_association",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "query_id", "tag_id"),
    )
    op.create_index(
        op.f("ix_query_tag_association_query_id"),
        "query_tag_association",
        ["query_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_query_tag_association_tag_id"),
        "query_tag_association",
        ["tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_query_tag_association_user_id"),
        "query_tag_association",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_query_endpoint_id"), "query", ["endpoint_id"], unique=False
    )
    op.create_index(op.f("ix_query_user_id"), "query", ["user_id"], unique=False)
    op.create_index(
        "ix_user_endpoint", "query", ["user_id", "endpoint_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_endpoint", table_name="query")
    op.drop_index(op.f("ix_query_user_id"), table_name="query")
    op.drop_index(op.f("ix_query_endpoint_id"), table_name="query")
    op.drop_index(
        op.f("ix_query_tag_association_user_id"), table_name="query_tag_association"
    )
    op.drop_index(
        op.f("ix_query_tag_association_tag_id"), table_name="query_tag_association"
    )
    op.drop_index(
        op.f("ix_query_tag_association_query_id"), table_name="query_tag_association"
    )
    op.drop_table("query_tag_association")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
