"""add display name to providers

Revision ID: 7eee9929ac76
Revises: d7563195dea1
Create Date: 2024-04-16 09:51:05.520210

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7eee9929ac76"
down_revision = "d7563195dea1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider", sa.Column("display_name", sa.String()))
    op.execute("UPDATE provider SET display_name='placeholder'")
    op.alter_column("provider", "display_name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider", "display_name")
    # ### end Alembic commands ###
