"""add dataset, evaluator and evaluation tables

Revision ID: 7f6b200eca18
Revises: f389050df167
Create Date: 2024-09-04 01:42:02.276500

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f6b200eca18"
down_revision = "f389050df167"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dataset_user_id"), "dataset", ["user_id"], unique=False)
    op.create_table(
        "evaluator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("class_config", sa.String(), nullable=False),
        sa.Column("judge_models", sa.String(), nullable=False),
        sa.Column("client_side", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluator_user_id"),
        "evaluator",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "stored_prompt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("ref_answer", sa.String(), nullable=True),
        sa.Column("num_tokens", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stored_prompt_user_id"),
        "stored_prompt",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "dataset_prompt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.Column("datum_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_prompt_dataset_id"),
        "dataset_prompt",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_prompt_datum_id"),
        "dataset_prompt",
        ["datum_id"],
        unique=False,
    )
    op.create_table(
        "evaluation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datum_id", sa.Integer(), nullable=True),
        sa.Column("evaluator_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluator_id"],
            ["evaluator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_evaluator_id"),
        "evaluation",
        ["evaluator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_datum_id"),
        "evaluation",
        ["datum_id"],
        unique=False,
    )
    op.create_table(
        "stored_prompt_extra_field",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datum_id", sa.Integer(), nullable=True),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stored_prompt_extra_field_datum_id"),
        "stored_prompt_extra_field",
        ["datum_id"],
        unique=False,
    )
    op.create_table(
        "stored_prompt_response",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datum_id", sa.Integer(), nullable=True),
        sa.Column("endpoint_str", sa.String(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
        sa.Column("num_tokens", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stored_prompt_response_datum_id"),
        "stored_prompt_response",
        ["datum_id"],
        unique=False,
    )
    op.create_table(
        "judgement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("response_id", sa.Integer(), nullable=True),
        sa.Column("judge_endpoint_id", sa.Integer(), nullable=False),
        sa.Column("judgement", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["judge_endpoint_id"],
            ["endpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["stored_prompt_response.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_judgement_response_id"),
        "judgement",
        ["response_id"],
        unique=False,
    )
    op.drop_table("dataset_evaluation")
    op.drop_table("dataset_evaluation_task")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_evaluation_task",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="dataset_evaluation_task_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="dataset_evaluation_task_pkey"),
        sa.UniqueConstraint("user_id", "name", name="uq_dataset_eval_user_id"),
    )
    op.create_table(
        "dataset_evaluation",
        sa.Column("mdl_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("dataset_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("prompt", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("score", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("gt_score", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("input_tokens", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("output_tokens", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "mdl_name",
            "dataset_name",
            "prompt",
            name="dataset_evaluation_pkey",
        ),
    )
    op.drop_index(op.f("ix_judgement_response_id"), table_name="judgement")
    op.drop_table("judgement")
    op.drop_index(
        op.f("ix_stored_prompt_response_datum_id"),
        table_name="stored_prompt_response",
    )
    op.drop_table("stored_prompt_response")
    op.drop_index(
        op.f("ix_stored_prompt_extra_field_datum_id"),
        table_name="stored_prompt_extra_field",
    )
    op.drop_table("stored_prompt_extra_field")
    op.drop_index(op.f("ix_evaluation_datum_id"), table_name="evaluation")
    op.drop_index(op.f("ix_evaluation_evaluator_id"), table_name="evaluation")
    op.drop_table("evaluation")
    op.drop_index(op.f("ix_dataset_prompt_datum_id"), table_name="dataset_prompt")
    op.drop_index(op.f("ix_dataset_prompt_dataset_id"), table_name="dataset_prompt")
    op.drop_table("dataset_prompt")
    op.drop_index(op.f("ix_stored_prompt_user_id"), table_name="stored_prompt")
    op.drop_table("stored_prompt")
    op.drop_index(op.f("ix_evaluator_user_id"), table_name="evaluator")
    op.drop_table("evaluator")
    op.drop_index(op.f("ix_dataset_user_id"), table_name="dataset")
    op.drop_table("dataset")
    # ### end Alembic commands ###
