"""Update schema to support benchmarking.

Revision ID: 972724c84cb8
Revises: b86a107c9058
Create Date: 2024-01-19 13:47:28.332147

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "972724c84cb8"
down_revision = "b86a107c9058"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmark_regime",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "benchmark_region",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "benchmark_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("regime", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("input_seq_len", sa.Integer(), nullable=False),
        sa.Column("output_seq_len", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "datapoint",
        sa.Column("benchmark_run_id", sa.Integer(), nullable=False),
    )
    op.add_column("datapoint", sa.Column("tooltip", sa.String(), nullable=True))
    op.drop_constraint("datapoint_endpoint_id_fkey", "datapoint", type_="foreignkey")
    op.create_foreign_key(
        None,
        "datapoint",
        "benchmark_run",
        ["benchmark_run_id"],
        ["id"],
    )
    op.drop_column("datapoint", "endpoint_id")
    op.add_column("metric", sa.Column("display_name", sa.String(), nullable=False))
    op.add_column("metric", sa.Column("tooltip", sa.String(), nullable=True))
    op.add_column("metric", sa.Column("priority", sa.Integer(), nullable=False))
    op.add_column("metric", sa.Column("plottable", sa.Boolean(), nullable=False))
    op.drop_column("metric", "units")
    op.add_column(
        "model",
        sa.Column("is_private", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model", "is_private")
    op.add_column(
        "metric",
        sa.Column("units", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("metric", "plottable")
    op.drop_column("metric", "priority")
    op.drop_column("metric", "tooltip")
    op.drop_column("metric", "display_name")
    op.add_column(
        "datapoint",
        sa.Column("endpoint_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "datapoint_benchmark_run_id_fkey",
        "datapoint",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "datapoint_endpoint_id_fkey",
        "datapoint",
        "endpoint",
        ["endpoint_id"],
        ["id"],
    )
    op.drop_column("datapoint", "tooltip")
    op.drop_column("datapoint", "benchmark_run_id")
    op.drop_table("benchmark_run")
    op.drop_table("benchmark_region")
    op.drop_table("benchmark_regime")
    # ### end Alembic commands ###
