"""add judgement score

Revision ID: f91d17403410
Revises: d19661e28ed5
Create Date: 2024-09-25 16:38:20.270018

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f91d17403410"
down_revision = "d19661e28ed5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "judgement", sa.Column("judgement_score", sa.Numeric(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("judgement", "judgement_score")
    # ### end Alembic commands ###
