"""add user id column
Revision ID: a04165c801bf
Revises: 80b0d354a57f
Create Date: 2024-09-09 11:26:13.779648
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a04165c801bf"
down_revision = "80b0d354a57f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("default_prompt", sa.Column("user_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_default_prompt_user_id"),
        "default_prompt",
        ["user_id"],
        unique=False,
    )
    op.create_foreign_key(None, "default_prompt", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "default_prompt", type_="foreignkey")
    op.drop_index(op.f("ix_default_prompt_user_id"), table_name="default_prompt")
    op.drop_column("default_prompt", "user_id")
    # ### end Alembic commands ###
