"""more tables

Revision ID: 32ac8e4d544e
Revises: 13b3eeb47aa9
Create Date: 2024-09-27 11:49:18.070011

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "32ac8e4d544e"
down_revision = "13b3eeb47aa9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("owner_id"),
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("user_id", "name"),
    )
    op.create_table(
        "organization_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("auth_user", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("auth_user", sa.Column("job_title", sa.String(), nullable=True))
    op.add_column(
        "auth_user",
        sa.Column("tier", sa.String(), server_default="developer", nullable=False),
    )
    op.add_column(
        "auth_user",
        sa.Column(
            "queries_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    op.add_column(
        "auth_user",
        sa.Column(
            "evaluations_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_user", "evaluations_enabled")
    op.drop_column("auth_user", "queries_enabled")
    op.drop_column("auth_user", "tier")
    op.drop_column("auth_user", "job_title")
    op.drop_column("auth_user", "last_name")
    op.drop_table("organization_member")
    op.drop_table("api_key")
    op.drop_table("organization")
    # ### end Alembic commands ###
