"""add router string info to query

Revision ID: 42f6dd026824
Revises: a8875de1c51c
Create Date: 2024-06-13 12:36:09.433549

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42f6dd026824"
down_revision = "a8875de1c51c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query", sa.Column("router", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query", "router")
    # ### end Alembic commands ###
