"""empty message

Revision ID: 2e5aa4cdd7a4
Revises: 366cf88065b9
Create Date: 2024-04-01 11:45:14.013928

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e5aa4cdd7a4"
down_revision = "366cf88065b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(), nullable=True))

    op.add_column("users", sa.Column("autorecharge", sa.Boolean()))
    op.execute("UPDATE users SET autorecharge=False")
    op.alter_column("users", "autorecharge", nullable=False)

    op.add_column("users", sa.Column("autorecharge_threshold", sa.Numeric()))
    op.execute("UPDATE users SET autorecharge_threshold=-1")
    op.alter_column("users", "autorecharge_threshold", nullable=False)

    op.add_column("users", sa.Column("autorecharge_qty", sa.Numeric()))
    op.execute("UPDATE users SET autorecharge_qty=0")
    op.alter_column("users", "autorecharge_qty", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "autorecharge_qty")
    op.drop_column("users", "autorecharge_threshold")
    op.drop_column("users", "autorecharge")
    op.drop_column("users", "stripe_customer_id")
    # ### end Alembic commands ###
