"""add alias to custom endpoint

Revision ID: 1da512aae00c
Revises: 9fee25400687
Create Date: 2024-08-02 09:29:24.883521

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1da512aae00c"
down_revision = "9fee25400687"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("custom_endpoint", sa.Column("mdl_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_endpoint", "mdl_name")
    # ### end Alembic commands ###
