"""fix foreign keys

Revision ID: 4eeab25d75ef
Revises: 32ac8e4d544e
Create Date: 2024-09-29 23:56:43.460816

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4eeab25d75ef"
down_revision = "32ac8e4d544e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_session_session_token", table_name="session")
    op.drop_table("session")
    op.drop_constraint("account_user_id_fkey", "account", type_="foreignkey")
    op.create_foreign_key(
        None,
        "account",
        "auth_user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("api_key_user_id_fkey", "api_key", type_="foreignkey")
    op.create_foreign_key(
        None,
        "api_key",
        "auth_user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("organization_owner_id_fkey", "organization", type_="foreignkey")
    op.create_foreign_key(
        None,
        "organization",
        "auth_user",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "organization_member_user_id_fkey",
        "organization_member",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "organization_member",
        "auth_user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization_member", type_="foreignkey")
    op.create_foreign_key(
        "organization_member_user_id_fkey",
        "organization_member",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.create_foreign_key(
        "organization_owner_id_fkey",
        "organization",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "api_key", type_="foreignkey")
    op.create_foreign_key(
        "api_key_user_id_fkey",
        "api_key",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "account", type_="foreignkey")
    op.create_foreign_key(
        "account_user_id_fkey",
        "account",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "session",
        sa.Column("session_token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="session_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_token", name="session_pkey"),
    )
    op.create_index(
        "ix_session_session_token",
        "session",
        ["session_token"],
        unique=False,
    )
    # ### end Alembic commands ###
