"""add uniqueness constaints

Revision ID: dbdd6bcbac52
Revises: 0cb6b7a81b25
Create Date: 2024-09-12 15:22:03.639119

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "dbdd6bcbac52"
down_revision = "0cb6b7a81b25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_evaluation",
        "evaluation",
        ["datum_id", "prompt_variation_id", "evaluator_id", "endpoint_str"],
    )
    op.create_unique_constraint("uq_userid_evaluator", "evaluator", ["user_id", "name"])
    op.create_unique_constraint(
        "uq_judgement",
        "judgement",
        ["response_id", "judge_endpoint_str", "evaluator_id"],
    )
    op.create_unique_constraint(
        "uq_prompt_response",
        "stored_prompt_response",
        ["datum_id", "prompt_variation_id", "endpoint_str"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_prompt_response", "stored_prompt_response", type_="unique")
    op.drop_constraint("uq_judgement", "judgement", type_="unique")
    op.drop_constraint("uq_userid_evaluator", "evaluator", type_="unique")
    op.drop_constraint("uq_evaluation", "evaluation", type_="unique")
    # ### end Alembic commands ###
