"""Add endpoint_id foreign key constraint to benchmark_run table.

Revision ID: 2a556ac356fd
Revises: ed28afce7031
Create Date: 2024-01-24 09:45:07.672504

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a556ac356fd"
down_revision = "ed28afce7031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "benchmark_run", "endpoint", ["endpoint_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "benchmark_run_endpoint_id_fkey",
        "benchmark_run",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
