"""Add measured_at and units columns.

Revision ID: 991cb19cb9af
Revises: f7858bf46c92
Create Date: 2024-01-25 04:21:14.583595

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "991cb19cb9af"
down_revision = "f7858bf46c92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "benchmark_run",
        sa.Column("measured_at", sa.TIMESTAMP(), nullable=False),
    )
    op.add_column("metric", sa.Column("units", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metric", "units")
    op.drop_column("benchmark_run", "measured_at")
    # ### end Alembic commands ###
