"""empty message

Revision ID: 1cb1c01ac935
Revises: fd70de5e6d04
Create Date: 2024-04-25 12:00:28.847256

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1cb1c01ac935"
down_revision = "fd70de5e6d04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_evaluation_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(
        "uq_dataset_eval_user_id", "dataset_evaluation_task", ["user_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_dataset_eval_user_id", "dataset_evaluation_task")
    op.drop_table("dataset_evaluation_task")
    # ### end Alembic commands ###
