"""Added extra parser column for evaluators

Revision ID: e58264537de7
Revises: d62c3daf37b9
Create Date: 2024-10-03 08:27:34.972136

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e58264537de7"
down_revision = "d62c3daf37b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluator", sa.Column("extra_parser", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluator", "extra_parser")
    # ### end Alembic commands ###
