"""add dashboard view tables

Revision ID: 80402c775278
Revises: 24929ee65f80
Create Date: 2024-10-31 15:11:44.020715

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80402c775278"
down_revision = "24929ee65f80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_view",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("view", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dashboard_view_project_id"),
        "dashboard_view",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dashboard_view_project_id"), table_name="dashboard_view")
    op.drop_table("dashboard_view")
    # ### end Alembic commands ###
