"""Added description column for evaluators

Revision ID: 858ab05ffac1
Revises: e58264537de7
Create Date: 2024-10-03 22:02:23.466543

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "858ab05ffac1"
down_revision = "e58264537de7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluator", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluator", "description")
    # ### end Alembic commands ###
