"""extra_fields moved inside stored_prompt

Revision ID: 2513710a8732
Revises: d62c3daf37b9
Create Date: 2024-10-03 10:51:18.278465

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "2513710a8732"
down_revision = "d62c3daf37b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "stored_prompt",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            default=dict,
            nullable=False,
        ),
    )

    stored_prompt = table(
        "stored_prompt", column("id", sa.Integer), column("extra_fields", JSONB)
    )
    stored_prompt_extra_field = table(
        "stored_prompt_extra_field",
        column("prompt_id", sa.Integer),
        column("field", sa.String),
        column("value", sa.String),
    )

    # Perform the data migration
    connection = op.get_bind()
    results = connection.execute(
        sa.select(
            stored_prompt_extra_field.c.prompt_id,
            sa.func.json_object_agg(
                stored_prompt_extra_field.c.field, stored_prompt_extra_field.c.value
            ).label("extra_fields"),
        ).group_by(stored_prompt_extra_field.c.prompt_id)
    ).fetchall()

    for row in results:
        connection.execute(
            stored_prompt.update()
            .where(stored_prompt.c.id == row.prompt_id)
            .values(extra_fields=row.extra_fields)
        )

    op.drop_index(
        "ix_stored_prompt_extra_field_prompt_id", table_name="stored_prompt_extra_field"
    )
    op.drop_table("stored_prompt_extra_field")

    op.drop_index("uq_userid_prompt", table_name="stored_prompt")
    op.create_index(
        "uq_userid_prompt",
        "stored_prompt",
        [
            sa.text(
                "hash_record_extended(row(user_id, system_msg, messages, prompt_kwargs, extra_fields), 0)"
            )
        ],
        unique=True,
    )
    op.drop_column("stored_prompt", "ref_answer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stored_prompt",
        sa.Column("ref_answer", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index("uq_userid_prompt", table_name="stored_prompt")
    op.create_index(
        "uq_userid_prompt",
        "stored_prompt",
        [
            sa.text(
                "hash_record_extended(ROW(user_id, system_msg, messages, prompt_kwargs), 0::bigint)"
            )
        ],
        unique=True,
    )
    op.drop_column("stored_prompt", "extra_fields")

    op.create_table(
        "stored_prompt_extra_field",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("prompt_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("field", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["stored_prompt.id"],
            name="stored_prompt_extra_field_prompt_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="stored_prompt_extra_field_pkey"),
    )
    op.create_index(
        "ix_stored_prompt_extra_field_prompt_id",
        "stored_prompt_extra_field",
        ["prompt_id"],
        unique=False,
    )
    # ### end Alembic commands ###
