"""add uniqueness for datasetprompt & storedprompt

Revision ID: 6e2c51496458
Revises: 6deeccc0faa5
Create Date: 2024-09-17 18:02:07.909362

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "6e2c51496458"
down_revision = "6deeccc0faa5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
    DELETE FROM dataset_prompt
    WHERE id IN (
        SELECT id
        FROM (
            SELECT id,
                   ROW_NUMBER() OVER (
                       PARTITION BY dataset_id, prompt_id
                       ORDER BY id
                   ) AS row_num
            FROM dataset_prompt
        ) t
        WHERE t.row_num > 1
    )
    """
    )

    op.create_unique_constraint(
        "uq_dataset_prompt", "dataset_prompt", ["dataset_id", "prompt_id"]
    )

    op.execute(
        """
    DELETE FROM stored_prompt
    WHERE id IN (
        SELECT id
        FROM (
            SELECT id,
                   ROW_NUMBER() OVER (
                       PARTITION BY user_id, system_msg, messages, prompt_kwargs
                       ORDER BY id
                   ) AS row_num
            FROM stored_prompt
        ) t
        WHERE t.row_num > 1
    )
    """
    )

    op.create_unique_constraint(
        "uq_userid_prompt",
        "stored_prompt",
        ["user_id", "system_msg", "messages", "prompt_kwargs"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_userid_prompt", "stored_prompt", type_="unique")
    op.drop_constraint("uq_dataset_prompt", "dataset_prompt", type_="unique")
    # ### end Alembic commands ###
