"""add image column to new users

Revision ID: 27bd2ddbc55c
Revises: 6af82fe8fca6
Create Date: 2024-10-01 09:38:37.619804

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "27bd2ddbc55c"
down_revision = "6af82fe8fca6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_user", sa.Column("image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_user", "image")
    # ### end Alembic commands ###
