"""Tie benchmark_run to benchmark_region and benchmark_regime.

Revision ID: ed28afce7031
Revises: 972724c84cb8
Create Date: 2024-01-24 05:28:02.355911

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed28afce7031"
down_revision = "972724c84cb8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "benchmark_run",
        "benchmark_region",
        ["region"],
        ["name"],
    )
    op.create_foreign_key(
        None,
        "benchmark_run",
        "benchmark_regime",
        ["regime"],
        ["name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("benchmark_run_regime_fkey", "benchmark_run", type_="foreignkey")
    op.drop_constraint("benchmark_run_region_fkey", "benchmark_run", type_="foreignkey")
    # ### end Alembic commands ###
