"""add default prompt table
Revision ID: 80b0d354a57f
Revises: df1c21169c93
Create Date: 2024-09-09 10:57:29.522181
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80b0d354a57f"
down_revision = "df1c21169c93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_prompt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "stored_prompt_variation",
        sa.Column("default_prompt_id", sa.Integer(), nullable=False),
    )
    op.alter_column(
        "stored_prompt_variation",
        "datum_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_stored_prompt_variation_default_prompt_id"),
        "stored_prompt_variation",
        ["default_prompt_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "stored_prompt_variation",
        "default_prompt",
        ["default_prompt_id"],
        ["id"],
    )
    op.drop_column("stored_prompt_variation", "prompt_overrides")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stored_prompt_variation",
        sa.Column("prompt_overrides", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "stored_prompt_variation", type_="foreignkey")
    op.drop_index(
        op.f("ix_stored_prompt_variation_default_prompt_id"),
        table_name="stored_prompt_variation",
    )
    op.alter_column(
        "stored_prompt_variation",
        "datum_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("stored_prompt_variation", "default_prompt_id")
    op.drop_table("default_prompt")
    # ### end Alembic commands ###
