"""change log version to be integer

Revision ID: 24929ee65f80
Revises: ac41d77761f5
Create Date: 2024-10-30 14:05:53.632322

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "24929ee65f80"
down_revision = "ac41d77761f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log",
        "version",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log",
        "version",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
