"""Renames prompt_id to datum_id across all tables

Revision ID: c32617ea1bde
Revises: 858ab05ffac1
Create Date: 2024-10-07 17:27:54.719555

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c32617ea1bde"
down_revision = "858ab05ffac1"
branch_labels = None
depends_on = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8R413
    op.drop_constraint(
        "stored_prompt_variation_prompt_id_fkey",
        "stored_prompt_variation",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_stored_prompt_variation_prompt_id",
        table_name="stored_prompt_variation",
    )
    op.alter_column("stored_prompt_variation", "prompt_id", new_column_name="datum_id")
    op.create_foreign_key(
        None,
        "stored_prompt_variation",
        "stored_prompt",
        ["datum_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_stored_prompt_variation_datum_id"),
        "stored_prompt_variation",
        ["datum_id"],
        unique=False,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8R413
    op.drop_constraint(
        "stored_prompt_response_prompt_id_fkey",
        "stored_prompt_response",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_stored_prompt_response_prompt_id",
        table_name="stored_prompt_response",
    )
    op.alter_column("stored_prompt_response", "prompt_id", new_column_name="datum_id")
    op.create_foreign_key(
        None,
        "stored_prompt_response",
        "stored_prompt",
        ["datum_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_stored_prompt_response_datum_id"),
        "stored_prompt_response",
        ["datum_id"],
        unique=False,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8R444
    op.drop_constraint("uq_prompt_response", "stored_prompt_response", type_="unique")
    op.create_unique_constraint(
        "uq_prompt_response",
        "stored_prompt_response",
        ["datum_id", "prompt_variation_id", "endpoint_str"],
        postgresql_nulls_not_distinct=True,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8R482
    op.drop_constraint(
        "dataset_prompt_prompt_id_fkey",
        "dataset_prompt",
        type_="foreignkey",
    )
    op.drop_index("ix_dataset_prompt_prompt_id", table_name="dataset_prompt")
    op.alter_column("dataset_prompt", "prompt_id", new_column_name="datum_id")
    op.create_foreign_key(None, "dataset_prompt", "stored_prompt", ["datum_id"], ["id"])
    op.create_index(
        op.f("ix_dataset_prompt_datum_id"),
        "dataset_prompt",
        ["datum_id"],
        unique=False,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8R486
    op.drop_constraint("uq_dataset_prompt", "dataset_prompt", type_="unique")
    op.create_unique_constraint(
        "uq_dataset_prompt",
        "dataset_prompt",
        ["dataset_id", "datum_id"],
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8R525
    op.drop_constraint("evaluation_prompt_id_fkey", "evaluation", type_="foreignkey")
    op.drop_index("ix_evaluation_prompt_id", table_name="evaluation")
    op.alter_column("evaluation", "prompt_id", new_column_name="datum_id")
    op.create_foreign_key(None, "evaluation", "stored_prompt", ["datum_id"], ["id"])
    op.create_index(
        op.f("ix_evaluation_datum_id"),
        "evaluation",
        ["datum_id"],
        unique=False,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8R536
    op.drop_constraint("uq_evaluation", "evaluation", type_="unique")
    op.create_unique_constraint(
        "uq_evaluation",
        "evaluation",
        ["datum_id", "prompt_variation_id", "evaluator_id", "endpoint_str"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8L413
    op.drop_constraint(
        "stored_prompt_variation_datum_id_fkey",
        "stored_prompt_variation",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_stored_prompt_variation_datum_id"),
        table_name="stored_prompt_variation",
    )
    op.alter_column("stored_prompt_variation", "datum_id", new_column_name="prompt_id")
    op.create_foreign_key(
        "stored_prompt_variation_prompt_id_fkey",
        "stored_prompt_variation",
        "stored_prompt",
        ["prompt_id"],
        ["id"],
    )
    op.create_index(
        "ix_stored_prompt_variation_prompt_id",
        "stored_prompt_variation",
        ["prompt_id"],
        unique=False,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8L433
    op.drop_constraint(
        "stored_prompt_response_datum_id_fkey",
        "stored_prompt_response",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_stored_prompt_response_datum_id"),
        table_name="stored_prompt_response",
    )
    op.alter_column("stored_prompt_response", "datum_id", new_column_name="prompt_id")
    op.create_foreign_key(
        "stored_prompt_response_prompt_id_fkey",
        "stored_prompt_response",
        "stored_prompt",
        ["prompt_id"],
        ["id"],
    )
    op.create_index(
        "ix_stored_prompt_response_prompt_id",
        "stored_prompt_response",
        ["prompt_id"],
        unique=False,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8L444
    op.drop_constraint("uq_prompt_response", "stored_prompt_response", type_="unique")
    op.create_unique_constraint(
        "uq_prompt_response",
        "stored_prompt_response",
        ["prompt_id", "prompt_variation_id", "endpoint_str"],
        postgresql_nulls_not_distinct=True,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8L482
    op.drop_constraint(
        "dataset_prompt_datum_id_fkey",
        "dataset_prompt",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_dataset_prompt_datum_id"), table_name="dataset_prompt")
    op.alter_column("dataset_prompt", "datum_id", new_column_name="prompt_id")
    op.create_foreign_key(
        "dataset_prompt_prompt_id_fkey",
        "dataset_prompt",
        "stored_prompt",
        ["prompt_id"],
        ["id"],
    )
    op.create_index(
        "ix_dataset_prompt_prompt_id",
        "dataset_prompt",
        ["prompt_id"],
        unique=False,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8L486
    op.drop_constraint("uq_dataset_prompt", "dataset_prompt", type_="unique")
    op.create_unique_constraint(
        "uq_dataset_prompt",
        "dataset_prompt",
        ["dataset_id", "prompt_id"],
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8L525
    op.drop_constraint("evaluation_datum_id_fkey", "evaluation", type_="foreignkey")
    op.drop_index(op.f("ix_evaluation_datum_id"), table_name="evaluation")
    op.alter_column("evaluation", "datum_id", new_column_name="prompt_id")
    op.create_foreign_key(
        "evaluation_prompt_id_fkey",
        "evaluation",
        "stored_prompt",
        ["prompt_id"],
        ["id"],
    )
    op.create_index(
        "ix_evaluation_prompt_id",
        "evaluation",
        ["prompt_id"],
        unique=False,
    )

    # https://github.com/unifyai/orchestra/commit/d5ac407240d723743a3125c6c775e00719043c64#diff-6dbb7891ac79c19a90a5fb7960bd2d22570dfa760d85c31996042b6e4782b4d8L536
    op.drop_constraint("uq_evaluation", "evaluation", type_="unique")
    op.create_unique_constraint(
        "uq_evaluation",
        "evaluation",
        ["prompt_id", "prompt_variation_id", "evaluator_id", "endpoint_str"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###
