"""Add seq_len to benchmark_run.

Revision ID: f7858bf46c92
Revises: 2a556ac356fd
Create Date: 2024-01-24 10:30:31.329750

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f7858bf46c92"
down_revision = "2a556ac356fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmark_seq_len",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.add_column("benchmark_run", sa.Column("seq_len", sa.String(), nullable=False))
    op.create_foreign_key(
        None,
        "benchmark_run",
        "benchmark_seq_len",
        ["seq_len"],
        ["name"],
    )
    op.drop_column("benchmark_run", "input_seq_len")
    op.drop_column("benchmark_run", "output_seq_len")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "benchmark_run",
        sa.Column("output_seq_len", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "benchmark_run",
        sa.Column("input_seq_len", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "benchmark_run_seq_len_fkey",
        "benchmark_run",
        type_="foreignkey",
    )
    op.drop_column("benchmark_run", "seq_len")
    op.drop_table("benchmark_seq_len")
    # ### end Alembic commands ###
