"""add active to endpoint

Revision ID: 69fda243ec6f
Revises: 1da512aae00c
Create Date: 2024-08-20 14:23:19.901943

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "69fda243ec6f"
down_revision = "1da512aae00c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "endpoint",
        sa.Column("active", sa.Boolean()),
    )
    op.execute("UPDATE endpoint SET active='f'")
    op.alter_column("endpoint", "active", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "active")
    # ### end Alembic commands ###
