"""delete old tables

Revision ID: ac41d77761f5
Revises: d0ebdc45de67
Create Date: 2024-10-23 11:13:00.702055

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ac41d77761f5"
down_revision = "d0ebdc45de67"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("router_evaluator_id_fkey", "router", type_="foreignkey")
    op.drop_column("router", "evaluator_id")
    op.drop_index("ix_judgement_response_id", table_name="judgement")
    op.drop_index("ix_evaluator_user_id", table_name="evaluator")
    op.drop_index("ix_stored_prompt_system_msg", table_name="stored_prompt")
    op.drop_index("ix_stored_prompt_user_id", table_name="stored_prompt")
    op.drop_index("uq_userid_prompt", table_name="stored_prompt")
    op.drop_index(
        "ix_stored_prompt_response_datum_id",
        table_name="stored_prompt_response",
    )
    op.drop_index(
        "ix_stored_prompt_response_prompt_variation_id",
        table_name="stored_prompt_response",
    )
    op.drop_index("ix_dataset_prompt_dataset_id", table_name="dataset_prompt")
    op.drop_index("ix_dataset_prompt_datum_id", table_name="dataset_prompt")
    op.drop_index("ix_evaluation_datum_id", table_name="evaluation")
    op.drop_index("ix_evaluation_evaluator_id", table_name="evaluation")
    op.drop_index("ix_evaluation_prompt_variation_id", table_name="evaluation")
    op.drop_index(
        "ix_stored_prompt_variation_datum_id",
        table_name="stored_prompt_variation",
    )
    op.drop_index(
        "ix_stored_prompt_variation_default_prompt_id",
        table_name="stored_prompt_variation",
    )
    op.drop_index("ix_default_prompt_user_id", table_name="default_prompt")

    op.drop_table("evaluation")
    op.drop_table("judgement")
    op.drop_table("stored_prompt_response")
    op.drop_table("stored_prompt_variation")
    op.drop_table("default_prompt")
    op.drop_table("evaluator")
    op.drop_table("dataset_prompt")
    op.drop_table("stored_prompt")
    op.drop_table("query_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_prompt",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('stored_prompt_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("num_tokens", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("system_msg", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("messages", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("prompt_kwargs", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="stored_prompt_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="stored_prompt_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "dataset_prompt",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("datum_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
            name="dataset_prompt_dataset_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
            name="dataset_prompt_datum_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="dataset_prompt_pkey"),
        sa.UniqueConstraint("dataset_id", "datum_id", name="uq_dataset_prompt"),
    )
    op.create_table(
        "default_prompt",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('default_prompt_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("prompt", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="default_prompt_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="default_prompt_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "stored_prompt_variation",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('stored_prompt_variation_id_seq'::regclass)",
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("datum_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "default_prompt_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
            name="stored_prompt_variation_datum_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["default_prompt_id"],
            ["default_prompt.id"],
            name="stored_prompt_variation_default_prompt_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="stored_prompt_variation_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "stored_prompt_response",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('stored_prompt_response_id_seq'::regclass)",
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("datum_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("endpoint_str", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("response", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("num_tokens", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "prompt_variation_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
            name="stored_prompt_response_datum_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_variation_id"],
            ["stored_prompt_variation.id"],
            name="stored_prompt_response_prompt_variation_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="stored_prompt_response_pkey"),
        sa.UniqueConstraint(
            "datum_id",
            "prompt_variation_id",
            "endpoint_str",
            name="uq_prompt_response",
            postgresql_nulls_not_distinct=True,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "evaluator",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("class_config", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("judge_models", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_side", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("judge_prompt", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "prompt_parser",
            sa.VARCHAR(),
            server_default=sa.text(
                "'{\"user_message\": \"[''messages''][-1][''content'']\"}'::character varying",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "response_parser",
            sa.VARCHAR(),
            server_default=sa.text(
                "'{\"assistant_message\": \"[''message''][''content'']\"}'::character varying",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="evaluator_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="evaluator_pkey"),
        sa.UniqueConstraint("user_id", "name", name="uq_userid_evaluator"),
    )
    op.create_table(
        "judgement",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("response_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("judgement", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "judge_endpoint_str",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("evaluator_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("judgement_score", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluator_id"],
            ["evaluator.id"],
            name="judgement_evaluator_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["stored_prompt_response.id"],
            name="judgement_response_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="judgement_pkey"),
        sa.UniqueConstraint(
            "response_id",
            "judge_endpoint_str",
            "evaluator_id",
            name="uq_judgement",
        ),
    )
    op.create_table(
        "evaluation",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("datum_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("evaluator_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("score", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column(
            "prompt_variation_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("endpoint_str", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["datum_id"],
            ["stored_prompt.id"],
            name="evaluation_datum_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["evaluator_id"],
            ["evaluator.id"],
            name="evaluation_evaluator_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_variation_id"],
            ["stored_prompt_variation.id"],
            name="evaluation_prompt_variation_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="evaluation_pkey"),
        sa.UniqueConstraint(
            "datum_id",
            "prompt_variation_id",
            "evaluator_id",
            "endpoint_str",
            name="uq_evaluation",
            postgresql_nulls_not_distinct=True,
        ),
    )

    op.create_index(
        "ix_default_prompt_user_id",
        "default_prompt",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_stored_prompt_variation_default_prompt_id",
        "stored_prompt_variation",
        ["default_prompt_id"],
        unique=False,
    )
    op.create_index(
        "ix_stored_prompt_variation_datum_id",
        "stored_prompt_variation",
        ["datum_id"],
        unique=False,
    )
    op.create_index(
        "ix_evaluation_prompt_variation_id",
        "evaluation",
        ["prompt_variation_id"],
        unique=False,
    )
    op.create_index(
        "ix_evaluation_evaluator_id",
        "evaluation",
        ["evaluator_id"],
        unique=False,
    )
    op.create_index("ix_evaluation_datum_id", "evaluation", ["datum_id"], unique=False)
    op.create_index(
        "ix_dataset_prompt_datum_id",
        "dataset_prompt",
        ["datum_id"],
        unique=False,
    )
    op.create_index(
        "ix_dataset_prompt_dataset_id",
        "dataset_prompt",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        "ix_stored_prompt_response_prompt_variation_id",
        "stored_prompt_response",
        ["prompt_variation_id"],
        unique=False,
    )
    op.create_index(
        "ix_stored_prompt_response_datum_id",
        "stored_prompt_response",
        ["datum_id"],
        unique=False,
    )
    op.create_index(
        "uq_userid_prompt",
        "stored_prompt",
        [
            sa.text(
                "hash_record_extended(ROW(user_id, system_msg, messages, prompt_kwargs), 0::bigint)",
            ),
        ],
        unique=True,
    )
    op.create_index(
        "ix_stored_prompt_user_id",
        "stored_prompt",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_stored_prompt_system_msg",
        "stored_prompt",
        ["system_msg"],
        unique=False,
    )
    op.create_table(
        "query_old",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("endpoint_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("credits", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("prompt", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("signature", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("used_router", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("router", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoint.id"],
            name="query_endpoint_id_fkey",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="query_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="query_pkey"),
    )
    op.create_index(
        "ix_judgement_response_id",
        "judgement",
        ["response_id"],
        unique=False,
    )
    op.create_index("ix_evaluator_user_id", "evaluator", ["user_id"], unique=False)
    op.add_column(
        "router",
        sa.Column("evaluator_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "router_evaluator_id_fkey",
        "router",
        "evaluator",
        ["evaluator_id"],
        ["id"],
    )
    # ### end Alembic commands ###
