"""Made naming for inter_token_latency and time_to_first_token more explicit

Revision ID: f3fbdcf9c215
Revises: e0f4abae5129
Create Date: 2024-10-13 23:08:52.081304

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f3fbdcf9c215"
down_revision = "e0f4abae5129"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "latest_benchmark",
        "ttft",
        new_column_name="time_to_first_token",
    )
    op.alter_column(
        "latest_benchmark",
        "itl",
        new_column_name="inter_token_latency",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "latest_benchmark",
        "time_to_first_token",
        new_column_name="ttft",
    )
    op.alter_column(
        "latest_benchmark",
        "inter_token_latency",
        new_column_name="itl",
    )
    # ### end Alembic commands ###
