"""add prompt to query table

Revision ID: d7563195dea1
Revises: 2e5aa4cdd7a4
Create Date: 2024-04-08 05:58:48.475991

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d7563195dea1"
down_revision = "2e5aa4cdd7a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query", sa.Column("prompt", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query", "prompt")
    # ### end Alembic commands ###
