"""Add uniqueness to prompts

Revision ID: 7693e2fac6fe
Revises: 6deeccc0faa5
Create Date: 2024-09-18 15:40:55.373145

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7693e2fac6fe"
down_revision = "6deeccc0faa5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
    DELETE FROM dataset_prompt
    WHERE id IN (
        SELECT id
        FROM (
            SELECT id,
                   ROW_NUMBER() OVER (
                       PARTITION BY dataset_id, prompt_id
                       ORDER BY id
                   ) AS row_num
            FROM dataset_prompt
        ) t
        WHERE t.row_num > 1
    )
    """
    )
    op.create_unique_constraint(
        "uq_dataset_prompt", "dataset_prompt", ["dataset_id", "prompt_id"]
    )
    op.execute(
        """
    DELETE FROM stored_prompt
    WHERE id IN (
        SELECT id
        FROM (
            SELECT id,
                   ROW_NUMBER() OVER (
                       PARTITION BY user_id, system_msg, messages, prompt_kwargs
                       ORDER BY id
                   ) AS row_num
            FROM stored_prompt
        ) t
        WHERE t.row_num > 1
    )
    """
    )

    op.create_index(
        "uq_userid_prompt",
        "stored_prompt",
        [
            sa.text(
                "hash_record_extended(row(user_id, system_msg, messages, prompt_kwargs), 0)"
            )
        ],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_userid_prompt", table_name="stored_prompt")
    op.drop_constraint("uq_dataset_prompt", "dataset_prompt", type_="unique")
     ### end Alembic commands ###
