"""add provider_type

Revision ID: 13b3eeb47aa9
Revises: d0df606a3bcf
Create Date: 2024-09-19 16:51:19.992184

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13b3eeb47aa9"
down_revision = "d0df606a3bcf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("provider_type", sa.String(), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "provider_type")
