"""empty message

Revision ID: 7abdedfadc78
Revises: 42f6dd026824
Create Date: 2024-06-19 11:42:34.912129

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7abdedfadc78"
down_revision = "42f6dd026824"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_router",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("router_name", sa.String(), nullable=False),
        sa.Column("router_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_router")
    # ### end Alembic commands ###
