""" create latest_benchmark table

Revision ID: e226d1c25675
Revises: 70b602194a76
Create Date: 2024-07-17 14:26:30.422606

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e226d1c25675"
down_revision = "70b602194a76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "latest_benchmark",
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("regime", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("seq_len", sa.String(), nullable=False),
        sa.Column("input_cost", sa.Numeric(), nullable=True),
        sa.Column("output_cost", sa.Numeric(), nullable=True),
        sa.Column("ttft", sa.Numeric(), nullable=True),
        sa.Column("itl", sa.Numeric(), nullable=True),
        sa.Column("measured_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoint.id"],
        ),
        sa.PrimaryKeyConstraint("endpoint_id", "regime", "region", "seq_len"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("latest_benchmark")
    # ### end Alembic commands ###
