"""add router tables

Revision ID: d62c3daf37b9
Revises: 27bd2ddbc55c
Create Date: 2024-10-01 16:39:32.957834

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d62c3daf37b9"
down_revision = "27bd2ddbc55c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "router",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("endpoints", sa.String(), nullable=False),
        sa.Column("evaluator_id", sa.Integer(), nullable=False),
        sa.Column("trained", sa.Boolean(), nullable=False),
        sa.Column("gcp_router_id", sa.String(), nullable=True),
        sa.Column("deployed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluator_id"],
            ["evaluator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_router_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("router")
    # ### end Alembic commands ###
