"""empty message

Revision ID: f45672bc228b
Revises: 1da512aae00c
Create Date: 2024-08-20 13:01:21.213180

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f45672bc228b"
down_revision = "1da512aae00c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_endpoint_benchmark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("custom_endpoint_id", sa.Integer(), nullable=False),
        sa.Column("metric_name", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("measured_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["custom_endpoint_id"],
            ["custom_endpoint.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("userstemp")
    op.drop_constraint(
        "uq_dataset_eval_user_id",
        "dataset_evaluation_task",
        type_="unique",
    )
    op.add_column(
        "endpoint",
        sa.Column("active", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "active")
    op.create_unique_constraint(
        "uq_dataset_eval_user_id",
        "dataset_evaluation_task",
        ["user_id", "name"],
    )
    op.create_table(
        "userstemp",
        sa.Column("id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "credits",
            sa.NUMERIC(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "credits2",
            sa.NUMERIC(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "credits3",
            sa.NUMERIC(),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("custom_endpoint_benchmark")
    # ### end Alembic commands ###
