"""Renamed column in Evaluator to judge_prompt

Revision ID: f1131ce1eefb
Revises: 6deeccc0faa5
Create Date: 2024-09-18 12:37:44.034906

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1131ce1eefb"
down_revision = "7693e2fac6fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluator", sa.Column("judge_prompt", sa.String(), nullable=True))
    op.drop_column("evaluator", "system_prompt")
    judge_prompt = sa.table("evaluator", sa.column("judge_prompt"))
    op.execute(
        judge_prompt.update().values(
            judge_prompt='{"messages":[{"content":"[System]\\nPlease act as an impartial judge and evaluate the quality of the response provided by an assistant to the user question displayed below.\\nYour job is to evaluate how good the assistant\'s answer is.\\nYour evaluation should consider correctness and helpfulness. Identify any mistakes.\\n\\nBe as objective as possible.","role":"system"},{"content":"\\n{class_config}\\n\\n[start of user question]\\n{user_prompt}\\n[end of user quesstion]\\n\\n[start of assistant answer]\\n{response}\\n[end of assistant answer]","role":"user"}],"frequency_penalty":null,"logit_bias":null,"logprobs":null,"top_logprobs":null,"max_tokens":1024,"n":null,"presence_penalty":null,"response_format":null,"seed":null,"stop":null,"temperature":1.0,"top_p":null,"tools":null,"tool_choice":null,"parallel_tool_calls":null,"extra_headers":null,"extra_query":null,"extra_body":null}',
        ),
    )
    op.alter_column("evaluator", "judge_prompt", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # probs make it nullable to avoid downgrading errors
    op.add_column(
        "evaluator",
        sa.Column("system_prompt", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("evaluator", "judge_prompt")

    # ### end Alembic commands ###
