"""uniqueness with nulls

Revision ID: 2ea882c8ddfe
Revises: 193e0a1d573f
Create Date: 2024-09-27 09:30:00.367120

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ea882c8ddfe"
down_revision = "193e0a1d573f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_evaluation", "evaluation", type_="unique")
    op.create_unique_constraint(
        "uq_evaluation",
        "evaluation",
        ["prompt_id", "prompt_variation_id", "evaluator_id", "endpoint_str"],
        postgresql_nulls_not_distinct=True,
    )
    op.drop_constraint("uq_prompt_response", "stored_prompt_response", type_="unique")
    op.create_unique_constraint(
        "uq_prompt_response",
        "stored_prompt_response",
        ["prompt_id", "prompt_variation_id", "endpoint_str"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_prompt_response", "stored_prompt_response", type_="unique")
    op.create_unique_constraint(
        "uq_prompt_response",
        "stored_prompt_response",
        ["prompt_id", "prompt_variation_id", "endpoint_str"],
    )
    op.drop_constraint("uq_evaluation", "evaluation", type_="unique")
    op.create_unique_constraint(
        "uq_evaluation",
        "evaluation",
        ["prompt_id", "prompt_variation_id", "evaluator_id", "endpoint_str"],
    )
    # ### end Alembic commands ###
