"""new query table with tags

Revision ID: f389050df167
Revises: 4251682afa02
Create Date: 2024-09-03 12:29:49.554042

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f389050df167"
down_revision = "4251682afa02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "local_endpoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "query",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("at", sa.TIMESTAMP(), nullable=False),
        sa.Column("model_provider_str", sa.String(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=True),
        sa.Column("custom_endpoint_id", sa.Integer(), nullable=True),
        sa.Column("local_endpoint_id", sa.Integer(), nullable=True),
        sa.Column("credits", sa.Numeric(), nullable=False),
        sa.Column("query_body", sa.String(), nullable=False),
        sa.Column("response_body", sa.String(), nullable=False),
        sa.Column("signature", sa.String(), nullable=True),
        sa.Column("used_router", sa.Boolean(), nullable=True),
        sa.Column("router", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["custom_endpoint_id"],
            ["custom_endpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["local_endpoint_id"],
            ["local_endpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_query_custom_endpoint_id"),
        "query",
        ["custom_endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_query_endpoint_id"), "query", ["endpoint_id"], unique=False
    )
    op.create_index(
        op.f("ix_query_local_endpoint_id"), "query", ["local_endpoint_id"], unique=False
    )
    op.create_index(op.f("ix_query_user_id"), "query", ["user_id"], unique=False)
    op.create_index(
        "ix_user_endpoint", "query", ["user_id", "endpoint_id"], unique=False
    )
    op.create_table(
        "query_tag_association",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "query_id", "tag_id"),
    )
    op.create_index(
        op.f("ix_query_tag_association_query_id"),
        "query_tag_association",
        ["query_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_query_tag_association_tag_id"),
        "query_tag_association",
        ["tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_query_tag_association_user_id"),
        "query_tag_association",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_query_tag_association_user_id"), table_name="query_tag_association"
    )
    op.drop_index(
        op.f("ix_query_tag_association_tag_id"), table_name="query_tag_association"
    )
    op.drop_index(
        op.f("ix_query_tag_association_query_id"), table_name="query_tag_association"
    )
    op.drop_table("query_tag_association")
    op.drop_index("ix_user_endpoint", table_name="query")
    op.drop_index(op.f("ix_query_user_id"), table_name="query")
    op.drop_index(op.f("ix_query_local_endpoint_id"), table_name="query")
    op.drop_index(op.f("ix_query_endpoint_id"), table_name="query")
    op.drop_index(op.f("ix_query_custom_endpoint_id"), table_name="query")
    op.drop_table("query")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_table("local_endpoint")
    # ### end Alembic commands ###
