"""add ground truth column to dataset evaluation

Revision ID: fd70de5e6d04
Revises: 97d0511c4df9
Create Date: 2024-04-17 13:30:55.001292

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fd70de5e6d04"
down_revision = "97d0511c4df9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset_evaluation", sa.Column("gt_score", sa.Numeric()))
    op.execute("UPDATE dataset_evaluation SET gt_score=0")
    op.alter_column("dataset_evaluation", "gt_score", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset_evaluation", "gt_score")
    # ### end Alembic commands ###
