"""add router info to telemetry

Revision ID: a8875de1c51c
Revises: 1dec27e2c947
Create Date: 2024-06-10 08:07:20.490186

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8875de1c51c"
down_revision = "1dec27e2c947"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query", sa.Column("used_router", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query", "used_router")
    # ### end Alembic commands ###
