"""add store prompts column

Revision ID: b7218594ae58
Revises: a9005e9f3afd
Create Date: 2024-07-02 08:58:46.159975

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7218594ae58"
down_revision = "a9005e9f3afd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("store_prompts", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "store_prompts")
    # ### end Alembic commands ###
