"""add input and output token counts

Revision ID: 5033ce957c00
Revises: 0abea2858ad4
Create Date: 2024-05-08 09:34:59.136533

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5033ce957c00"
down_revision = "0abea2858ad4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dataset_evaluation",
        sa.Column("input_tokens", sa.Numeric(), nullable=True),
    )
    op.add_column(
        "dataset_evaluation",
        sa.Column("output_tokens", sa.Numeric(), nullable=True),
    )
    op.drop_column("dataset_evaluation", "metric")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dataset_evaluation",
        sa.Column("metric", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("dataset_evaluation", "output_tokens")
    op.drop_column("dataset_evaluation", "input_tokens")
    # ### end Alembic commands ###
