"""add dataset evaluation table

Revision ID: 97d0511c4df9
Revises: 7eee9929ac76
Create Date: 2024-04-16 20:07:34.892929

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "97d0511c4df9"
down_revision = "7eee9929ac76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_evaluation",
        sa.Column("mdl_name", sa.String(), nullable=False),
        sa.Column("dataset_name", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("score", sa.Numeric(), nullable=False),
        sa.Column("metric", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("mdl_name", "dataset_name", "prompt"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dataset_evaluation")
    # ### end Alembic commands ###
