"""add beta list

Revision ID: 0abea2858ad4
Revises: 1cb1c01ac935
Create Date: 2024-05-08 09:10:07.242445

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0abea2858ad4"
down_revision = "1cb1c01ac935"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beta_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("beta_list")
    # ### end Alembic commands ###
