"""change columns in dataset table

Revision ID: 76e875ab31c4
Revises: 704ebc5192eb
Create Date: 2024-09-05 14:45:03.014710

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76e875ab31c4"
down_revision = "704ebc5192eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stored_prompt", sa.Column("system_msg", sa.String(), nullable=True))
    op.add_column("stored_prompt", sa.Column("messages", sa.String(), nullable=False))
    op.add_column(
        "stored_prompt",
        sa.Column("prompt_kwargs", sa.String(), nullable=False),
    )
    op.create_index(
        op.f("ix_stored_prompt_messages"),
        "stored_prompt",
        ["messages"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_prompt_system_msg"),
        "stored_prompt",
        ["system_msg"],
        unique=False,
    )
    op.drop_column("stored_prompt", "prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stored_prompt",
        sa.Column("prompt", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_stored_prompt_system_msg"), table_name="stored_prompt")
    op.drop_index(op.f("ix_stored_prompt_messages"), table_name="stored_prompt")
    op.drop_column("stored_prompt", "prompt_kwargs")
    op.drop_column("stored_prompt", "messages")
    op.drop_column("stored_prompt", "system_msg")
    # ### end Alembic commands ###
