"""remove index on stored prompt messages

Revision ID: 6deeccc0faa5
Revises: dbdd6bcbac52
Create Date: 2024-09-13 08:43:26.112418

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6deeccc0faa5"
down_revision = "dbdd6bcbac52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stored_prompt_messages", table_name="stored_prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_stored_prompt_messages",
        "stored_prompt",
        ["messages"],
        unique=False,
    )
    # ### end Alembic commands ###
