"""Renames custom endpoint column from mdl_name to model_arg

Revision ID: e0f4abae5129
Revises: 095d832adb8d
Create Date: 2024-10-13 17:05:31.195276

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "e0f4abae5129"
down_revision = "095d832adb8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_endpoint",
        "mdl_name",
        nullable=True,
        new_column_name="model_arg",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_endpoint",
        "model_arg",
        nullable=True,
        new_column_name="mdl_name",
    )
    # ### end Alembic commands ###
