""" fixing bugs

Revision ID: 0cb6b7a81b25
Revises: a04165c801bf
Create Date: 2024-09-12 11:12:05.717253

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0cb6b7a81b25"
down_revision = "a04165c801bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_endpoint_benchmark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("custom_endpoint_id", sa.Integer(), nullable=False),
        sa.Column("metric_name", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("measured_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["custom_endpoint_id"],
            ["custom_endpoint.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("evaluation", sa.Column("endpoint_str", sa.String(), nullable=False))
    op.add_column(
        "judgement", sa.Column("judge_endpoint_str", sa.String(), nullable=False)
    )
    op.add_column("judgement", sa.Column("evaluator_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        "judgement_judge_endpoint_id_fkey", "judgement", type_="foreignkey"
    )
    op.create_foreign_key(None, "judgement", "evaluator", ["evaluator_id"], ["id"])
    op.drop_column("judgement", "judge_endpoint_id")
    op.create_unique_constraint(
        "uq_user_endpoint", "local_endpoint", ["user_id", "name"]
    )
    op.create_unique_constraint("uq_user_tag", "tags", ["user_id", "tag_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_tag", "tags", type_="unique")
    op.drop_constraint("uq_user_endpoint", "local_endpoint", type_="unique")
    op.add_column(
        "judgement",
        sa.Column(
            "judge_endpoint_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "judgement", type_="foreignkey")
    op.create_foreign_key(
        "judgement_judge_endpoint_id_fkey",
        "judgement",
        "endpoint",
        ["judge_endpoint_id"],
        ["id"],
    )
    op.drop_column("judgement", "evaluator_id")
    op.drop_column("judgement", "judge_endpoint_str")
    op.drop_column("evaluation", "endpoint_str")
    op.drop_table("custom_endpoint_benchmark")
    # ### end Alembic commands ###
