"""add signature to query telemetry

Revision ID: b1d2a431b00f
Revises: 5033ce957c00
Create Date: 2024-06-04 14:31:34.689085

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b1d2a431b00f"
down_revision = "5033ce957c00"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query", sa.Column("signature", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query", "signature")
    # ### end Alembic commands ###
