"""add cc fingerprint table

Revision ID: 70b602194a76
Revises: b7218594ae58
Create Date: 2024-07-02 11:54:46.632632

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70b602194a76"
down_revision = "b7218594ae58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_card_fingerprint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credit_card_fingerprint")
    # ### end Alembic commands ###
