"""empty message

Revision ID: 366cf88065b9
Revises: 991cb19cb9af
Create Date: 2024-03-24 20:35:15.288301

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "366cf88065b9"
down_revision = "991cb19cb9af"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recharge", sa.Column("transaction_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recharge", "transaction_id")
    # ### end Alembic commands ###
