"""Added prompt and response parsers

Revision ID: d19661e28ed5
Revises: f1131ce1eefb
Create Date: 2024-09-24 12:29:28.337927

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d19661e28ed5"
down_revision = "f1131ce1eefb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluator",
        sa.Column(
            "prompt_parser",
            sa.String(),
            nullable=False,
            server_default="{\"user_message\": \"['messages'][-1]['content']\"}",
        ),
    )
    op.add_column(
        "evaluator",
        sa.Column(
            "response_parser",
            sa.String(),
            nullable=False,
            server_default="{\"assistant_message\": \"['message']['content']\"}",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluator", "response_parser")
    op.drop_column("evaluator", "prompt_parser")
    # ### end Alembic commands ###
