"""Add version to log unique constraint

Revision ID: b50dc2dba723
Revises: 6ba521af7a38
Create Date: 2025-02-18 13:51:43.979189

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b50dc2dba723"
down_revision = "6ba521af7a38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_log_event_id_key", "log", type_="unique")
    op.create_unique_constraint(
        "uq_log_event_id_key_version",
        "log",
        ["log_event_id", "key", "version"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_log_event_id_key_version", "log", type_="unique")
    op.create_unique_constraint("uq_log_event_id_key", "log", ["log_event_id", "key"])
    # ### end Alembic commands ###
