"""Add unique_id_names column to context table and remove unique_id_name column.

Revision ID: d9b3c968c46c
Revises: 648dd81c1a5e
Create Date: 2025-06-27 23:57:07.168703

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d9b3c968c46c"
down_revision = "648dd81c1a5e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "unique_id_names",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='"row_id"',
            nullable=False,
        ),
    )
    op.drop_column("context", "unique_id_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "unique_id_name",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'\"row_id\"'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("context", "unique_id_names")
    # ### end Alembic commands ###
