"""add optional whatsapp_number field to assistants table

Revision ID: 471127163463
Revises: 1376c83be652
Create Date: 2025-07-01 10:50:48.866329

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "471127163463"
down_revision = "1376c83be652"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column("whatsapp_number", sa.String(), nullable=True),
    )
    op.drop_column("assistants", "whatsapp_sid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column("whatsapp_sid", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("assistants", "whatsapp_number")
    # ### end Alembic commands ###
