"""Adding indexes to improve query performance

Revision ID: 450bf2f1266a
Revises: daaf1b9415a5
Create Date: 2025-03-21 01:01:10.532356

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "450bf2f1266a"
down_revision = "daaf1b9415a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_log_key"), "log", ["key"], unique=False)
    op.create_index(
        "idx_log_event_project_id_id",
        "log_event",
        ["project_id", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_log_event_project_id_id", table_name="log_event")
    op.drop_index(op.f("ix_log_key"), table_name="log")
    # ### end Alembic commands ###
