"""Change unique_id_name column from VARCHAR to JSONB to support nested unique IDs

Revision ID: 648dd81c1a5e
Revises: b341517aa97f
Create Date: 2025-06-27 21:17:21.610160

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "648dd81c1a5e"
down_revision = "b341517aa97f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "context",
        "unique_id_name",
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'row_id'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "context",
        "unique_id_name",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        existing_server_default=sa.text("'row_id'::character varying"),
    )
    # ### end Alembic commands ###
