"""Add voice mode to Assistant table

Revision ID: 3d05bea20ead
Revises: support_variable_vector_dims
Create Date: 2025-11-10 15:22:57.412288

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d05bea20ead"
down_revision = "support_variable_vector_dims"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the new nullable column to the table.
    op.add_column(
        "assistants",
        sa.Column("voice_mode", sa.String(), nullable=True),
    )

    # Step 2: Perform the data migration.
    # First, set a default 'tts' for all existing assistants that have a voice.
    # This ensures assistants with providers like 'cartesia' get the correct default.
    op.execute(
        "UPDATE assistants SET voice_mode = 'tts' WHERE voice_provider IS NOT NULL",
    )

    # Second, specifically update assistants with 'openai' provider to 'sts'.
    # This will override the 'tts' default set in the previous step for these specific rows.
    op.execute(
        "UPDATE assistants SET voice_mode = 'sts' WHERE voice_provider = 'openai'",
    )

    # Step 3: Add the CHECK constraint after the data has been populated.
    op.create_check_constraint(
        "ck_assistant_voice_mode",
        "assistants",
        "voice_mode IN ('tts', 'sts')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # In downgrade, operations are reversed. First, drop the constraint.
    op.drop_constraint("ck_assistant_voice_mode", "assistants", type_="check")
    # Then, drop the column.
    op.drop_column("assistants", "voice_mode")
    # ### end Alembic commands ###
