"""Add provider to Voice table and make gender optional

Revision ID: b341517aa97f
Revises: 9d58e7c772e5
Create Date: 2025-06-23 16:51:53.779290

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b341517aa97f"
down_revision = "9d58e7c772e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voices",
        sa.Column("provider", sa.String(), server_default="cartesia", nullable=True),
    )
    op.alter_column(
        "voices",
        "gender",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "voices",
        "gender",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("voices", "provider")
    # ### end Alembic commands ###
