"""add assistant hiring approval and one time link

Revision ID: 000958ab98b9
Revises: 8a8cd9e801e8
Create Date: 2025-05-27 16:00:22.354634

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000958ab98b9"
down_revision = "8a8cd9e801e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_hiring_one_time_approval_link",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("claimed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assistant_hiring_one_time_approval_link_token"),
        "assistant_hiring_one_time_approval_link",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_assistant_hiring_one_time_approval_link_user_id"),
        "assistant_hiring_one_time_approval_link",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "auth_user", sa.Column("assistant_hiring_approval", sa.String(), nullable=True)
    )
    op.add_column(
        "auth_user",
        sa.Column(
            "has_claimed_approval_link",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_auth_user_assistant_hiring_approval"),
        "auth_user",
        ["assistant_hiring_approval"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth_user_assistant_hiring_approval"), table_name="auth_user"
    )
    op.drop_column("auth_user", "has_claimed_approval_link")
    op.drop_column("auth_user", "assistant_hiring_approval")
    op.drop_index(
        op.f("ix_assistant_hiring_one_time_approval_link_user_id"),
        table_name="assistant_hiring_one_time_approval_link",
    )
    op.drop_index(
        op.f("ix_assistant_hiring_one_time_approval_link_token"),
        table_name="assistant_hiring_one_time_approval_link",
    )
    op.drop_table("assistant_hiring_one_time_approval_link")
    # ### end Alembic commands ###
