"""adding new JSONLog table to preserve dict ordering

Revision ID: b4583965a112
Revises: c0fbba95c2fe
Create Date: 2025-02-01 21:27:12.333913

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b4583965a112"
down_revision = "c0fbba95c2fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "json_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("log_event_id", "key"),
    )
    op.create_index(
        op.f("ix_json_log_log_event_id"),
        "json_log",
        ["log_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f("ix_json_log_log_event_id"), table_name="json_log")
    op.drop_table("json_log")
    # ### end Alembic commands ###
