"""Add description fields to project and field_type tables, remove artifact tables

Revision ID: c4c58223e97d
Revises: d1110527c042
Create Date: 2025-06-17 21:48:15.438857

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c4c58223e97d"
down_revision = "d1110527c042"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifact_project_id"), table_name="artifact")
    op.drop_table("artifact")
    op.drop_index(op.f("ix_context_artifact_context_id"), table_name="context_artifact")
    op.drop_table("context_artifact")
    op.add_column(
        "field_type",
        sa.Column("description", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "project",
        sa.Column("description", sa.String(length=256), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "description")
    op.drop_column("field_type", "description")
    op.create_table(
        "context_artifact",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("context_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["context.id"],
            name=op.f("context_artifact_context_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("context_artifact_pkey")),
        sa.UniqueConstraint(
            "context_id",
            "key",
            name=op.f("uq_context_artifact_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_context_artifact_context_id"),
        "context_artifact",
        ["context_id"],
        unique=False,
    )
    op.create_table(
        "artifact",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("artifact_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("artifact_pkey")),
    )
    op.create_index(
        op.f("ix_artifact_project_id"),
        "artifact",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###
