"""add assistant phone country input

Revision ID: 9d58e7c772e5
Revises: c4c58223e97d
Create Date: 2025-06-19 18:19:52.977191

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d58e7c772e5"
down_revision = "c4c58223e97d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_artifact_project_id", table_name="artifact")
    op.drop_table("artifact")
    op.drop_index("ix_context_artifact_context_id", table_name="context_artifact")
    op.drop_table("context_artifact")
    op.add_column("assistants", sa.Column("country", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "country")
    op.create_table(
        "context_artifact",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("context_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["context.id"],
            name="context_artifact_context_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="context_artifact_pkey"),
        sa.UniqueConstraint("context_id", "key", name="uq_context_artifact_key"),
    )
    op.create_index(
        "ix_context_artifact_context_id",
        "context_artifact",
        ["context_id"],
        unique=False,
    )
    op.create_table(
        "artifact",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="artifact_project_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="artifact_pkey"),
    )
    op.create_index("ix_artifact_project_id", "artifact", ["project_id"], unique=False)
    # ### end Alembic commands ###
