"""Add webhook log table and recharge status column

Revision ID: d175ef45ab65
Revises: 0052a63d731e
Create Date: 2025-04-03 22:11:55.382058

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d175ef45ab65"
down_revision = "0052a63d731e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_log",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column(
            "processed_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.add_column(
        "recharge",
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
    )
    op.alter_column("recharge", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("recharge_type_fkey", "recharge", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recharge", "status")
    op.create_foreign_key(
        "recharge_type_fkey",
        "recharge",
        "recharge_type",
        ["type"],
        ["type"],
    )
    op.alter_column("recharge", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table("webhook_log")
    # ### end Alembic commands ###
