"""Replace CASCADE with SET NULL when deleting a voice

Revision ID: 14c60904630a
Revises: 72fbacb6b22e
Create Date: 2025-05-21 19:42:44.541929

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14c60904630a"
down_revision = "72fbacb6b22e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("assistants_voice_id_fkey", "assistants", type_="foreignkey")
    op.create_foreign_key(
        None, "assistants", "voices", ["voice_id"], ["voice_id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assistants", type_="foreignkey")
    op.create_foreign_key(
        "assistants_voice_id_fkey",
        "assistants",
        "voices",
        ["voice_id"],
        ["voice_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
