"""Make assistant fields optional

Revision ID: 2de4af3a96de
Revises: 4d1e3019dab3
Create Date: 2025-04-30 16:09:54.584692

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2de4af3a96de"
down_revision = "4d1e3019dab3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assistants",
        "first_name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column("assistants", "surname", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("assistants", "age", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("assistants", "region", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "assistants",
        "profile_photo",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column("assistants", "about", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "assistants",
        "weekly_limit",
        existing_type=sa.NUMERIC(),
        nullable=True,
    )
    op.alter_column(
        "assistants",
        "max_parallel",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assistants",
        "max_parallel",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "assistants",
        "weekly_limit",
        existing_type=sa.NUMERIC(),
        nullable=False,
    )
    op.alter_column("assistants", "about", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "assistants",
        "profile_photo",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column("assistants", "region", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("assistants", "age", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("assistants", "surname", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "assistants",
        "first_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
