"""Add timezone to User and Assistant tables

Revision ID: 1cb930843ee0
Revises: 3d05bea20ead
Create Date: 2025-11-11 16:09:45.619429

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1cb930843ee0"
down_revision = "3d05bea20ead"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("timezone", sa.String(), nullable=True))
    op.add_column("auth_user", sa.Column("timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_user", "timezone")
    op.drop_column("assistants", "timezone")
    # ### end Alembic commands ###
