"""Add mutable field support to FieldType model

Revision ID: 7659f0a372db
Revises: 9d120cbc0b48
Create Date: 2025-02-05 17:41:39.566218

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7659f0a372db"
down_revision = "9d120cbc0b48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field_type",
        sa.Column("mutable", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("field_type", "mutable")
    # ### end Alembic commands ###
