"""Replace unique_id_names with separate unique_key_names and unique_key_types JSONB arrays to support flexible composite keys with mixed types in the Context table

Revision ID: e8b659127557
Revises: da76fbc330ac
Create Date: 2025-08-19 17:16:15.085074

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e8b659127557"
down_revision = "da76fbc330ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "unique_key_names",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "context",
        sa.Column(
            "unique_key_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.drop_column("context", "unique_id_names")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "unique_id_names",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'\"row_id\"'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("context", "unique_key_types")
    op.drop_column("context", "unique_key_names")
    # ### end Alembic commands ###
