"""add_organization_direct_billing

Revision ID: 621d5dcac748
Revises: 9898c8469548
Create Date: 2025-12-11 13:20:04.054061

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "621d5dcac748"
down_revision = "9898c8469548"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("credits", sa.Numeric(), server_default="0", nullable=False),
    )
    op.add_column(
        "organization", sa.Column("stripe_customer_id", sa.String(), nullable=True)
    )
    op.add_column(
        "organization",
        sa.Column("autorecharge", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "organization",
        sa.Column(
            "autorecharge_threshold", sa.Numeric(), server_default="10", nullable=False
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "autorecharge_qty", sa.Numeric(), server_default="100", nullable=False
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "account_status", sa.String(), server_default="ACTIVE", nullable=False
        ),
    )
    op.add_column(
        "organization", sa.Column("billing_email", sa.String(), nullable=True)
    )
    op.add_column(
        "organization", sa.Column("business_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "organization", sa.Column("tax_id", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "organization",
        sa.Column(
            "billing_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "billing_setup_complete",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.alter_column(
        "organization", "billing_user_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_index(
        op.f("ix_organization_stripe_customer_id"),
        "organization",
        ["stripe_customer_id"],
        unique=True,
    )
    op.alter_column(
        "organization_invite",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_org_invite_org_email"), table_name="organization_invite")
    op.alter_column(
        "permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("recharge", sa.Column("organization_id", sa.Integer(), nullable=True))
    op.alter_column("recharge", "user_id", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(
        op.f("ix_recharge_organization_id"),
        "recharge",
        ["organization_id"],
        unique=False,
    )
    op.drop_constraint(op.f("recharge_user_id_fkey"), "recharge", type_="foreignkey")
    op.create_foreign_key(
        None,
        "recharge",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "recharge", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "resource_access",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role_permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "team",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "team_member",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "team_member",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "team",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role_permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "resource_access",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "recharge", type_="foreignkey")
    op.drop_constraint(None, "recharge", type_="foreignkey")
    op.create_foreign_key(
        op.f("recharge_user_id_fkey"), "recharge", "users", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_recharge_organization_id"), table_name="recharge")
    op.alter_column("recharge", "user_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("recharge", "organization_id")
    op.alter_column(
        "permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_org_invite_org_email"),
        "organization_invite",
        ["organization_id", "invitee_email"],
        unique=False,
    )
    op.alter_column(
        "organization_invite",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_organization_stripe_customer_id"), table_name="organization")
    op.alter_column(
        "organization", "billing_user_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("organization", "billing_setup_complete")
    op.drop_column("organization", "billing_address")
    op.drop_column("organization", "tax_id")
    op.drop_column("organization", "business_name")
    op.drop_column("organization", "billing_email")
    op.drop_column("organization", "account_status")
    op.drop_column("organization", "autorecharge_qty")
    op.drop_column("organization", "autorecharge_threshold")
    op.drop_column("organization", "autorecharge")
    op.drop_column("organization", "stripe_customer_id")
    op.drop_column("organization", "credits")
    # ### end Alembic commands ###
