"""Update field_type migration to enforce non-null context_id

Revision ID: cf380df9266f
Revises: 13d9c5f4aef5
Create Date: 2025-02-19 02:27:30.745391

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf380df9266f"
down_revision = "13d9c5f4aef5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, update any existing NULL context_id values to a default value of 1
    op.execute(
        """
        UPDATE field_type
        SET context_id = 1
        WHERE context_id IS NULL
    """
    )

    # Now we can safely set the NOT NULL constraint
    op.alter_column(
        "field_type", "context_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint("uq_project_context_field_name", "field_type", type_="unique")
    op.create_unique_constraint(
        "uq_project_field_name_context_id",
        "field_type",
        ["project_id", "field_name", "context_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_project_field_name_context_id", "field_type", type_="unique")
    op.create_unique_constraint(
        "uq_project_context_field_name",
        "field_type",
        ["project_id", "context_id", "field_name"],
    )
    op.alter_column(
        "field_type", "context_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
