"""icons & ordering for project/interface/tab

Revision ID: 05bc6ea4c6f0
Revises: a4600d2adc40
Create Date: 2025-08-05 18:16:19.138082

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "05bc6ea4c6f0"
down_revision = "a4600d2adc40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interface",
        sa.Column("icon", sa.String(), server_default="folder", nullable=False),
    )
    op.add_column(
        "interface",
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "project",
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "tab",
        sa.Column("icon", sa.String(), server_default="tab", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tab", "icon")
    op.drop_column("project", "order")
    op.drop_column("interface", "order")
    op.drop_column("interface", "icon")
    # ### end Alembic commands ###
