"""Rename file_path to file_name in editor_tile table

Revision ID: 3898244e2fab
Revises: d717913966d6
Create Date: 2025-06-04 19:25:42.686726

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3898244e2fab"
down_revision = "d717913966d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("editor_tile", sa.Column("file_name", sa.String(), nullable=True))
    op.drop_column("editor_tile", "file_path")
    op.alter_column(
        "users",
        "store_prompts",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "store_prompts", existing_type=sa.BOOLEAN(), nullable=True)
    op.add_column(
        "editor_tile",
        sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("editor_tile", "file_name")
    # ### end Alembic commands ###
