"""Rename min_width and min_height to minW and minH. Add color to tile. Make type nullable.

Revision ID: 4ae087139447
Revises: afffa4a2a8e2
Create Date: 2025-05-12 16:09:52.719989

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ae087139447"
down_revision = "afffa4a2a8e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tile", sa.Column("minW", sa.Float(), nullable=True))
    op.add_column("tile", sa.Column("minH", sa.Float(), nullable=True))
    op.add_column("tile", sa.Column("color", sa.String(), nullable=True))
    op.alter_column("tile", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("tile", "min_height")
    op.drop_column("tile", "min_width")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tile",
        sa.Column(
            "min_width",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tile",
        sa.Column(
            "min_height",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column("tile", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("tile", "color")
    op.drop_column("tile", "minH")
    op.drop_column("tile", "minW")
    # ### end Alembic commands ###
