"""added the created_at attribute to the interface and temp interface tables to maintain order of tabs added

Revision ID: cf18b8b0968b
Revises: 6aed698e9497
Create Date: 2025-04-09 16:29:52.527806

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf18b8b0968b"
down_revision = "6aed698e9497"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interface",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "temp_interface",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("temp_interface", "created_at")
    op.drop_column("interface", "created_at")
    # ### end Alembic commands ###
