"""removed the column_context field from the interface and temp_interface tables

Revision ID: e8f76de792cd
Revises: 13d9c5f4aef5
Create Date: 2025-02-26 11:13:51.100179

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8f76de792cd"
down_revision = "13d9c5f4aef5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interface", "column_context")
    op.drop_column("temp_interface", "column_context")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "temp_interface",
        sa.Column("column_context", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "interface",
        sa.Column("column_context", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
