"""Add billing infrastructure

Revision ID: 7b448af747e2
Revises: 2c12988f18c9
Create Date: 2025-05-30 21:15:28.539556

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7b448af747e2"
down_revision = "2c12988f18c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recharge",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING_INVOICE",
            "INVOICE_CREATED",
            "PAID",
            "FAILED",
            name="recharge_status",
        ),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING_INVOICE'::recharge_status"),
    )
    op.alter_column(
        "users",
        "store_prompts",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "store_prompts", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "recharge",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "PENDING_INVOICE",
            "INVOICE_CREATED",
            "PAID",
            "FAILED",
            name="recharge_status",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING_INVOICE'::recharge_status"),
    )
    # ### end Alembic commands ###
