"""Adjust schema to allow cascade deletion for Project, LogEvent, Context and Interface.

Revision ID: c75079c801c8
Revises: 064db0a6bbd1
Create Date: 2025-02-13 15:35:49.796737

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c75079c801c8"
down_revision = "064db0a6bbd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interface", sa.Column("project_id", sa.Integer(), nullable=False))
    op.drop_constraint("it_uq_project_name", "interface", type_="unique")
    op.create_unique_constraint(
        "it_uq_project_name",
        "interface",
        ["user_id", "project_id", "name"],
    )
    op.create_index(
        op.f("ix_interface_project_id"),
        "interface",
        ["project_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "interface",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("interface", "project")
    op.drop_column("interface", "context")
    op.drop_constraint(
        "log_event_context_log_event_id_fkey",
        "log_event_context",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "log_event_context",
        "log_event",
        ["log_event_id"],
        ["id"],
    )
    op.add_column(
        "temp_interface",
        sa.Column("project_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint("temp_it_uq_project_name", "temp_interface", type_="unique")
    op.create_unique_constraint(
        "temp_it_uq_project_name",
        "temp_interface",
        ["user_id", "project_id", "name"],
    )
    op.create_index(
        op.f("ix_temp_interface_project_id"),
        "temp_interface",
        ["project_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "temp_interface",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("temp_interface", "project")
    op.drop_column("temp_interface", "context")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "temp_interface",
        sa.Column("context", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "temp_interface",
        sa.Column("project", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "temp_interface", type_="foreignkey")
    op.drop_index(op.f("ix_temp_interface_project_id"), table_name="temp_interface")
    op.drop_constraint("temp_it_uq_project_name", "temp_interface", type_="unique")
    op.create_unique_constraint(
        "temp_it_uq_project_name",
        "temp_interface",
        ["user_id", "project", "name"],
    )
    op.drop_column("temp_interface", "project_id")
    op.drop_constraint(None, "log_event_context", type_="foreignkey")
    op.create_foreign_key(
        "log_event_context_log_event_id_fkey",
        "log_event_context",
        "log_event",
        ["log_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "interface",
        sa.Column("context", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "interface",
        sa.Column("project", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "interface", type_="foreignkey")
    op.drop_index(op.f("ix_interface_project_id"), table_name="interface")
    op.drop_constraint("it_uq_project_name", "interface", type_="unique")
    op.create_unique_constraint(
        "it_uq_project_name",
        "interface",
        ["user_id", "project", "name"],
    )
    op.drop_column("interface", "project_id")
    # ### end Alembic commands ###
