"""Adding tables to support Versioned Contexts and Logs

Revision ID: 8ebf4f10635f
Revises: 7659f0a372db
Create Date: 2025-02-11 22:55:02.352877

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8ebf4f10635f"
down_revision = "7659f0a372db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "context_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "log_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
            comment="Stores {log_event_id: {field_key: version_int}}",
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "archived_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["context_id"], ["context.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_history_context_id"),
        "context_history",
        ["context_id"],
        unique=False,
    )
    op.create_table(
        "json_log_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "archived_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_json_log_history_log_event_id"),
        "json_log_history",
        ["log_event_id"],
        unique=False,
    )
    op.create_table(
        "log_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("inferred_type", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "archived_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_history_log_event_id"),
        "log_history",
        ["log_event_id"],
        unique=False,
    )
    op.add_column(
        "context",
        sa.Column("is_versioned", sa.Boolean(), server_default="f", nullable=False),
    )
    op.add_column(
        "context",
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("context", "version")
    op.drop_column("context", "is_versioned")
    op.drop_index(op.f("ix_log_history_log_event_id"), table_name="log_history")
    op.drop_table("log_history")
    op.drop_index(
        op.f("ix_json_log_history_log_event_id"),
        table_name="json_log_history",
    )
    op.drop_table("json_log_history")
    op.drop_index(op.f("ix_context_history_context_id"), table_name="context_history")
    op.drop_table("context_history")
    # ### end Alembic commands ###
