"""Replace direct log_event_id foreign keys with many-to-many association tables for Log, DerivedLog, JSONLog, and JSONLogHistory to support flexible log-event relationships

Revision ID: da76fbc330ac
Revises: 05bc6ea4c6f0
Create Date: 2025-08-18 14:56:40.726318

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da76fbc330ac"
down_revision = "05bc6ea4c6f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_event_derived_log",
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("derived_log_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["derived_log_id"],
            ["derived_log.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("log_event_id", "derived_log_id"),
    )
    op.create_index(
        "idx_log_event_derived_log_derived_log_id",
        "log_event_derived_log",
        ["derived_log_id"],
        unique=False,
    )
    op.create_index(
        "idx_log_event_derived_log_event_id",
        "log_event_derived_log",
        ["log_event_id"],
        unique=False,
    )
    op.create_table(
        "log_event_json_log",
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("json_log_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["json_log_id"], ["json_log.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("log_event_id", "json_log_id"),
    )
    op.create_index(
        "idx_log_event_json_log_event_id",
        "log_event_json_log",
        ["log_event_id"],
        unique=False,
    )
    op.create_index(
        "idx_log_event_json_log_json_log_id",
        "log_event_json_log",
        ["json_log_id"],
        unique=False,
    )
    op.create_table(
        "log_event_json_log_history",
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("json_log_history_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["json_log_history_id"],
            ["json_log_history.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("log_event_id", "json_log_history_id"),
    )
    op.create_index(
        "idx_log_event_json_log_history_event_id",
        "log_event_json_log_history",
        ["log_event_id"],
        unique=False,
    )
    op.create_index(
        "idx_log_event_json_log_history_json_log_history_id",
        "log_event_json_log_history",
        ["json_log_history_id"],
        unique=False,
    )
    op.create_table(
        "log_event_log",
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["log_id"], ["log.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("log_event_id", "log_id"),
    )
    op.create_index(
        "idx_log_event_log_event_id",
        "log_event_log",
        ["log_event_id"],
        unique=False,
    )
    op.create_index(
        "idx_log_event_log_log_id",
        "log_event_log",
        ["log_id"],
        unique=False,
    )
    op.drop_constraint(
        "derived_log_log_event_id_key_key",
        "derived_log",
        type_="unique",
    )
    op.drop_index("ix_derived_log_log_event_id", table_name="derived_log")
    op.drop_constraint(
        "derived_log_log_event_id_fkey",
        "derived_log",
        type_="foreignkey",
    )
    op.drop_column("derived_log", "log_event_id")
    op.drop_index("ix_json_log_log_event_id", table_name="json_log")
    op.drop_constraint("json_log_log_event_id_key_key", "json_log", type_="unique")
    op.drop_constraint("json_log_log_event_id_fkey", "json_log", type_="foreignkey")
    op.drop_column("json_log", "log_event_id")
    op.drop_index("ix_json_log_history_log_event_id", table_name="json_log_history")
    op.drop_constraint(
        "json_log_history_log_event_id_fkey",
        "json_log_history",
        type_="foreignkey",
    )
    op.drop_column("json_log_history", "log_event_id")
    op.drop_index("ix_log_log_event_id", table_name="log")
    op.drop_constraint("log_log_event_id_key_param_version_key", "log", type_="unique")
    op.create_index(
        "idx_log_key_param_version",
        "log",
        ["key", "param_version"],
        unique=False,
    )
    op.drop_constraint("log_log_event_id_fkey", "log", type_="foreignkey")
    op.drop_column("log", "log_event_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "log",
        sa.Column("log_event_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "log_log_event_id_fkey",
        "log",
        "log_event",
        ["log_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("idx_log_key_param_version", table_name="log")
    op.create_unique_constraint(
        "log_log_event_id_key_param_version_key",
        "log",
        ["log_event_id", "key", "param_version"],
    )
    op.create_index("ix_log_log_event_id", "log", ["log_event_id"], unique=False)
    op.add_column(
        "json_log_history",
        sa.Column("log_event_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "json_log_history_log_event_id_fkey",
        "json_log_history",
        "log_event",
        ["log_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_json_log_history_log_event_id",
        "json_log_history",
        ["log_event_id"],
        unique=False,
    )
    op.add_column(
        "json_log",
        sa.Column("log_event_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "json_log_log_event_id_fkey",
        "json_log",
        "log_event",
        ["log_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "json_log_log_event_id_key_key",
        "json_log",
        ["log_event_id", "key"],
    )
    op.create_index(
        "ix_json_log_log_event_id",
        "json_log",
        ["log_event_id"],
        unique=False,
    )
    op.add_column(
        "derived_log",
        sa.Column("log_event_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "derived_log_log_event_id_fkey",
        "derived_log",
        "log_event",
        ["log_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_derived_log_log_event_id",
        "derived_log",
        ["log_event_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "derived_log_log_event_id_key_key",
        "derived_log",
        ["log_event_id", "key"],
    )
    op.drop_index("idx_log_event_log_log_id", table_name="log_event_log")
    op.drop_index("idx_log_event_log_event_id", table_name="log_event_log")
    op.drop_table("log_event_log")
    op.drop_index(
        "idx_log_event_json_log_history_json_log_history_id",
        table_name="log_event_json_log_history",
    )
    op.drop_index(
        "idx_log_event_json_log_history_event_id",
        table_name="log_event_json_log_history",
    )
    op.drop_table("log_event_json_log_history")
    op.drop_index("idx_log_event_json_log_json_log_id", table_name="log_event_json_log")
    op.drop_index("idx_log_event_json_log_event_id", table_name="log_event_json_log")
    op.drop_table("log_event_json_log")
    op.drop_index(
        "idx_log_event_derived_log_event_id",
        table_name="log_event_derived_log",
    )
    op.drop_index(
        "idx_log_event_derived_log_derived_log_id",
        table_name="log_event_derived_log",
    )
    op.drop_table("log_event_derived_log")
    # ### end Alembic commands ###
