"""Add field_category and created_at to field_type table

Revision ID: 53af6e90a854
Revises: c75079c801c8
Create Date: 2025-02-14 23:08:29.571902

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "53af6e90a854"
down_revision = "c75079c801c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field_type",
        sa.Column(
            "field_category",
            sa.String(),
            server_default="entry",
            nullable=False,
        ),
    )
    op.add_column(
        "field_type",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("field_type", "created_at")
    op.drop_column("field_type", "field_category")
    # ### end Alembic commands ###
