"""add onboarded flag to auth_user

Revision ID: c4f43793ef49
Revises: c4c44a11dce9
Create Date: 2025-07-11 12:15:48.478928

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4f43793ef49"
down_revision = "c4c44a11dce9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_user",
        sa.Column("onboarded", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_user", "onboarded")
    # ### end Alembic commands ###
