"""Add optional profile_video field in Assistants table

Revision ID: a4600d2adc40
Revises: 3693faa73c90
Create Date: 2025-07-28 14:13:55.539123

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a4600d2adc40"
down_revision = "3693faa73c90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("profile_video", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "profile_video")
    # ### end Alembic commands ###
