"""add optional assistant whatsapp number to assistant table

Revision ID: 900e49cf9bcf
Revises: 471127163463
Create Date: 2025-07-01 12:27:03.468508

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "900e49cf9bcf"
down_revision = "471127163463"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column("user_whatsapp_number", sa.String(), nullable=True),
    )
    op.add_column(
        "assistants",
        sa.Column("assistant_whatsapp_number", sa.String(), nullable=True),
    )
    op.drop_column("assistants", "whatsapp_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column("whatsapp_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("assistants", "assistant_whatsapp_number")
    op.drop_column("assistants", "user_whatsapp_number")
    # ### end Alembic commands ###
