"""Add context_id column and update unique constraints in field_type table

Revision ID: 13d9c5f4aef5
Revises: b50dc2dba723
Create Date: 2025-02-18 16:37:03.592531

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13d9c5f4aef5"
down_revision = "b50dc2dba723"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("field_type", sa.Column("context_id", sa.Integer(), nullable=True))
    op.drop_constraint("uq_project_field_name", "field_type", type_="unique")
    op.create_unique_constraint(
        "uq_project_context_field_name",
        "field_type",
        ["project_id", "context_id", "field_name"],
    )
    op.create_foreign_key(
        None,
        "field_type",
        "context",
        ["context_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "field_type", type_="foreignkey")
    op.drop_constraint("uq_project_context_field_name", "field_type", type_="unique")
    op.create_unique_constraint(
        "uq_project_field_name",
        "field_type",
        ["project_id", "field_name"],
    )
    op.drop_column("field_type", "context_id")
    # ### end Alembic commands ###
