"""updated the interface and temp_interface tables to support multiple interfaces per project

Revision ID: 11042764eae3
Revises: 7fd935ee72f7
Create Date: 2025-01-20 11:56:57.745761

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "11042764eae3"
down_revision = "7fd935ee72f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interface", sa.Column("name", sa.String(), nullable=False))
    op.alter_column(
        "interface",
        "new_counter",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("interface", "project", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("temp_interface", sa.Column("name", sa.String(), nullable=False))
    op.alter_column(
        "temp_interface",
        "new_counter",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "temp_interface",
        "project",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "temp_interface",
        "project",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "temp_interface",
        "new_counter",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("temp_interface", "name")
    op.alter_column("interface", "project", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "interface",
        "new_counter",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("interface", "name")
    # ### end Alembic commands ###
