"""Add voice provider to the Assistants table and use it alongside the voice_id as the Voice table's primary key

Revision ID: 51f08d4846c7
Revises: add_desktop_url_to_assistants
Create Date: 2025-09-18 13:40:49.896531

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "51f08d4846c7"
down_revision = "add_desktop_url_to_assistants"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("voice_provider", sa.String(), nullable=True))
    op.drop_constraint("fk_assistants_voices", "assistants", type_="foreignkey")
    op.create_foreign_key(
        "fk_assistants_voices",
        "assistants",
        "voices",
        ["user_id", "voice_id", "voice_provider"],
        ["user_id", "voice_id", "provider"],
    )
    op.alter_column(
        "voices",
        "provider",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'cartesia'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "voices",
        "provider",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'cartesia'::character varying"),
    )
    op.drop_constraint("fk_assistants_voices", "assistants", type_="foreignkey")
    op.create_foreign_key(
        "fk_assistants_voices",
        "assistants",
        "voices",
        ["user_id", "voice_id"],
        ["user_id", "voice_id"],
    )
    op.drop_column("assistants", "voice_provider")
    # ### end Alembic commands ###
