"""Add complete billing infrastructure

Revision ID: 31c100c206d2
Revises: 2c12988f18c9
Create Date: 2025-06-03 09:56:57.970255

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31c100c206d2"
down_revision = "2c12988f18c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recharge",
        sa.Column("amount_usd", sa.Numeric(), nullable=False, server_default="0.00"),
    )
    op.add_column(
        "recharge",
        sa.Column("stripe_invoice_id", sa.String(), nullable=True),
    )
    op.add_column("recharge", sa.Column("invoice_group", sa.Date(), nullable=True))
    op.create_index(
        "idx_recharge_pending",
        "recharge",
        ["status", "invoice_group"],
        unique=False,
    )
    op.add_column("users", sa.Column("credit_balance", sa.BigInteger(), nullable=True))
    op.add_column(
        "users",
        sa.Column("billing_state", sa.String(), server_default="OK", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "billing_state")
    op.drop_column("users", "credit_balance")
    op.drop_index("idx_recharge_pending", table_name="recharge")
    op.drop_column("recharge", "invoice_group")
    op.drop_column("recharge", "stripe_invoice_id")
    op.drop_column("recharge", "amount_usd")
    # ### end Alembic commands ###
