"""empty message

Revision ID: e81f65ef8f53
Revises: 7e634b76aeaf
Create Date: 2025-01-05 12:31:59.377730

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e81f65ef8f53"
down_revision = "7e634b76aeaf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "derived_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("equation", sa.String(), nullable=True),
        sa.Column(
            "referenced_logs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("inferred_type", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("log_event_id", "key"),
    )
    op.create_index(
        op.f("ix_derived_log_log_event_id"),
        "derived_log",
        ["log_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_derived_log_log_event_id"), table_name="derived_log")
    op.drop_table("derived_log")
    # ### end Alembic commands ###
