"""Add CASCADE delete to embedding foreign key

Revision ID: df96cf4dc6f9
Revises: 4ae087139447
Create Date: 2025-05-12 22:40:03.396283

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "df96cf4dc6f9"
down_revision = "4ae087139447"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("embedding_ref_id_fkey", "embedding", type_="foreignkey")
    op.create_foreign_key(
        None,
        "embedding",
        "log_event",
        ["ref_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "embedding", type_="foreignkey")
    op.create_foreign_key(
        "embedding_ref_id_fkey",
        "embedding",
        "log_event",
        ["ref_id"],
        ["id"],
    )
    # ### end Alembic commands ###
