"""added the context fields to the interface and temp_interface tables

Revision ID: b3e3b70efd56
Revises: 6ba521af7a38
Create Date: 2025-02-18 12:04:45.491459

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3e3b70efd56"
down_revision = "6ba521af7a38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interface", sa.Column("context", sa.String(), nullable=True))
    op.add_column("interface", sa.Column("column_context", sa.String(), nullable=True))
    op.add_column("temp_interface", sa.Column("context", sa.String(), nullable=True))
    op.add_column(
        "temp_interface",
        sa.Column("column_context", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("temp_interface", "column_context")
    op.drop_column("temp_interface", "context")
    op.drop_column("interface", "column_context")
    op.drop_column("interface", "context")
    # ### end Alembic commands ###
