"""Remove dataset-related tables and indices from the database

Revision ID: 6ba521af7a38
Revises: 53af6e90a854
Create Date: 2025-02-17 13:00:08.322639

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6ba521af7a38"
down_revision = "53af6e90a854"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dataset_entry_dataset_id", table_name="dataset_entry")
    op.drop_table("dataset_entry")
    op.drop_index("ix_dataset_artifact_dataset_id", table_name="dataset_artifact")
    op.drop_table("dataset_artifact")
    op.drop_index("ix_dataset_user_id", table_name="dataset")
    op.drop_table("dataset")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('dataset_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="dataset_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="dataset_pkey"),
        sa.UniqueConstraint("user_id", "name", name="uq_userid_name"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_dataset_user_id", "dataset", ["user_id"], unique=False)
    op.create_table(
        "dataset_artifact",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
            name="dataset_artifact_dataset_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="dataset_artifact_pkey"),
    )
    op.create_index(
        "ix_dataset_artifact_dataset_id",
        "dataset_artifact",
        ["dataset_id"],
        unique=False,
    )
    op.create_table(
        "dataset_entry",
        sa.Column("id", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("dataset_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("entry", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "entry_hash",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
            name="dataset_entry_dataset_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="dataset_entry_pkey"),
        sa.UniqueConstraint("dataset_id", "entry_hash", name="uq_dataset_entry_hash"),
    )
    op.create_index(
        "ix_dataset_entry_dataset_id",
        "dataset_entry",
        ["dataset_id"],
        unique=False,
    )
    # ### end Alembic commands ###
