"""Add assistant_call_recording table for storing call recordings

Revision ID: 9e9fb4ffebf1
Revises: 236616a2d695
Create Date: 2025-05-08 11:43:50.992015

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e9fb4ffebf1"
down_revision = "236616a2d695"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_call_recording",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["assistants.agent_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assistant_call_recording_agent_id"),
        "assistant_call_recording",
        ["agent_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_assistant_call_recording_agent_id"),
        table_name="assistant_call_recording",
    )
    op.drop_table("assistant_call_recording")
    # ### end Alembic commands ###
