"""Add enum_values and enum_restrict columns to field_type table for supporting Enums

Revision ID: 236616a2d695
Revises: 46c2450d64eb
Create Date: 2025-05-07 21:42:00.286912

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "236616a2d695"
down_revision = "46c2450d64eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field_type",
        sa.Column(
            "enum_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
    )
    op.add_column(
        "field_type",
        sa.Column(
            "enum_restrict",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("field_type", "enum_restrict")
    op.drop_column("field_type", "enum_values")
    # ### end Alembic commands ###
