"""handle assistant voice and image management

Revision ID: d717913966d6
Revises: 2c12988f18c9
Create Date: 2025-06-03 15:06:37.531716

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d717913966d6"
down_revision = "2c12988f18c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voices",
        sa.Column("is_preset", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voices", "is_preset")
    # ### end Alembic commands ###
