"""Add Context, ContextArtifact, and LogEventContext tables to manage Static Contexts

Revision ID: 62b724c3ed9d
Revises: 11042764eae3
Create Date: 2025-01-22 10:44:17.957461

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62b724c3ed9d"
down_revision = "11042764eae3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "context",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_project_context_name"),
    )
    op.create_index(
        op.f("ix_context_project_id"),
        "context",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "context_artifact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["context_id"], ["context.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("context_id", "key", name="uq_context_artifact_key"),
    )
    op.create_index(
        op.f("ix_context_artifact_context_id"),
        "context_artifact",
        ["context_id"],
        unique=False,
    )
    op.create_table(
        "log_event_context",
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["context_id"], ["context.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["log_event_id"], ["log_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("log_event_id", "context_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("log_event_context")
    op.drop_index(op.f("ix_context_artifact_context_id"), table_name="context_artifact")
    op.drop_table("context_artifact")
    op.drop_index(op.f("ix_context_project_id"), table_name="context")
    op.drop_table("context")
    # ### end Alembic commands ###
