"""added the temp_interface table and changed the id column to be a string

Revision ID: d805d43c0bde
Revises: f3153538b97e
Create Date: 2025-01-08 12:17:01.005777

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d805d43c0bde"
down_revision = "f3153538b97e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temp_interface",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("new_counter", sa.Integer(), nullable=True),
        sa.Column("items", sa.String(), nullable=False),
        sa.Column("project", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_temp_interface_organization_id"),
        "temp_interface",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_temp_interface_user_id"),
        "temp_interface",
        ["user_id"],
        unique=False,
    )
    op.add_column("interface", sa.Column("project", sa.String(), nullable=True))
    op.alter_column(
        "interface",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "interface",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("interface", "project")
    op.drop_index(op.f("ix_temp_interface_user_id"), table_name="temp_interface")
    op.drop_index(
        op.f("ix_temp_interface_organization_id"),
        table_name="temp_interface",
    )
    op.drop_table("temp_interface")
    # ### end Alembic commands ###
