"""Add allow_duplicates column to context table

Revision ID: 91f24754e746
Revises: e024442293ef
Create Date: 2025-03-16 13:00:02.266077

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91f24754e746"
down_revision = "e024442293ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column("allow_duplicates", sa.Boolean(), server_default="t", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("context", "allow_duplicates")
    # ### end Alembic commands ###
