"""Add frozen column to users table

Revision ID: 6aed698e9497
Revises: d175ef45ab65
Create Date: 2025-04-04 18:23:09.291691

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6aed698e9497"
down_revision = "d175ef45ab65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("frozen", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "frozen")
    # ### end Alembic commands ###
