"""Add favorite_project table for user project favorites

Revision ID: 1ee50d5a905a
Revises: 4c3af42b1697
Create Date: 2025-04-23 10:24:39.300067

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ee50d5a905a"
down_revision = "4c3af42b1697"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "position", name="uq_user_favorite_position"),
        sa.UniqueConstraint("user_id", "project_id", name="uq_user_favorite_project"),
    )
    op.create_index(
        op.f("ix_favorite_project_user_id"),
        "favorite_project",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorite_project_user_id"), table_name="favorite_project")
    op.drop_table("favorite_project")
    # ### end Alembic commands ###
