"""change DerivedLog value field to JSONB

Revision ID: 7fd935ee72f7
Revises: d805d43c0bde
Create Date: 2025-01-16 21:19:53.752236

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7fd935ee72f7"
down_revision = "d805d43c0bde"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "derived_log",
        "value",
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        postgresql_using="value::jsonb",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "derived_log",
        "value",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        postgresql_using="value::text",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
