"""rename_tab_global_context_to_context

Revision ID: d8beba067cc0
Revises: e8b659127557
Create Date: 2025-08-22 18:11:53.721852

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d8beba067cc0"
down_revision = "e8b659127557"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tab", "global_context", new_column_name="context")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tab", "context", new_column_name="global_context")
    # ### end Alembic commands ###
