"""Add assistant voice

Revision ID: 72fbacb6b22e
Revises: df96cf4dc6f9
Create Date: 2025-05-21 13:05:02.353068

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72fbacb6b22e"
down_revision = "df96cf4dc6f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voices",
        sa.Column("voice_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("voice_id"),
    )
    op.create_index(op.f("ix_voices_user_id"), "voices", ["user_id"], unique=False)
    op.add_column("assistants", sa.Column("voice_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_assistants_voice_id"), "assistants", ["voice_id"], unique=False
    )
    op.create_foreign_key(
        None, "assistants", "voices", ["voice_id"], ["voice_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assistants", type_="foreignkey")
    op.drop_index(op.f("ix_assistants_voice_id"), table_name="assistants")
    op.drop_column("assistants", "voice_id")
    op.drop_index(op.f("ix_voices_user_id"), table_name="voices")
    op.drop_table("voices")
    # ### end Alembic commands ###
