"""added default_hidden_columns field to table tile

Revision ID: 1376c83be652
Revises: 74dded9a9283
Create Date: 2025-06-30 21:30:08.884069

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1376c83be652"
down_revision = "74dded9a9283"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "table_tile",
        sa.Column(
            "default_hidden_columns",
            sa.Boolean(),
            server_default="t",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_tile", "default_hidden_columns")
    # ### end Alembic commands ###
