"""updated the interface and temp_interface tables to add context attribute

Revision ID: 9d120cbc0b48
Revises: b4583965a112
Create Date: 2025-02-03 17:07:30.014378

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d120cbc0b48"
down_revision = "b4583965a112"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interface", sa.Column("context", sa.String(), nullable=True))
    op.add_column("temp_interface", sa.Column("context", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("temp_interface", "context")
    op.drop_column("interface", "context")
    # ### end Alembic commands ###
