"""Add whatsapp_sid column to assistants table

Revision ID: 8a8cd9e801e8
Revises: 14c60904630a
Create Date: 2025-05-26 11:11:51.412816

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a8cd9e801e8"
down_revision = "14c60904630a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("whatsapp_sid", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "whatsapp_sid")
    # ### end Alembic commands ###
