"""modify schema to support project and context version control

Revision ID: 3de7b0446970
Revises: 4772bac3def7
Create Date: 2025-06-11 17:58:14.844009

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3de7b0446970"
down_revision = "4772bac3def7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("commit_hash", sa.String(), nullable=False),
        sa.Column("commit_message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("commit_hash"),
    )
    op.create_index(
        op.f("ix_project_version_project_id"),
        "project_version",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "context_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=False),
        sa.Column("project_version_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "archived_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("commit_hash", sa.String(), nullable=False),
        sa.Column("commit_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["context_id"], ["context.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["project_version_id"],
            ["project_version.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_version_context_id"),
        "context_version",
        ["context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_version_project_version_id"),
        "context_version",
        ["project_version_id"],
        unique=False,
    )
    op.create_table(
        "log_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context_version_id", sa.Integer(), nullable=False),
        sa.Column("log_event_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("param_version", sa.Integer(), nullable=True),
        sa.Column("inferred_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["context_version_id"],
            ["context_version.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_version_context_version_id"),
        "log_version",
        ["context_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_version_log_event_id"),
        "log_version",
        ["log_event_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_context_history_context_id"), table_name="context_history")
    op.drop_table("context_history")
    op.drop_index(op.f("ix_log_history_log_event_id"), table_name="log_history")
    op.drop_table("log_history")
    op.drop_column("context", "version")
    op.add_column("log", sa.Column("param_version", sa.Integer(), nullable=True))
    op.drop_constraint(op.f("uq_log_event_id_key_version"), "log", type_="unique")
    op.create_unique_constraint(None, "log", ["log_event_id", "key", "param_version"])
    op.drop_column("log", "version")
    op.add_column(
        "project",
        sa.Column("is_versioned", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "is_versioned")
    op.add_column(
        "log",
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "log", type_="unique")
    op.create_unique_constraint(
        op.f("uq_log_event_id_key_version"),
        "log",
        ["log_event_id", "key", "version"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("log", "param_version")
    op.add_column(
        "context",
        sa.Column(
            "version",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "log_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("log_event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("inferred_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "archived_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["log_event_id"],
            ["log_event.id"],
            name=op.f("log_history_log_event_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("log_history_pkey")),
    )
    op.create_index(
        op.f("ix_log_history_log_event_id"),
        "log_history",
        ["log_event_id"],
        unique=False,
    )
    op.create_table(
        "context_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("context_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "log_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
            comment="Stores {log_event_id: {field_key: version_int}}",
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "archived_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["context.id"],
            name=op.f("context_history_context_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("context_history_pkey")),
    )
    op.create_index(
        op.f("ix_context_history_context_id"),
        "context_history",
        ["context_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_log_version_log_event_id"), table_name="log_version")
    op.drop_index(op.f("ix_log_version_context_version_id"), table_name="log_version")
    op.drop_table("log_version")
    op.drop_index(
        op.f("ix_context_version_project_version_id"),
        table_name="context_version",
    )
    op.drop_index(op.f("ix_context_version_context_id"), table_name="context_version")
    op.drop_table("context_version")
    op.drop_index(op.f("ix_project_version_project_id"), table_name="project_version")
    op.drop_table("project_version")
    # ### end Alembic commands ###
