"""add new tile type - terminal

Revision ID: 4772bac3def7
Revises: 3898244e2fab
Create Date: 2025-06-09 15:56:15.801963

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4772bac3def7"
down_revision = "3898244e2fab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "terminal_tile",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tile_id", sa.String(), nullable=False),
        sa.Column("shell_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["tile_id"], ["tile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_terminal_tile_tile_id"),
        "terminal_tile",
        ["tile_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_terminal_tile_tile_id"), table_name="terminal_tile")
    op.drop_table("terminal_tile")
    # ### end Alembic commands ###
