"""Remove unique_id_column from context table


Revision ID: 74dded9a9283
Revises: d9b3c968c46c
Create Date: 2025-06-30 14:48:19.723025

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74dded9a9283"
down_revision = "d9b3c968c46c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("context", "unique_id_column")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "unique_id_column",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
