"""added the color attribute to the interface and temp interface tables

Revision ID: 4c3af42b1697
Revises: cf18b8b0968b
Create Date: 2025-04-10 17:48:09.568922

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4c3af42b1697"
down_revision = "cf18b8b0968b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interface", sa.Column("color", sa.String(), nullable=True))
    op.add_column("temp_interface", sa.Column("color", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("temp_interface", "color")
    op.drop_column("interface", "color")
    # ### end Alembic commands ###
