"""Add auto_counting JSONB column to store auto-increment configuration separate from unique_keys

Revision ID: de93563153ae
Revises: e8b659127557
Create Date: 2025-08-22 14:35:53.908011

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de93563153ae"
down_revision = "e8b659127557"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "auto_counting",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("context", "auto_counting")
    # ### end Alembic commands ###
