"""Lift column_context and grouping to the base Tile table

Revision ID: 1bfcb03cb98a
Revises: 46c2450d64eb
Create Date: 2025-05-07 19:45:21.522858

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1bfcb03cb98a"
down_revision = "46c2450d64eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_tile", "grouping")
    op.drop_column("table_tile", "column_context")
    op.add_column("tile", sa.Column("column_context", sa.String(), nullable=True))
    op.add_column("tile", sa.Column("grouping", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tile", "grouping")
    op.drop_column("tile", "column_context")
    op.add_column(
        "table_tile",
        sa.Column("column_context", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "table_tile",
        sa.Column("grouping", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
