"""Add desktop_url column to assistants

Revision ID: add_desktop_url_to_assistants
Revises: d8beba067cc0
Create Date: 2025-09-18 12:00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_desktop_url_to_assistants"
down_revision = "d8beba067cc0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("desktop_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "desktop_url")
    # ### end Alembic commands ###
