"""Add business classification system with tax compliance

Revision ID: 96afb57ce047
Revises: 900e49cf9bcf
Create Date: 2025-07-04 14:45:25.271663

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "96afb57ce047"
down_revision = "900e49cf9bcf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_auth_user_account_type_verified",
        "auth_user",
        ["account_type", "business_verified"],
        unique=False,
    )
    op.create_index(
        "idx_auth_user_business_country",
        "auth_user",
        ["business_country"],
        unique=False,
    )
    op.create_index(
        "idx_auth_user_business_verified",
        "auth_user",
        ["business_verified"],
        unique=False,
    )
    op.create_index(
        "idx_auth_user_tax_jurisdiction",
        "auth_user",
        ["tax_jurisdiction"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_auth_user_tax_jurisdiction", table_name="auth_user")
    op.drop_index("idx_auth_user_business_verified", table_name="auth_user")
    op.drop_index("idx_auth_user_business_country", table_name="auth_user")
    op.drop_index("idx_auth_user_account_type_verified", table_name="auth_user")
    # ### end Alembic commands ###
