"""Add commit hash tracking for versioning contexts and projects

Revision ID: c4c44a11dce9
Revises: a25265d80402
Create Date: 2025-07-07 21:30:02.251959

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c4c44a11dce9"
down_revision = "a25265d80402"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column("current_commit_hash", sa.String(), nullable=True),
    )
    op.add_column(
        "context_version",
        sa.Column("prev_commit_hash", sa.String(), nullable=True),
    )
    op.add_column(
        "context_version",
        sa.Column(
            "next_commit_hash",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "project",
        sa.Column("current_commit_hash", sa.String(), nullable=True),
    )
    op.add_column(
        "project_version",
        sa.Column("prev_commit_hash", sa.String(), nullable=True),
    )
    op.add_column(
        "project_version",
        sa.Column(
            "next_commit_hash",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_version", "next_commit_hash")
    op.drop_column("project_version", "prev_commit_hash")
    op.drop_column("project", "current_commit_hash")
    op.drop_column("context_version", "next_commit_hash")
    op.drop_column("context_version", "prev_commit_hash")
    op.drop_column("context", "current_commit_hash")
    # ### end Alembic commands ###
