"""Add new assistant profile fields

Revision ID: 4d1e3019dab3
Revises: 254925615db2
Create Date: 2025-04-29 15:20:41.392543

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d1e3019dab3"
down_revision = "254925615db2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("region", sa.String(), nullable=False))
    op.add_column("assistants", sa.Column("profile_photo", sa.String(), nullable=False))
    op.add_column("assistants", sa.Column("about", sa.String(), nullable=False))
    op.add_column("assistants", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("assistants", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "email")
    op.drop_column("assistants", "phone")
    op.drop_column("assistants", "about")
    op.drop_column("assistants", "profile_photo")
    op.drop_column("assistants", "region")
    # ### end Alembic commands ###
