"""updated the interface and temp_interface tables to add uniqueness constraint

Revision ID: c0fbba95c2fe
Revises: 62b724c3ed9d
Create Date: 2025-01-29 14:22:12.754130

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c0fbba95c2fe"
down_revision = "62b724c3ed9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_derived_log_key"), "derived_log", ["key"], unique=False)
    op.create_unique_constraint(
        "it_uq_project_name",
        "interface",
        ["user_id", "project", "name"],
    )
    op.create_unique_constraint(
        "temp_it_uq_project_name",
        "temp_interface",
        ["user_id", "project", "name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("temp_it_uq_project_name", "temp_interface", type_="unique")
    op.drop_constraint("it_uq_project_name", "interface", type_="unique")
    op.drop_index(op.f("ix_derived_log_key"), table_name="derived_log")
    # ### end Alembic commands ###
