"""Add active_derived_log_template table for dynamic derived log generation

Revision ID: daaf1b9415a5
Revises: 91f24754e746
Create Date: 2025-03-18 10:28:57.573914

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "daaf1b9415a5"
down_revision = "91f24754e746"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_derived_log_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("equation", sa.String(), nullable=False),
        sa.Column(
            "referenced_logs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "filter_expression",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("inferred_type", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="t", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["context_id"], ["context.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "context_id", "key"),
    )
    op.create_index(
        op.f("ix_active_derived_log_template_context_id"),
        "active_derived_log_template",
        ["context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_active_derived_log_template_key"),
        "active_derived_log_template",
        ["key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_active_derived_log_template_project_id"),
        "active_derived_log_template",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_active_derived_log_template_project_id"),
        table_name="active_derived_log_template",
    )
    op.drop_index(
        op.f("ix_active_derived_log_template_key"),
        table_name="active_derived_log_template",
    )
    op.drop_index(
        op.f("ix_active_derived_log_template_context_id"),
        table_name="active_derived_log_template",
    )
    op.drop_table("active_derived_log_template")
    # ### end Alembic commands ###
