"""add_organization_direct_billing

Revision ID: b8ccd66119a2
Revises: 9898c8469548
Create Date: 2025-12-11 14:38:34.893779

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b8ccd66119a2"
down_revision = "9898c8469548"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("credits", sa.Numeric(), server_default="0", nullable=False),
    )
    op.add_column(
        "organization", sa.Column("stripe_customer_id", sa.String(), nullable=True)
    )
    op.add_column(
        "organization",
        sa.Column("autorecharge", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "organization",
        sa.Column(
            "autorecharge_threshold", sa.Numeric(), server_default="10", nullable=False
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "autorecharge_qty", sa.Numeric(), server_default="100", nullable=False
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "account_status", sa.String(), server_default="ACTIVE", nullable=False
        ),
    )
    op.add_column(
        "organization", sa.Column("billing_email", sa.String(), nullable=True)
    )
    op.add_column(
        "organization", sa.Column("business_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "organization", sa.Column("tax_id", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "organization",
        sa.Column(
            "billing_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "billing_setup_complete",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.alter_column(
        "organization", "billing_user_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_index(
        op.f("ix_organization_stripe_customer_id"),
        "organization",
        ["stripe_customer_id"],
        unique=True,
    )
    op.alter_column(
        "organization_invite",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_org_invite_org_email"), table_name="organization_invite")
    op.alter_column(
        "permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("recharge", sa.Column("organization_id", sa.Integer(), nullable=True))
    op.alter_column("recharge", "user_id", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(
        op.f("ix_recharge_organization_id"),
        "recharge",
        ["organization_id"],
        unique=False,
    )
    op.drop_constraint(op.f("recharge_user_id_fkey"), "recharge", type_="foreignkey")
    op.create_foreign_key(
        None,
        "recharge",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "recharge", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "resource_access",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role_permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "team",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "team_member",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )

    # Add XOR constraint: exactly one of user_id or organization_id must be set
    op.execute(
        """
        ALTER TABLE recharge
        ADD CONSTRAINT ck_recharge_entity_xor
        CHECK (
            (user_id IS NOT NULL AND organization_id IS NULL) OR
            (user_id IS NULL AND organization_id IS NOT NULL)
        )
    """
    )

    # Add account_status check constraint
    op.execute(
        """
        ALTER TABLE organization
        ADD CONSTRAINT ck_organization_account_status
        CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'PAST_DUE', 'CLOSED'))
    """
    )

    # Seed billing permissions
    op.execute(
        """
        INSERT INTO permission (name, description, resource_type, action)
        VALUES
            ('billing:read', 'View billing information, credits, and invoices', 'billing', 'read'),
            ('billing:write', 'Update billing settings, autorecharge, and business profile', 'billing', 'write')
        ON CONFLICT (name) DO NOTHING;
    """
    )

    # Owner gets all permissions (billing:read and billing:write)
    op.execute(
        """
        INSERT INTO role_permission (role_id, permission_id)
        SELECT r.id, p.id
        FROM role r, permission p
        WHERE r.name = 'Owner' AND r.is_system_role = true
          AND p.name IN ('billing:read', 'billing:write')
        ON CONFLICT DO NOTHING;
    """
    )

    # Admin gets billing:read and billing:write
    op.execute(
        """
        INSERT INTO role_permission (role_id, permission_id)
        SELECT r.id, p.id
        FROM role r, permission p
        WHERE r.name = 'Admin' AND r.is_system_role = true
          AND p.name IN ('billing:read', 'billing:write')
        ON CONFLICT DO NOTHING;
    """
    )

    # Member gets billing:read only
    op.execute(
        """
        INSERT INTO role_permission (role_id, permission_id)
        SELECT r.id, p.id
        FROM role r, permission p
        WHERE r.name = 'Member' AND r.is_system_role = true
          AND p.name = 'billing:read'
        ON CONFLICT DO NOTHING;
    """
    )

    # Viewer gets billing:read only
    op.execute(
        """
        INSERT INTO role_permission (role_id, permission_id)
        SELECT r.id, p.id
        FROM role r, permission p
        WHERE r.name = 'Viewer' AND r.is_system_role = true
          AND p.name = 'billing:read'
        ON CONFLICT DO NOTHING;
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove billing role_permission assignments
    op.execute(
        """
        DELETE FROM role_permission
        WHERE permission_id IN (
            SELECT id FROM permission WHERE name IN ('billing:read', 'billing:write')
        );
    """
    )

    # Remove billing permissions
    op.execute(
        """
        DELETE FROM permission WHERE name IN ('billing:read', 'billing:write');
    """
    )

    # Remove account_status check constraint
    op.execute(
        "ALTER TABLE organization DROP CONSTRAINT ck_organization_account_status"
    )

    # Remove XOR constraint
    op.execute("ALTER TABLE recharge DROP CONSTRAINT ck_recharge_entity_xor")

    op.alter_column(
        "team_member",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "team",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role_permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "resource_access",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("recharge_organization_id_fkey", "recharge", type_="foreignkey")
    op.drop_constraint("recharge_user_id_fkey", "recharge", type_="foreignkey")
    op.create_foreign_key(
        "recharge_user_id_fkey", "recharge", "users", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_recharge_organization_id"), table_name="recharge")
    op.alter_column("recharge", "user_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("recharge", "organization_id")
    op.alter_column(
        "permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_org_invite_org_email"),
        "organization_invite",
        ["organization_id", "invitee_email"],
        unique=False,
    )
    op.alter_column(
        "organization_invite",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_organization_stripe_customer_id"), table_name="organization")
    op.alter_column(
        "organization", "billing_user_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("organization", "billing_setup_complete")
    op.drop_column("organization", "billing_address")
    op.drop_column("organization", "tax_id")
    op.drop_column("organization", "business_name")
    op.drop_column("organization", "billing_email")
    op.drop_column("organization", "account_status")
    op.drop_column("organization", "autorecharge_qty")
    op.drop_column("organization", "autorecharge_threshold")
    op.drop_column("organization", "autorecharge")
    op.drop_column("organization", "stripe_customer_id")
    op.drop_column("organization", "credits")
    # ### end Alembic commands ###
