"""Add description fields to project and field_type tables

Revision ID: c4c58223e97d
Revises: d1110527c042
Create Date: 2025-06-17 21:48:15.438857

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4c58223e97d"
down_revision = "d1110527c042"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field_type",
        sa.Column("description", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "project",
        sa.Column("description", sa.String(length=256), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "description")
    op.drop_column("field_type", "description")
    # ### end Alembic commands ###
