"""Add business classification system with tax compliance

Revision ID: a25265d80402
Revises: 900e49cf9bcf
Create Date: 2025-07-04 17:42:43.104888

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a25265d80402"
down_revision = "900e49cf9bcf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_user",
        sa.Column(
            "account_type",
            sa.String(length=20),
            server_default="individual",
            nullable=False,
        ),
    )
    op.add_column(
        "auth_user",
        sa.Column("business_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("tax_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("business_type", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("business_address_line1", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("business_address_line2", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("business_city", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("business_state", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("business_country", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("business_postal_code", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "auth_user",
        sa.Column("tax_exempt", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "auth_user",
        sa.Column(
            "business_verified",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "auth_user",
        sa.Column("tax_jurisdiction", sa.String(length=100), nullable=True),
    )
    op.create_index(
        "idx_auth_user_account_type",
        "auth_user",
        ["account_type"],
        unique=False,
    )
    op.create_index(
        "idx_auth_user_account_type_verified",
        "auth_user",
        ["account_type", "business_verified"],
        unique=False,
    )
    op.create_index(
        "idx_auth_user_business_country",
        "auth_user",
        ["business_country"],
        unique=False,
    )
    op.create_index(
        "idx_auth_user_business_verified",
        "auth_user",
        ["business_verified"],
        unique=False,
    )
    op.create_index(
        "idx_auth_user_tax_id",
        "auth_user",
        ["tax_id"],
        unique=True,
        postgresql_where=sa.text("tax_id IS NOT NULL"),
    )
    op.create_index(
        "idx_auth_user_tax_jurisdiction",
        "auth_user",
        ["tax_jurisdiction"],
        unique=False,
    )
    op.create_check_constraint(
        "ck_auth_user_account_type",
        "auth_user",
        "account_type IN ('individual', 'business')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_auth_user_account_type", "auth_user")
    op.drop_index("idx_auth_user_tax_jurisdiction", table_name="auth_user")
    op.drop_index(
        "idx_auth_user_tax_id",
        table_name="auth_user",
        postgresql_where=sa.text("tax_id IS NOT NULL"),
    )
    op.drop_index("idx_auth_user_business_verified", table_name="auth_user")
    op.drop_index("idx_auth_user_business_country", table_name="auth_user")
    op.drop_index("idx_auth_user_account_type_verified", table_name="auth_user")
    op.drop_index("idx_auth_user_account_type", table_name="auth_user")
    op.drop_column("auth_user", "tax_jurisdiction")
    op.drop_column("auth_user", "business_verified")
    op.drop_column("auth_user", "tax_exempt")
    op.drop_column("auth_user", "business_postal_code")
    op.drop_column("auth_user", "business_country")
    op.drop_column("auth_user", "business_state")
    op.drop_column("auth_user", "business_city")
    op.drop_column("auth_user", "business_address_line2")
    op.drop_column("auth_user", "business_address_line1")
    op.drop_column("auth_user", "business_type")
    op.drop_column("auth_user", "tax_id")
    op.drop_column("auth_user", "business_name")
    op.drop_column("auth_user", "account_type")
    # ### end Alembic commands ###
