"""Update voice primary key to use a composite of voice_id and user_id

Revision ID: bfe2418ac281
Revises: c4f43793ef49
Create Date: 2025-07-11 16:36:35.699801

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfe2418ac281"
down_revision = "c4f43793ef49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("assistants_voice_id_fkey", "assistants", type_="foreignkey")
    op.create_foreign_key(
        "fk_assistants_voices",
        "assistants",
        "voices",
        ["user_id", "voice_id"],
        ["user_id", "voice_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_assistants_voices", "assistants", type_="foreignkey")
    op.create_foreign_key(
        "assistants_voice_id_fkey",
        "assistants",
        "voices",
        ["voice_id"],
        ["voice_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
