"""Remove unique constraint on favorite_project position

Revision ID: 7918ca0574ae
Revises: 1ee50d5a905a
Create Date: 2025-04-23 16:56:30.443536

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7918ca0574ae"
down_revision = "1ee50d5a905a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_favorite_position", "favorite_project", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_favorite_position", "favorite_project", ["user_id", "position"],
    )
    # ### end Alembic commands ###
