"""added default_hidden_columns field to table tile

Revision ID: a007b080a491
Revises: d9b3c968c46c
Create Date: 2025-06-30 17:11:26.517942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a007b080a491"
down_revision = "d9b3c968c46c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "table_tile",
        sa.Column(
            "default_hidden_columns",
            sa.Boolean(),
            server_default="t",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_tile", "default_hidden_columns")
    # ### end Alembic commands ###
