"""Add uniquness constraint for assistant name for a given user

Revision ID: 3693faa73c90
Revises: b9d21c93c850
Create Date: 2025-07-28 11:43:30.985513

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3693faa73c90"
down_revision = "b9d21c93c850"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_assistant_name",
        "assistants",
        ["user_id", "first_name", "surname"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_assistant_name", "assistants", type_="unique")
    # ### end Alembic commands ###
