"""Add granular models for Tab, Tile, TableTile, PlotTile, EditorTile, ViewTile

Revision ID: 46c2450d64eb
Revises: 2de4af3a96de
Create Date: 2025-05-02 15:44:07.459982

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46c2450d64eb"
down_revision = "2de4af3a96de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tab",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("interface_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("visible", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("active", sa.Boolean(), server_default="f", nullable=False),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("global_context", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("is_checkpoint", sa.Boolean(), server_default="f", nullable=False),
        sa.Column("checkpoint_or_active_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["interface_id"], ["interface.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "interface_id",
            "name",
            "is_checkpoint",
            name="tab_uq_interface_name_checkpoint",
        ),
    )
    op.create_index(op.f("ix_tab_interface_id"), "tab", ["interface_id"], unique=False)
    op.create_table(
        "tile",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tab_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("x_position", sa.Float(), nullable=False),
        sa.Column("y_position", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("min_width", sa.Float(), nullable=True),
        sa.Column("min_height", sa.Float(), nullable=True),
        sa.Column("visible", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("locked", sa.Boolean(), server_default="f", nullable=False),
        sa.Column("moved", sa.Boolean(), server_default="f", nullable=False),
        sa.Column("static", sa.Boolean(), server_default="f", nullable=False),
        sa.Column("context", sa.String(), nullable=True),
        sa.Column("table", sa.String(), nullable=True),
        sa.Column("auto_update", sa.String(), nullable=True),
        sa.Column("freeze", sa.String(), nullable=True),
        sa.Column("filters", sa.String(), nullable=True),
        sa.Column("common_filter", sa.String(), nullable=True),
        sa.Column("metric", sa.String(), nullable=True),
        sa.Column("is_checkpoint", sa.Boolean(), server_default="f", nullable=False),
        sa.Column("checkpoint_or_active_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["tab_id"], ["tab.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tab_id",
            "name",
            "is_checkpoint",
            name="tile_uq_tab_name_checkpoint",
        ),
    )
    op.create_index(op.f("ix_tile_tab_id"), "tile", ["tab_id"], unique=False)
    op.create_table(
        "editor_tile",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tile_id", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["tile_id"], ["tile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_editor_tile_tile_id"),
        "editor_tile",
        ["tile_id"],
        unique=True,
    )
    op.create_table(
        "plot_tile",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tile_id", sa.String(), nullable=False),
        sa.Column("plot_type", sa.String(), nullable=True),
        sa.Column("plot_scale_x", sa.String(), nullable=True),
        sa.Column("plot_scale_y", sa.String(), nullable=True),
        sa.Column("plot_aggregate", sa.String(), nullable=True),
        sa.Column("x_axis", sa.String(), nullable=True),
        sa.Column("y_axis", sa.String(), nullable=True),
        sa.Column("plot_group_by", sa.String(), nullable=True),
        sa.Column("plot_group_by_colors", sa.String(), nullable=True),
        sa.Column("bin_count", sa.String(), nullable=True),
        sa.Column("regression_line", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["tile_id"], ["tile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plot_tile_tile_id"), "plot_tile", ["tile_id"], unique=True)
    op.create_table(
        "table_tile",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tile_id", sa.String(), nullable=False),
        sa.Column("table_type", sa.String(), nullable=True),
        sa.Column("column_context", sa.String(), nullable=True),
        sa.Column("page_number", sa.String(), nullable=True),
        sa.Column("column_order", sa.String(), nullable=True),
        sa.Column("hidden_columns", sa.String(), nullable=True),
        sa.Column("sorting", sa.String(), nullable=True),
        sa.Column("grouping", sa.String(), nullable=True),
        sa.Column("group_sorting", sa.String(), nullable=True),
        sa.Column("columns_pin_left", sa.String(), nullable=True),
        sa.Column("columns_pin_right", sa.String(), nullable=True),
        sa.Column("selected", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["tile_id"], ["tile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_table_tile_tile_id"),
        "table_tile",
        ["tile_id"],
        unique=True,
    )
    op.create_table(
        "view_tile",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tile_id", sa.String(), nullable=False),
        sa.Column("base_index", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["tile_id"], ["tile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_view_tile_tile_id"), "view_tile", ["tile_id"], unique=True)
    op.add_column(
        "interface",
        sa.Column("is_checkpoint", sa.Boolean(), server_default="f", nullable=False),
    )
    op.add_column(
        "interface",
        sa.Column("checkpoint_or_active_id", sa.String(), nullable=True),
    )
    op.add_column("interface", sa.Column("updated_at", sa.TIMESTAMP(), nullable=True))
    op.add_column("interface", sa.Column("active_tab_id", sa.String(), nullable=True))
    op.drop_constraint("it_uq_project_name", "interface", type_="unique")
    op.create_unique_constraint(
        "it_uq_project_name_checkpoint",
        "interface",
        ["user_id", "project_id", "name", "is_checkpoint"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("it_uq_project_name_checkpoint", "interface", type_="unique")
    op.create_unique_constraint(
        "it_uq_project_name",
        "interface",
        ["user_id", "project_id", "name"],
    )
    op.drop_column("interface", "active_tab_id")
    op.drop_column("interface", "updated_at")
    op.drop_column("interface", "checkpoint_or_active_id")
    op.drop_column("interface", "is_checkpoint")
    op.drop_index(op.f("ix_view_tile_tile_id"), table_name="view_tile")
    op.drop_table("view_tile")
    op.drop_index(op.f("ix_table_tile_tile_id"), table_name="table_tile")
    op.drop_table("table_tile")
    op.drop_index(op.f("ix_plot_tile_tile_id"), table_name="plot_tile")
    op.drop_table("plot_tile")
    op.drop_index(op.f("ix_editor_tile_tile_id"), table_name="editor_tile")
    op.drop_table("editor_tile")
    op.drop_index(op.f("ix_tile_tab_id"), table_name="tile")
    op.drop_table("tile")
    op.drop_index(op.f("ix_tab_interface_id"), table_name="tab")
    op.drop_table("tab")
    # ### end Alembic commands ###
