"""unique_id_column and unique_id_name to Context table for sequential ID generation

Revision ID: d1110527c042
Revises: b36d5295805d
Create Date: 2025-06-16 19:08:37.732134

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1110527c042"
down_revision = "b36d5295805d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column("unique_id_column", sa.Boolean(), server_default="f", nullable=False),
    )
    op.add_column(
        "context",
        sa.Column(
            "unique_id_name",
            sa.String(),
            server_default="row_id",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("context", "unique_id_name")
    op.drop_column("context", "unique_id_column")
    # ### end Alembic commands ###
