"""Add param_version table to track parameter versions in a non-blocking manner.

Revision ID: 0052a63d731e
Revises: 450bf2f1266a
Create Date: 2025-03-27 12:31:48.437783

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0052a63d731e"
down_revision = "450bf2f1266a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "param_version",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=False),
        sa.Column("param_key", sa.String(), nullable=False),
        sa.Column("last_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["context_id"], ["context.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "context_id", "param_key"),
    )
    op.create_index(
        "idx_param_version_project_key",
        "param_version",
        ["project_id", "context_id", "param_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_param_version_project_key", table_name="param_version")
    op.drop_table("param_version")
    # ### end Alembic commands ###
