"""Add user_local_desktop field and constraint to Assistant table

Revision ID: 21edec5565a4
Revises: 51f08d4846c7
Create Date: 2025-09-19 15:45:17.241486

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21edec5565a4"
down_revision = "51f08d4846c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column("user_local_desktop", sa.String(), nullable=True),
    )
    # Manually added CHECK constraint to enforce allowed values
    op.create_check_constraint(
        "ck_assistant_user_local_desktop",
        "assistants",
        "user_local_desktop IN ('ubuntu', 'windows', 'macos')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually added drop for the CHECK constraint
    op.drop_constraint("ck_assistant_user_local_desktop", "assistants", type_="check")
    op.drop_column("assistants", "user_local_desktop")
    # ### end Alembic commands ###
