"""added the user phone to the assistant table

Revision ID: 2c12988f18c9
Revises: 000958ab98b9
Create Date: 2025-05-30 13:32:34.858715

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c12988f18c9"
down_revision = "000958ab98b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("user_phone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "user_phone")
    # ### end Alembic commands ###
