"""Add unique constraint column to field_type table

Revision ID: b36d5295805d
Revises: 3de7b0446970
Create Date: 2025-06-16 14:00:31.764548

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b36d5295805d"
down_revision = "3de7b0446970"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field_type",
        sa.Column("unique", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("field_type", "unique")
    # ### end Alembic commands ###
