"""Create assistants table for managing custom agents

Revision ID: 254925615db2
Revises: 7918ca0574ae
Create Date: 2025-04-25 18:20:05.518884

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "254925615db2"
down_revision = "7918ca0574ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistants",
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("weekly_limit", sa.Numeric(), nullable=False),
        sa.Column("max_parallel", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_index(
        op.f("ix_assistants_user_id"),
        "assistants",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assistants_user_id"), table_name="assistants")
    op.drop_table("assistants")
    # ### end Alembic commands ###
