"""add icon to project / drop icon from favorite_project

Revision ID: b9d21c93c850
Revises: bfe2418ac281
Create Date: 2025-07-21 14:57:52.157932

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9d21c93c850"
down_revision = "bfe2418ac281"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorite_project", "icon")
    op.add_column(
        "project",
        sa.Column("icon", sa.String(), server_default="folder", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "icon")
    op.add_column(
        "favorite_project",
        sa.Column("icon", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
