"""Update voice primary key to use a composite of voice_id and user_id

Revision ID: bfe2418ac281
Revises: c4f43793ef49
Create Date: 2025-07-11 16:36:35.699801

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfe2418ac281"
down_revision = "c4f43793ef49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, drop the existing foreign key constraint
    op.drop_constraint("assistants_voice_id_fkey", "assistants", type_="foreignkey")

    # Update the voices table to have a composite primary key
    # Drop the existing primary key constraint
    op.drop_constraint("voices_pkey", "voices", type_="primary")

    # Create the new composite primary key
    op.create_primary_key("voices_pkey", "voices", ["voice_id", "user_id"])

    # Now create the foreign key constraint referencing the composite key
    op.create_foreign_key(
        "fk_assistants_voices",
        "assistants",
        "voices",
        ["user_id", "voice_id"],
        ["user_id", "voice_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the foreign key constraint
    op.drop_constraint("fk_assistants_voices", "assistants", type_="foreignkey")

    # Revert the voices table to single primary key
    op.drop_constraint("voices_pkey", "voices", type_="primary")
    op.create_primary_key("voices_pkey", "voices", ["voice_id"])

    # Recreate the original foreign key constraint
    op.create_foreign_key(
        "assistants_voice_id_fkey",
        "assistants",
        "voices",
        ["voice_id"],
        ["voice_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
