services:
  api:
    environment:
      # Adds opentelemetry endpoint.
      ORCHESTRA_OPENTELEMETRY_ENDPOINT: "http://otel-collector:4317"

  otel-collector:
    build:
      context: .
      dockerfile: ./deploy/otel.Dockerfile
    image: otel-collector:${ORCHESTRA_VERSION:-latest}
    environment:
      - JAEGER_ENDPOINT=jaeger-lz5fmz6i7q-ew.a.run.app:443
    ports:
      # Collector's endpoint
    - "4317:4317"

  jaeger:
    image: jaegertracing/all-in-one:1.52
    hostname: jaeger
    ports:
      # Jaeger UI
    - 16686:16686
