services:
  api:
    environment:
      # Adds opentelemetry endpoint.
      ORCHESTRA_OPENTELEMETRY_ENDPOINT: "jaeger:4317"
      ORCHESTRA_OPENTELEMETRY_SECURE: "True"

  jaeger:
    image: jaegertracing/all-in-one:1.52
    hostname: jaeger
    ports:
      # Jaeger UI
    - 16686:16686
