services:
  api:
    environment:
      # OpenTelemetry configuration
      ORCHESTRA_OTEL: "true"
      ORCHESTRA_OTEL_ENDPOINT: "jaeger:4317"
      ORCHESTRA_OTEL_SECURE: "true"

  jaeger:
    image: jaegertracing/all-in-one:1.52
    hostname: jaeger
    ports:
      # Jaeger UI
    - 16686:16686
