from providers.completion.base_completion_provider import BaseCompletionProvider


class TogetherAI(BaseCompletionProvider):
    """
    A completion provider that uses the TogetherAI service.

    Supported models: https://docs.together.ai/docs/inference-models
    """

    supported_models = {
        "yi-34b": "together_ai/zero-one-ai/Yi-34B",
        "yi-6b": "together_ai/zero-one-ai/Yi-6B",
        "yi-34b-chat": "together_ai/zero-one-ai/Yi-34B-Chat",
        "alpaca-7b": "together_ai/togethercomputer/alpaca-7b",
        "chronos-hermes-13b": "together_ai/Austism/chronos-hermes-13b",
        "codellama-13b": "together_ai/togethercomputer/CodeLlama-13b",
        "codellama-34b": "together_ai/togethercomputer/CodeLlama-34b",
        "codellama-7b": "together_ai/togethercomputer/CodeLlama-7b",
        "codellama-13b-instruct": "together_ai/togethercomputer/CodeLlama-13b-Instruct",
        "codellama-34b-instruct": "together_ai/togethercomputer/CodeLlama-34b-Instruct",
        "codellama-7b-instruct": "together_ai/togethercomputer/CodeLlama-7b-Instruct",
        "codellama-13b-python": "together_ai/togethercomputer/CodeLlama-13b-Python",
        "codellama-34b-python": "together_ai/togethercomputer/CodeLlama-34b-Python",
        "codellama-7b-python": "together_ai/togethercomputer/CodeLlama-7b-Python",
        "codegen2-16b": "together_ai/togethercomputer/codegen2-16B",
        "codegen2-7b": "together_ai/togethercomputer/codegen2-7B",
        "dolly-v2-12b": "together_ai/databricks/dolly-v2-12b",
        "dolly-v2-3b": "together_ai/databricks/dolly-v2-3b",
        "dolly-v2-7b": "together_ai/databricks/dolly-v2-7b",
        "falcon-40b": "together_ai/togethercomputer/falcon-40b",
        "falcon-7b": "together_ai/togethercomputer/falcon-7b",
        "falcon-40b-instruct": "together_ai/togethercomputer/falcon-40b-instruct",
        "falcon-7b-instruct": "together_ai/togethercomputer/falcon-7b-instruct",
        "flan-t5-xl": "together_ai/google/flan-t5-xl",
        "flan-t5-xxl": "together_ai/google/flan-t5-xxl",
        "gpt-j-6b": "together_ai/EleutherAI/gpt-j-6b",
        "gpt-jt-6b-v1": "together_ai/togethercomputer/GPT-JT-6B-v1",
        "gpt-jt-moderation-6b": "together_ai/togethercomputer/GPT-JT-Moderation-6B",
        "gpt-neox-20b": "together_ai/EleutherAI/gpt-neox-20b",
        "gpt-neoxt-chat-base-20b": "together_ai/togethercomputer/GPT-NeoXT-Chat-Base-20B",
        "guanaco-13b": "together_ai/togethercomputer/guanaco-13b",
        "guanaco-33b": "together_ai/togethercomputer/guanaco-33b",
        "guanaco-65b": "together_ai/togethercomputer/guanaco-65b",
        "guanaco-7b": "together_ai/togethercomputer/guanaco-7b",
        "instructcodet5p-16b": "together_ai/Salesforce/instructcodet5p-16b",
        "koala-13b": "together_ai/togethercomputer/Koala-13B",
        "koala-7b": "together_ai/togethercomputer/Koala-7B",
        "llama-13b": "together_ai/huggyllama/llama-13b",
        "llama-30b": "together_ai/huggyllama/llama-30b",
        "llama-65b": "together_ai/huggyllama/llama-65b",
        "llama-7b": "together_ai/huggyllama/llama-7b",
        "llama-2-13b": "together_ai/togethercomputer/llama-2-13b",
        "llama-2-70b": "together_ai/togethercomputer/llama-2-70b",
        "llama-2-7b": "together_ai/togethercomputer/llama-2-7b",
        "llama-2-13b-chat": "together_ai/togethercomputer/llama-2-13b-chat",
        "llama-2-70b-chat": "together_ai/togethercomputer/llama-2-70b-chat",
        "llama-2-7b-chat": "together_ai/togethercomputer/llama-2-7b-chat",
        "llama-2-7b-32k": "together_ai/togethercomputer/LLaMA-2-7B-32K",
        "llama-2-7b-32k-instruct": "together_ai/togethercomputer/Llama-2-7B-32K-Instruct",
        "llemma_7b": "together_ai/EleutherAI/llemma_7b",
        "mpt-7b": "together_ai/togethercomputer/mpt-7b",
        "mpt-30b-chat": "together_ai/togethercomputer/mpt-30b-chat",
        "mpt-7b-chat": "together_ai/togethercomputer/mpt-7b-chat",
        "mpt-7b-instruct": "together_ai/togethercomputer/mpt-7b-instruct",
        "mistral-7b-v0.1": "together_ai/mistralai/Mistral-7B-v0.1",
        "mistral-7b-instruct-v0.1": "together_ai/mistralai/Mistral-7B-Instruct-v0.1",
        "mythomax-l2-13b": "together_ai/Gryphe/MythoMax-L2-13b",
        "nsql-6b": "together_ai/NumbersStation/nsql-6B",
        "nsql-llama-2-7b": "together_ai/NumbersStation/nsql-llama-2-7B",
        "nexusraven-v2-13b": "together_ai/Nexusflow/NexusRaven-V2-13B",
        "nous-capybara-7b-v1p9": "together_ai/NousResearch/Nous-Capybara-7B-V1p9",
        "nous-hermes-13b": "together_ai/NousResearch/Nous-Hermes-13b",
        "nous-hermes-llama2-70b": "together_ai/NousResearch/Nous-Hermes-Llama2-70b",
        "nous-hermes-llama-2-7b": "together_ai/NousResearch/Nous-Hermes-llama-2-7b",
        "nous-hermes-llama2-13b": "together_ai/NousResearch/Nous-Hermes-Llama2-13b",
        "oasst-sft-6-llama-30b-xor": "together_ai/OpenAssistant/oasst-sft-6-llama-30b-xor",
        "oasst-sft-4-pythia-12b-epoch-3.5": "together_ai/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5",
        "stablelm-7b-sft-v7-epoch-3": "together_ai/OpenAssistant/stablelm-7b-sft-v7-epoch-3",
        "openhermes-2-mistral-7b": "together_ai/teknium/OpenHermes-2-Mistral-7B",
        "openhermes-2p5-mistral-7b": "together_ai/teknium/OpenHermes-2p5-Mistral-7B",
        "mistral-7b-openorca": "together_ai/Open-Orca/Mistral-7B-OpenOrca",
        "phind-codellama-34b-python-v1": "together_ai/Phind/Phind-CodeLlama-34B-Python-v1",
        "phind-codellama-34b-v2": "together_ai/Phind/Phind-CodeLlama-34B-v2",
        "platypus2-70b-instruct": "together_ai/garage-bAInd/Platypus2-70B-instruct",
        "pythia-12b-v0": "together_ai/EleutherAI/pythia-12b-v0",
        "pythia-1b-v0": "together_ai/EleutherAI/pythia-1b-v0",
        "pythia-2.8b-v0": "together_ai/EleutherAI/pythia-2.8b-v0",
        "pythia-6.9b": "together_ai/EleutherAI/pythia-6.9b",
        "pythia-chat-base-7b-v0.16": "together_ai/togethercomputer/Pythia-Chat-Base-7B-v0.16",
        "qwen-7b": "together_ai/togethercomputer/Qwen-7B",
        "qwen-7b-chat": "together_ai/togethercomputer/Qwen-7B-Chat",
        "remm-slerp-l2-13b": "together_ai/Undi95/ReMM-SLERP-L2-13B",
        "redpajama-incite-base-3b-v1": "together_ai/togethercomputer/RedPajama-INCITE-Base-3B-v1",
        "redpajama-incite-7b-base": "together_ai/togethercomputer/RedPajama-INCITE-7B-Base",
        "redpajama-incite-chat-3b-v1": "together_ai/togethercomputer/RedPajama-INCITE-Chat-3B-v1",
        "redpajama-incite-7b-chat": "together_ai/togethercomputer/RedPajama-INCITE-7B-Chat",
        "redpajama-incite-instruct-3b-v1": "together_ai/togethercomputer/RedPajama-INCITE-Instruct-3B-v1",
        "redpajama-incite-7b-instruct": "together_ai/togethercomputer/RedPajama-INCITE-7B-Instruct",
        "replit-code-v1-3b": "together_ai/togethercomputer/replit-code-v1-3b",
        "solar-0-70b-16bit": "together_ai/upstage/SOLAR-0-70b-16bit",
        "sqlcoder": "together_ai/defog/sqlcoder",
        "stablelm-base-alpha-3b": "together_ai/stabilityai/stablelm-base-alpha-3b",
        "stablelm-base-alpha-7b": "together_ai/stabilityai/stablelm-base-alpha-7b",
        "starcoder": "together_ai/bigcode/starcoder",
        "starchat-alpha": "together_ai/HuggingFaceH4/starchat-alpha",
        "toppy-m-7b": "together_ai/Undi95/Toppy-M-7B",
        "vicuna-13b-v1.3": "together_ai/lmsys/vicuna-13b-v1.3",
        "vicuna-7b-v1.3": "together_ai/lmsys/vicuna-7b-v1.3",
        "vicuna-13b-v1.5": "together_ai/lmsys/vicuna-13b-v1.5",
        "vicuna-7b-v1.5": "together_ai/lmsys/vicuna-7b-v1.5",
        "vicuna-13b-v1.5-16k": "together_ai/lmsys/vicuna-13b-v1.5-16k",
        "fastchat-t5-3b-v1.0": "together_ai/lmsys/fastchat-t5-3b-v1.0",
        "wizardcoder-15b-v1.0": "together_ai/WizardLM/WizardCoder-15B-V1.0",
        "wizardlm-70b-v1.0": "together_ai/WizardLM/WizardLM-70B-V1.0",
        "wizardlm-13b-v1.2": "together_ai/WizardLM/WizardLM-13B-V1.2",
    }
