// DB schema of the model hub
// Docs: https://dbml.dbdiagram.io/docs

Table model {
  id integer [primary key]
  mdl_code varchar // e.g. llama-2-70b-chat
  user_id varchar // uploaded by
  uploaded_at timestamp [not null]
  task varchar [not null]
  description text [not null]
  license varchar
  input_args_format text [not null]
  output_format text [not null]
  custom_fields text [note: 'Optional field for extra key:value pairs']
  active boolean [not null]
  is_private boolean [not null]
}

Table license {
  name varchar [primary key]
  image_url varchar
  description text [not null]
}

Table task {
  name varchar [primary key]
  modality varchar [not null]
}

Table modality {
  name varchar [primary key]
}

Table endpoint {
  id integer [primary key]
  mdl_id integer [not null]
  provider_id integer [not null]
  created_at timestamp [not null]
}

Table provider {
  id integer [primary key]
  name varchar [not null]
  image_url varchar [not null]
  description text
}

Table datapoint {
  id integer [primary key]
  benchmark_run_id integer [not null]
  measured_at timestamp [not null]
  metric_name varchar [not null]
  value decimal [not null]
  tooltip varchar
}

Table benchmark_regime {
  name varchar [primary key]
}

Table benchmark_region {
  name varchar [primary key]
}

Table benchmark_run {
  id integer [primary key]
  endpoint_id integer [not null]
  regime varchar [not null]
  region varchar [not null]
  seq_len varchar [not null]
}

Table benchmark_seq_len {
  name varchar [primary key]
}

Table metric {
  name varchar [primary key]
  display_name varchar [not null]
  tooltip varchar
  priority integer [not null]
  plottable boolean [not null] // Not sure if this is a word open to suggestions
}

Table query {
  id integer [primary key]
  user_id varchar [not null]
  at timestamp [not null]
  endpoint_id integer [not null]
  credits decimal [not null]
}

Table users {
  // This id is the same as the user id in the console app table of users
  // Every time a user is created in the console app, a new entry should
  // be added here automatically with a default balance.
  id varchar [primary key]
  credits decimal [not null]
}

Table recharge {
  id integer [primary key]
  at timestamp [not null]
  user_id varchar [not null]
  quantity decimal [not null]
  type varchar [not null]
}

Table recharge_type {
  type varchar [primary key] // daily, free, manual, ...
}

Ref: model.user_id > users.id
Ref: model.task > task.name
Ref: model.license > license.name
Ref: task.modality > modality.name
Ref: endpoint.mdl_id > model.id
Ref: endpoint.provider_id > provider.id
Ref: datapoint.benchmark_run_id > benchmark_run.id
Ref: datapoint.metric_name > metric.name
Ref: query.user_id > users.id
Ref: query.endpoint_id > endpoint.id
Ref: recharge.user_id > users.id
Ref: recharge.type > recharge_type.type
Ref: benchmark_run.regime > benchmark_regime.name
Ref: benchmark_run.region > benchmark_region.name
Ref: benchmark_run.endpoint_id > endpoint.id
Ref: benchmark_run.seq_len > benchmark_seq_len.name
