"""DAO for CanvasToken model operations."""

from typing import Optional

from sqlalchemy.orm import Session

from orchestra.db.models.orchestra_models import CanvasToken


class CanvasTokenDAO:
    """Data access object for the canvas_token routing table."""

    def __init__(self, session: Session):
        self.session = session

    def register(
        self,
        token: str,
        context_name: str,
        project_id: int,
        user_id: str,
        organization_id: Optional[int],
        visibility: str = "private",
        status: str = "draft",
    ) -> CanvasToken:
        """Register a new token mapping.

        The token is generated by Unify with ``secrets.token_urlsafe``; the
        PRIMARY KEY enforces uniqueness rather than a pre-check, so two
        assistants publishing at once cannot both win.
        """
        entry = CanvasToken(
            token=token,
            context_name=context_name,
            project_id=project_id,
            user_id=user_id,
            organization_id=organization_id,
            visibility=visibility,
            status=status,
        )
        self.session.add(entry)
        self.session.flush()
        return entry

    def get_by_token(self, token: str) -> Optional[CanvasToken]:
        """Resolve a token to its context mapping."""
        return (
            self.session.query(CanvasToken).filter(CanvasToken.token == token).first()
        )

    def set_state(
        self,
        token: str,
        *,
        visibility: Optional[str] = None,
        status: Optional[str] = None,
    ) -> Optional[CanvasToken]:
        """Update the authorization columns for one token.

        These two are mutable on their own because both are operational rather
        than authored: publishing a draft and quarantining a live canvas both
        need to take effect without rewriting the canvas or reissuing its URL.
        """
        entry = self.get_by_token(token)
        if not entry:
            return None
        if visibility is not None:
            entry.visibility = visibility
        if status is not None:
            entry.status = status
        self.session.flush()
        return entry

    def delete_by_token(self, token: str) -> bool:
        """Remove a token mapping. Returns True if a row was deleted."""
        entry = self.get_by_token(token)
        if not entry:
            return False
        self.session.delete(entry)
        self.session.flush()
        return True
