experiment:
  run_name: train_your_router

data:
  data_paths:
  - /train_data.jsonl
  validation_path: /validation_data.jsonl
  train_split_ratio: 0.99
  num_training_samples: 100000

model:
  architecture: dcn
  prompt_encoder: "microsoft/deberta-v3-xsmall"
  embed_dim: 64
  dropout: 0.15

train:
  epochs: 20
  batch_size: 16
  gradient_acc_steps: 1
  max_num_tokens: 256
  eval_steps: 30
  save_epochs: true
  save_eval: false
  score_mapping: {"irrelevant": 0, "very_bad": 0, "very_good": 0.8, "very bad": 0, "bad": 0, "good": 0.5, "satisfactory": 0.5, "very good": 0.8, "excellent": 1.0}
  device: cuda
  optimizer:
    name: AdamW
    prompt_encoder_lr: 2e-5
    rest_lr: 2e-5
  loss_type: mse
  metrics: []

validation:
  batch_size: 32
  metrics: []
  media: []
