name: Deploy to Google Cloud VM

env:
  GH_WORKDIR: pubsub_2_clickhouse
  SERVICE_NAME: pubsub_2_clickhouse
  GCLOUD_PROJECT: saas-368716
  GCLOUD_ZONE: europe-west1-b
  GCLOUD_WORKDIR: /opt/pubsub-2-clickhouse
  GCLOUD_INSTANCE: pubsub-2-clickhouse
  GCLOUD_USERNAME: serviceuser

# TODO: Only when pushing to main
# TODO: Staging?

on:
  push:
    branches:
    - pubsub-2-clickhouse
    paths:
    - $GH_WORKDIR/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        project_id: $GCLOUD_PROJECT

    - name: Copy Python script to VM
      run: |
        gcloud compute scp $GH_WORKDIR/main.py $GCLOUD_USERNAME@$GCLOUD_INSTANCE:$GCLOUD_WORKDIR --zone $GCLOUD_ZONE

    - name: Copy service file to VM
      run: |
        gcloud compute scp $GH_WORKDIR/$SERVICE_NAME.service $GCLOUD_USERNAME@$GCLOUD_INSTANCE:/etc/systemd/system/ --zone $GCLOUD_ZONE

    - name: Reload and restart the service on VM
      run: |
        gcloud compute ssh $GCLOUD_USERNAME@$GCLOUD_INSTANCE --zone $GCLOUD_ZONE --command "
          sudo systemctl daemon-reload &&
          sudo systemctl restart $SERVICE_NAME.service &&
          sudo systemctl enable $SERVICE_NAME.service
        "
