name: Update docs
on:
  push:
    branches:
      - "main"

jobs:
  update-docs:
    name: Update docs
    uses: unifyai/workflows/.github/workflows/docs.yml@main
    secrets: inherit
    with:
      repo-name: modelhub
