name: Performance tests

on:
  workflow_dispatch:

jobs:
  performance_tests:
    runs-on: ubuntu-latest
    environment: orchestra-testing
    services:
      orchestra-db:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_PASSWORD: orchestra
          POSTGRES_USER: orchestra
          POSTGRES_DB: orchestra
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 5432:5432
    steps:

    - uses: actions/checkout@v4
    - name: Auth into Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install deps
      run: |
        pip install "poetry>=2.1.0"
        poetry config virtualenvs.create false
        poetry install

    - name: Run pytest performance tests
      run: poetry run pytest -p no:warnings -vv orchestra/tests/test_log -m "performance" -s
      env:
        ORCHESTRA_HOST: "0.0.0.0"
        ORCHESTRA_DB_HOST: localhost
        GCP_PROJECT_ID: saas-368716
        ORCHESTRA_ADMIN_KEY: ${{ secrets.ORCHESTRA_ADMIN_KEY }}
        AUTH_ACCOUNT_API_KEY: ${{ secrets.AUTH_ACCOUNT_API_KEY }}
        AUTH_ACCOUNT_USER_ID: ${{ secrets.AUTH_ACCOUNT_USER_ID }}
        ORCHESTRA_PERF_LOG_EVENTS_COUNT: 50000

    - name: Upload performance metrics
      uses: actions/upload-artifact@v4
      with:
        name: perf_timings
        path: perf_timings.json
