name: Testing orchestra

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run black check
      run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run flake8 check
      run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run mypy check
      run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    services:

      orchestra-db:
        image: postgres:13.8-bullseye
        env:
          POSTGRES_PASSWORD: orchestra
          POSTGRES_USER: orchestra
          POSTGRES_DB: orchestra
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="orchestra" .
      env:
        ORCHESTRA_HOST: "0.0.0.0"
        ORCHESTRA_DB_HOST: localhost
        ORCHESTRA_OCTOAI_API_KEY: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNkMjMzOTQ5In0.eyJzdWIiOiI2MmJkOWVjOS05YjQwLTQ4ZWEtODRiNC1kMjYyMGRiNWVmNmMiLCJ0eXBlIjoidXNlckFjY2Vzc1Rva2VuIiwidGVuYW50SWQiOiIyNzQxYzAzNi1mYjUzLTQ4NjktOGVlYy1hMTUyNmU2ZWI0Y2IiLCJ1c2VySWQiOiI0MzhhYzJiZC1iMzBmLTRlODktYmEyOS00MmQxOWY0OTk3MWMiLCJyb2xlcyI6WyJGRVRDSC1ST0xFUy1CWS1BUEkiXSwicGVybWlzc2lvbnMiOlsiRkVUQ0gtUEVSTUlTU0lPTlMtQlktQVBJIl0sImF1ZCI6IjNkMjMzOTQ5LWEyZmItNGFiMC1iN2VjLTQ2ZjYyNTVjNTEwZSIsImlzcyI6Imh0dHBzOi8vaWRlbnRpdHkub2N0b21sLmFpIiwiaWF0IjoxNzAzMTU2MDM0fQ.mNc6rHurbHNucR_SzkvWJgTUXwv_cHl8Dt_bujc7UKGdmYa-hG5ff5QJ_WtMcIHPrmPfOgIWjvf7PNUWQtjqsArpI1z3WXHt6KoQnKNBYQsSn6y46MAliixTHWc0qh63bzKhc8Jvh2D6NCHEfYdmRxJuxL_wkisCWD1Kt-hkvk1kfi4ALgjFmr_GFsRQH_P1-85ld4P2y27tGiUWPg2lGyd6H4KJJpOnbOHmlbUfxAgr4cY4UsoZqvjTmD_rEMD9LEgel6HZuH34mYcRxLyoq7OnGBLCWSbvg3Iv_A_PdZqwKY3EjXObsaN19nhFcBmJybPJmMCdJpI-xgWzIK8Gww" # TODO: replace with secrets
        ORCHESTRA_OPENAI_API_KEY: "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" #TODO: replace with secrets from GH actions
