name: Trigger Default Evals

on:
  workflow_dispatch:

jobs:
  trigger_default_evals:
    name: Trigger Default Evals
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Trigger Evals
      run: |
        export API_KEY=${{ secrets.USER_API_KEY }}
        python3 -m pip install requests
        python3 trigger_default_evals.py
