name: Update LiteLLM

on:
  # schedule:
  #   # runs everyday at 23:00 UTC
  # - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  update_litellm:
    name: Update LiteLLM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: true

    - name: Update LiteLLM
      run: |
        pwd
        cd orchestra
        poetry shell
        poetry add litellm@latest
        git status
