name: Upload Data for On-Prem

on:
  schedule:
  - cron: '0 23 * * *'
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  upload_data_for_on_prem:
    name: Upload Data for On-Prem
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'


    - name: Auth into Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_DEFAULT_CREDENTIALS }}'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Upload on-prem data
      id: update_litellm
      run: |
        python3 -m pip install cloud-sql-python-connector[pg8000]
        python3 upload_data_for_on_prem.py
      env:
        INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
